module.exports = {
  'Africa/Abidjan': 'توقيت غرينتش',
  'Africa/Accra': 'توقيت غرينتش',
  'Africa/Addis_Ababa': 'توقيت شرق أفريقيا',
  'Africa/Algiers': 'توقيت وسط أوروبا الرسمي',
  'Africa/Asmara': 'توقيت شرق أفريقيا',
  'Africa/Bamako': 'توقيت غرينتش',
  'Africa/Bangui': 'توقيت غرب أفريقيا الرسمي',
  'Africa/Banjul': 'توقيت غرينتش',
  'Africa/Bissau': 'توقيت غرينتش',
  'Africa/Blantyre': 'توقيت وسط أفريقيا',
  'Africa/Brazzaville': 'توقيت غرب أفريقيا الرسمي',
  'Africa/Bujumbura': 'توقيت وسط أفريقيا',
  'Africa/Cairo': 'توقيت شرق أوروبا الرسمي',
  'Africa/Casablanca': 'توقيت غرب أوروبا الرسمي',
  'Africa/Ceuta': 'توقيت وسط أوروبا الرسمي',
  'Africa/Conakry': 'توقيت غرينتش',
  'Africa/Dakar': 'توقيت غرينتش',
  'Africa/Dar_es_Salaam': 'توقيت شرق أفريقيا',
  'Africa/Djibouti': 'توقيت شرق أفريقيا',
  'Africa/Douala': 'توقيت غرب أفريقيا الرسمي',
  'Africa/El_Aaiun': 'توقيت غرب أوروبا الرسمي',
  'Africa/Freetown': 'توقيت غرينتش',
  'Africa/Gaborone': 'توقيت وسط أفريقيا',
  'Africa/Harare': 'توقيت وسط أفريقيا',
  'Africa/Johannesburg': 'توقيت جنوب أفريقيا',
  'Africa/Juba': 'توقيت شرق أفريقيا',
  'Africa/Kampala': 'توقيت شرق أفريقيا',
  'Africa/Khartoum': 'توقيت وسط أفريقيا',
  'Africa/Kigali': 'توقيت وسط أفريقيا',
  'Africa/Kinshasa': 'توقيت غرب أفريقيا الرسمي',
  'Africa/Lagos': 'توقيت غرب أفريقيا الرسمي',
  'Africa/Libreville': 'توقيت غرب أفريقيا الرسمي',
  'Africa/Lome': 'توقيت غرينتش',
  'Africa/Luanda': 'توقيت غرب أفريقيا الرسمي',
  'Africa/Lubumbashi': 'توقيت وسط أفريقيا',
  'Africa/Lusaka': 'توقيت وسط أفريقيا',
  'Africa/Malabo': 'توقيت غرب أفريقيا الرسمي',
  'Africa/Maputo': 'توقيت وسط أفريقيا',
  'Africa/Maseru': 'توقيت جنوب أفريقيا',
  'Africa/Mbabane': 'توقيت جنوب أفريقيا',
  'Africa/Mogadishu': 'توقيت شرق أفريقيا',
  'Africa/Monrovia': 'توقيت غرينتش',
  'Africa/Nairobi': 'توقيت شرق أفريقيا',
  'Africa/Ndjamena': 'توقيت غرب أفريقيا الرسمي',
  'Africa/Niamey': 'توقيت غرب أفريقيا الرسمي',
  'Africa/Nouakchott': 'توقيت غرينتش',
  'Africa/Ouagadougou': 'توقيت غرينتش',
  'Africa/Porto-Novo': 'توقيت غرب أفريقيا الرسمي',
  'Africa/Sao_Tome': 'توقيت غرينتش',
  'Africa/Tripoli': 'توقيت شرق أوروبا الرسمي',
  'Africa/Tunis': 'توقيت وسط أوروبا الرسمي',
  'Africa/Windhoek': 'توقيت وسط أفريقيا',
  'America/Adak': 'توقيت هاواي ألوتيان الرسمي',
  'America/Anchorage': 'التوقيت الرسمي لألاسكا',
  'America/Anguilla': 'التوقيت الرسمي الأطلسي',
  'America/Antigua': 'التوقيت الرسمي الأطلسي',
  'America/Araguaina': 'توقيت برازيليا الرسمي',
  'America/Argentina/Buenos_Aires': 'توقيت الأرجنتين الرسمي',
  'America/Argentina/Catamarca': 'توقيت الأرجنتين الرسمي',
  'America/Argentina/Cordoba': 'توقيت الأرجنتين الرسمي',
  'America/Argentina/Jujuy': 'توقيت الأرجنتين الرسمي',
  'America/Argentina/La_Rioja': 'توقيت الأرجنتين الرسمي',
  'America/Argentina/Mendoza': 'توقيت الأرجنتين الرسمي',
  'America/Argentina/Rio_Gallegos': 'توقيت الأرجنتين الرسمي',
  'America/Argentina/Salta': 'توقيت الأرجنتين الرسمي',
  'America/Argentina/San_Juan': 'توقيت الأرجنتين الرسمي',
  'America/Argentina/San_Luis': 'توقيت غرب الأرجنتين الرسمي',
  'America/Argentina/Tucuman': 'توقيت الأرجنتين الرسمي',
  'America/Argentina/Ushuaia': 'توقيت الأرجنتين الرسمي',
  'America/Aruba': 'التوقيت الرسمي الأطلسي',
  'America/Asuncion': 'توقيت باراغواي الرسمي',
  'America/Atikokan': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Bahia': 'توقيت برازيليا الرسمي',
  'America/Bahia_Banderas': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Barbados': 'التوقيت الرسمي الأطلسي',
  'America/Belem': 'توقيت برازيليا الرسمي',
  'America/Belize': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Blanc-Sablon': 'التوقيت الرسمي الأطلسي',
  'America/Boa_Vista': 'توقيت الأمازون الرسمي',
  'America/Bogota': 'توقيت كولومبيا الرسمي',
  'America/Boise': 'التوقيت الجبلي الرسمي لأمريكا الشمالية',
  'America/Cambridge_Bay': 'التوقيت الجبلي الرسمي لأمريكا الشمالية',
  'America/Campo_Grande': 'توقيت الأمازون الرسمي',
  'America/Cancun': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Caracas': 'توقيت فنزويلا',
  'America/Cayenne': 'توقيت غايانا الفرنسية',
  'America/Cayman': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Chicago': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Chihuahua': 'توقيت المحيط الهادي الرسمي للمكسيك',
  'America/Costa_Rica': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Creston': 'التوقيت الجبلي الرسمي لأمريكا الشمالية',
  'America/Cuiaba': 'توقيت الأمازون الرسمي',
  'America/Curacao': 'التوقيت الرسمي الأطلسي',
  'America/Danmarkshavn': 'توقيت غرينتش',
  'America/Dawson': 'توقيت المحيط الهادي الرسمي',
  'America/Dawson_Creek': 'التوقيت الجبلي الرسمي لأمريكا الشمالية',
  'America/Denver': 'التوقيت الجبلي الرسمي لأمريكا الشمالية',
  'America/Detroit': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Dominica': 'التوقيت الرسمي الأطلسي',
  'America/Edmonton': 'التوقيت الجبلي الرسمي لأمريكا الشمالية',
  'America/Eirunepe': 'غرينتش-٠٥:٠٠',
  'America/El_Salvador': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Fort_Nelson': 'التوقيت الجبلي الرسمي لأمريكا الشمالية',
  'America/Fortaleza': 'توقيت برازيليا الرسمي',
  'America/Glace_Bay': 'التوقيت الرسمي الأطلسي',
  'America/Godthab': 'توقيت غرب غرينلاند الرسمي',
  'America/Goose_Bay': 'التوقيت الرسمي الأطلسي',
  'America/Grand_Turk': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Grenada': 'التوقيت الرسمي الأطلسي',
  'America/Guadeloupe': 'التوقيت الرسمي الأطلسي',
  'America/Guatemala': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Guayaquil': 'توقيت الإكوادور',
  'America/Guyana': 'توقيت غيانا',
  'America/Halifax': 'التوقيت الرسمي الأطلسي',
  'America/Havana': 'توقيت كوبا الرسمي',
  'America/Hermosillo': 'توقيت المحيط الهادي الرسمي للمكسيك',
  'America/Indiana/Indianapolis': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Indiana/Knox': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Indiana/Marengo': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Indiana/Petersburg': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Indiana/Tell_City': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Indiana/Vevay': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Indiana/Vincennes': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Indiana/Winamac': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Inuvik': 'التوقيت الجبلي الرسمي لأمريكا الشمالية',
  'America/Iqaluit': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Jamaica': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Juneau': 'التوقيت الرسمي لألاسكا',
  'America/Kentucky/Louisville': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Kentucky/Monticello': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Kralendijk': 'التوقيت الرسمي الأطلسي',
  'America/La_Paz': 'توقيت بوليفيا',
  'America/Lima': 'توقيت بيرو الرسمي',
  'America/Los_Angeles': 'توقيت المحيط الهادي الرسمي',
  'America/Lower_Princes': 'التوقيت الرسمي الأطلسي',
  'America/Maceio': 'توقيت برازيليا الرسمي',
  'America/Managua': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Manaus': 'توقيت الأمازون الرسمي',
  'America/Marigot': 'التوقيت الرسمي الأطلسي',
  'America/Martinique': 'التوقيت الرسمي الأطلسي',
  'America/Matamoros': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Mazatlan': 'توقيت المحيط الهادي الرسمي للمكسيك',
  'America/Menominee': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Merida': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Metlakatla': 'التوقيت الرسمي لألاسكا',
  'America/Mexico_City': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Miquelon': 'توقيت سانت بيير وميكولون الرسمي',
  'America/Moncton': 'التوقيت الرسمي الأطلسي',
  'America/Monterrey': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Montevideo': 'توقيت أوروغواي الرسمي',
  'America/Montserrat': 'التوقيت الرسمي الأطلسي',
  'America/Nassau': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/New_York': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Nipigon': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Nome': 'التوقيت الرسمي لألاسكا',
  'America/Noronha': 'توقيت فرناندو دي نورونها الرسمي',
  'America/North_Dakota/Beulah': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/North_Dakota/Center': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/North_Dakota/New_Salem': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Ojinaga': 'التوقيت الجبلي الرسمي لأمريكا الشمالية',
  'America/Panama': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Pangnirtung': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Paramaribo': 'توقيت سورينام',
  'America/Phoenix': 'التوقيت الجبلي الرسمي لأمريكا الشمالية',
  'America/Port-au-Prince': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Port_of_Spain': 'التوقيت الرسمي الأطلسي',
  'America/Porto_Velho': 'توقيت الأمازون الرسمي',
  'America/Puerto_Rico': 'التوقيت الرسمي الأطلسي',
  'America/Punta_Arenas': 'غرينتش-٠٣:٠٠',
  'America/Rainy_River': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Rankin_Inlet': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Recife': 'توقيت برازيليا الرسمي',
  'America/Regina': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Resolute': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Rio_Branco': 'غرينتش-٠٥:٠٠',
  'America/Santarem': 'توقيت برازيليا الرسمي',
  'America/Santiago': 'توقيت شيلي الرسمي',
  'America/Santo_Domingo': 'التوقيت الرسمي الأطلسي',
  'America/Sao_Paulo': 'توقيت برازيليا الرسمي',
  'America/Scoresbysund': 'توقيت شرق غرينلاند الرسمي',
  'America/Sitka': 'التوقيت الرسمي لألاسكا',
  'America/St_Barthelemy': 'التوقيت الرسمي الأطلسي',
  'America/St_Johns': 'توقيت نيوفاوندلاند الرسمي',
  'America/St_Kitts': 'التوقيت الرسمي الأطلسي',
  'America/St_Lucia': 'التوقيت الرسمي الأطلسي',
  'America/St_Thomas': 'التوقيت الرسمي الأطلسي',
  'America/St_Vincent': 'التوقيت الرسمي الأطلسي',
  'America/Swift_Current': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Tegucigalpa': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Thule': 'التوقيت الرسمي الأطلسي',
  'America/Thunder_Bay': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Tijuana': 'توقيت المحيط الهادي الرسمي',
  'America/Toronto': 'التوقيت الرسمي الشرقي لأمريكا الشمالية',
  'America/Tortola': 'التوقيت الرسمي الأطلسي',
  'America/Vancouver': 'توقيت المحيط الهادي الرسمي',
  'America/Whitehorse': 'توقيت المحيط الهادي الرسمي',
  'America/Winnipeg': 'التوقيت الرسمي المركزي لأمريكا الشمالية',
  'America/Yakutat': 'التوقيت الرسمي لألاسكا',
  'America/Yellowknife': 'التوقيت الجبلي الرسمي لأمريكا الشمالية',
  'Antarctica/Casey': 'غرينتش+١١:٠٠',
  'Antarctica/Davis': 'توقيت دافيز',
  'Antarctica/DumontDUrville': 'توقيت دي مونت دو روفيل',
  'Antarctica/Macquarie': 'توقيت ماكواري',
  'Antarctica/Mawson': 'توقيت ماوسون',
  'Antarctica/McMurdo': 'توقيت نيوزيلندا الرسمي',
  'Antarctica/Palmer': 'غرينتش-٠٣:٠٠',
  'Antarctica/Rothera': 'توقيت روثيرا',
  'Antarctica/Syowa': 'توقيت سايووا',
  'Antarctica/Troll': 'توقيت غرينتش',
  'Antarctica/Vostok': 'توقيت فوستوك',
  'Arctic/Longyearbyen': 'توقيت وسط أوروبا الرسمي',
  'Asia/Aden': 'التوقيت العربي الرسمي',
  'Asia/Almaty': 'توقيت شرق كازاخستان',
  'Asia/Amman': 'توقيت شرق أوروبا الرسمي',
  'Asia/Anadyr': 'توقيت أنادير الرسمي',
  'Asia/Aqtau': 'توقيت غرب كازاخستان',
  'Asia/Aqtobe': 'توقيت غرب كازاخستان',
  'Asia/Ashgabat': 'توقيت تركمانستان الرسمي',
  'Asia/Atyrau': 'توقيت غرب كازاخستان',
  'Asia/Baghdad': 'التوقيت العربي الرسمي',
  'Asia/Bahrain': 'التوقيت العربي الرسمي',
  'Asia/Baku': 'توقيت أذربيجان الرسمي',
  'Asia/Bangkok': 'توقيت الهند الصينية',
  'Asia/Barnaul': 'غرينتش+٠٧:٠٠',
  'Asia/Beirut': 'توقيت شرق أوروبا الرسمي',
  'Asia/Bishkek': 'توقيت قيرغيزستان',
  'Asia/Brunei': 'توقيت بروناي',
  'Asia/Chita': 'توقيت ياكوتسك الرسمي',
  'Asia/Choibalsan': 'توقيت شويبالسان الرسمي',
  'Asia/Colombo': 'توقيت الهند',
  'Asia/Damascus': 'توقيت شرق أوروبا الرسمي',
  'Asia/Dhaka': 'توقيت بنغلاديش الرسمي',
  'Asia/Dili': 'توقيت تيمور الشرقية',
  'Asia/Dubai': 'توقيت الخليج',
  'Asia/Dushanbe': 'توقيت طاجكستان',
  'Asia/Famagusta': 'غرينتش+٠٢:٠٠',
  'Asia/Gaza': 'توقيت شرق أوروبا الرسمي',
  'Asia/Hebron': 'توقيت شرق أوروبا الرسمي',
  'Asia/Ho_Chi_Minh': 'توقيت الهند الصينية',
  'Asia/Hong_Kong': 'توقيت هونغ كونغ الرسمي',
  'Asia/Hovd': 'توقيت هوفد الرسمي',
  'Asia/Irkutsk': 'توقيت إركوتسك الرسمي',
  'Asia/Jakarta': 'توقيت غرب إندونيسيا',
  'Asia/Jayapura': 'توقيت شرق إندونيسيا',
  'Asia/Jerusalem': 'توقيت إسرائيل الرسمي',
  'Asia/Kabul': 'توقيت أفغانستان',
  'Asia/Kamchatka': 'توقيت بيتروبافلوفسك-كامتشاتسكي',
  'Asia/Karachi': 'توقيت باكستان الرسمي',
  'Asia/Kathmandu': 'توقيت نيبال',
  'Asia/Khandyga': 'توقيت ياكوتسك الرسمي',
  'Asia/Kolkata': 'توقيت الهند',
  'Asia/Krasnoyarsk': 'توقيت كراسنويارسك الرسمي',
  'Asia/Kuala_Lumpur': 'توقيت ماليزيا',
  'Asia/Kuching': 'توقيت ماليزيا',
  'Asia/Kuwait': 'التوقيت العربي الرسمي',
  'Asia/Macau': 'توقيت الصين الرسمي',
  'Asia/Magadan': 'توقيت ماغادان الرسمي',
  'Asia/Makassar': 'توقيت وسط إندونيسيا',
  'Asia/Manila': 'توقيت الفيلبين الرسمي',
  'Asia/Muscat': 'توقيت الخليج',
  'Asia/Nicosia': 'توقيت شرق أوروبا الرسمي',
  'Asia/Novokuznetsk': 'توقيت كراسنويارسك الرسمي',
  'Asia/Novosibirsk': 'توقيت نوفوسيبيرسك الرسمي',
  'Asia/Omsk': 'توقيت أومسك الرسمي',
  'Asia/Oral': 'توقيت غرب كازاخستان',
  'Asia/Phnom_Penh': 'توقيت الهند الصينية',
  'Asia/Pontianak': 'توقيت غرب إندونيسيا',
  'Asia/Pyongyang': 'توقيت بيونغ يانغ',
  'Asia/Qatar': 'التوقيت العربي الرسمي',
  'Asia/Qyzylorda': 'توقيت شرق كازاخستان',
  'Asia/Riyadh': 'التوقيت العربي الرسمي',
  'Asia/Sakhalin': 'توقيت ساخالين الرسمي',
  'Asia/Samarkand': 'توقيت أوزبكستان الرسمي',
  'Asia/Seoul': 'توقيت كوريا الرسمي',
  'Asia/Shanghai': 'توقيت الصين الرسمي',
  'Asia/Singapore': 'توقيت سنغافورة',
  'Asia/Srednekolymsk': 'غرينتش+١١:٠٠',
  'Asia/Taipei': 'توقيت تايبيه الرسمي',
  'Asia/Tashkent': 'توقيت أوزبكستان الرسمي',
  'Asia/Tbilisi': 'توقيت جورجيا الرسمي',
  'Asia/Tehran': 'توقيت إيران الرسمي',
  'Asia/Thimphu': 'توقيت بوتان',
  'Asia/Tokyo': 'توقيت اليابان الرسمي',
  'Asia/Tomsk': 'غرينتش+٠٧:٠٠',
  'Asia/Ulaanbaatar': 'توقيت أولان باتور الرسمي',
  'Asia/Urumqi': 'غرينتش+٠٦:٠٠',
  'Asia/Ust-Nera': 'توقيت فلاديفوستوك الرسمي',
  'Asia/Vientiane': 'توقيت الهند الصينية',
  'Asia/Vladivostok': 'توقيت فلاديفوستوك الرسمي',
  'Asia/Yakutsk': 'توقيت ياكوتسك الرسمي',
  'Asia/Yangon': 'توقيت ميانمار',
  'Asia/Yekaterinburg': 'توقيت يكاترينبورغ الرسمي',
  'Asia/Yerevan': 'توقيت أرمينيا الرسمي',
  'Atlantic/Azores': 'توقيت أزورس الرسمي',
  'Atlantic/Bermuda': 'التوقيت الرسمي الأطلسي',
  'Atlantic/Canary': 'توقيت غرب أوروبا الرسمي',
  'Atlantic/Cape_Verde': 'توقيت الرأس الأخضر الرسمي',
  'Atlantic/Faroe': 'توقيت غرب أوروبا الرسمي',
  'Atlantic/Madeira': 'توقيت غرب أوروبا الرسمي',
  'Atlantic/Reykjavik': 'توقيت غرينتش',
  'Atlantic/South_Georgia': 'توقيت جنوب جورجيا',
  'Atlantic/St_Helena': 'توقيت غرينتش',
  'Atlantic/Stanley': 'توقيت جزر فوكلاند الرسمي',
  'Australia/Adelaide': 'توقيت وسط أستراليا الرسمي',
  'Australia/Brisbane': 'توقيت شرق أستراليا الرسمي',
  'Australia/Broken_Hill': 'توقيت وسط أستراليا الرسمي',
  'Australia/Currie': 'توقيت شرق أستراليا الرسمي',
  'Australia/Darwin': 'توقيت وسط أستراليا الرسمي',
  'Australia/Eucla': 'توقيت غرب وسط أستراليا الرسمي',
  'Australia/Hobart': 'توقيت شرق أستراليا الرسمي',
  'Australia/Lindeman': 'توقيت شرق أستراليا الرسمي',
  'Australia/Lord_Howe': 'توقيت لورد هاو الرسمي',
  'Australia/Melbourne': 'توقيت شرق أستراليا الرسمي',
  'Australia/Perth': 'توقيت غرب أستراليا الرسمي',
  'Australia/Sydney': 'توقيت شرق أستراليا الرسمي',
  'Europe/Amsterdam': 'توقيت وسط أوروبا الرسمي',
  'Europe/Andorra': 'توقيت وسط أوروبا الرسمي',
  'Europe/Astrakhan': 'غرينتش+٠٤:٠٠',
  'Europe/Athens': 'توقيت شرق أوروبا الرسمي',
  'Europe/Belgrade': 'توقيت وسط أوروبا الرسمي',
  'Europe/Berlin': 'توقيت وسط أوروبا الرسمي',
  'Europe/Bratislava': 'توقيت وسط أوروبا الرسمي',
  'Europe/Brussels': 'توقيت وسط أوروبا الرسمي',
  'Europe/Bucharest': 'توقيت شرق أوروبا الرسمي',
  'Europe/Budapest': 'توقيت وسط أوروبا الرسمي',
  'Europe/Busingen': 'توقيت وسط أوروبا الرسمي',
  'Europe/Chisinau': 'توقيت شرق أوروبا الرسمي',
  'Europe/Copenhagen': 'توقيت وسط أوروبا الرسمي',
  'Europe/Dublin': 'توقيت غرينتش',
  'Europe/Gibraltar': 'توقيت وسط أوروبا الرسمي',
  'Europe/Guernsey': 'توقيت غرينتش',
  'Europe/Helsinki': 'توقيت شرق أوروبا الرسمي',
  'Europe/Isle_of_Man': 'توقيت غرينتش',
  'Europe/Istanbul': 'غرينتش+٠٣:٠٠',
  'Europe/Jersey': 'توقيت غرينتش',
  'Europe/Kaliningrad': 'توقيت شرق أوروبا الرسمي',
  'Europe/Kiev': 'توقيت شرق أوروبا الرسمي',
  'Europe/Kirov': 'غرينتش+٠٣:٠٠',
  'Europe/Lisbon': 'توقيت غرب أوروبا الرسمي',
  'Europe/Ljubljana': 'توقيت وسط أوروبا الرسمي',
  'Europe/London': 'توقيت غرينتش',
  'Europe/Luxembourg': 'توقيت وسط أوروبا الرسمي',
  'Europe/Madrid': 'توقيت وسط أوروبا الرسمي',
  'Europe/Malta': 'توقيت وسط أوروبا الرسمي',
  'Europe/Mariehamn': 'توقيت شرق أوروبا الرسمي',
  'Europe/Minsk': 'توقيت موسكو الرسمي',
  'Europe/Monaco': 'توقيت وسط أوروبا الرسمي',
  'Europe/Moscow': 'توقيت موسكو الرسمي',
  'Europe/Oslo': 'توقيت وسط أوروبا الرسمي',
  'Europe/Paris': 'توقيت وسط أوروبا الرسمي',
  'Europe/Podgorica': 'توقيت وسط أوروبا الرسمي',
  'Europe/Prague': 'توقيت وسط أوروبا الرسمي',
  'Europe/Riga': 'توقيت شرق أوروبا الرسمي',
  'Europe/Rome': 'توقيت وسط أوروبا الرسمي',
  'Europe/Samara': 'توقيت سمارا',
  'Europe/San_Marino': 'توقيت وسط أوروبا الرسمي',
  'Europe/Sarajevo': 'توقيت وسط أوروبا الرسمي',
  'Europe/Saratov': 'غرينتش+٠٤:٠٠',
  'Europe/Simferopol': 'توقيت موسكو الرسمي',
  'Europe/Skopje': 'توقيت وسط أوروبا الرسمي',
  'Europe/Sofia': 'توقيت شرق أوروبا الرسمي',
  'Europe/Stockholm': 'توقيت وسط أوروبا الرسمي',
  'Europe/Tallinn': 'توقيت شرق أوروبا الرسمي',
  'Europe/Tirane': 'توقيت وسط أوروبا الرسمي',
  'Europe/Ulyanovsk': 'غرينتش+٠٤:٠٠',
  'Europe/Uzhgorod': 'توقيت شرق أوروبا الرسمي',
  'Europe/Vaduz': 'توقيت وسط أوروبا الرسمي',
  'Europe/Vatican': 'توقيت وسط أوروبا الرسمي',
  'Europe/Vienna': 'توقيت وسط أوروبا الرسمي',
  'Europe/Vilnius': 'توقيت شرق أوروبا الرسمي',
  'Europe/Volgograd': 'توقيت موسكو الرسمي',
  'Europe/Warsaw': 'توقيت وسط أوروبا الرسمي',
  'Europe/Zagreb': 'توقيت وسط أوروبا الرسمي',
  'Europe/Zaporozhye': 'توقيت شرق أوروبا الرسمي',
  'Europe/Zurich': 'توقيت وسط أوروبا الرسمي',
  'Indian/Antananarivo': 'توقيت شرق أفريقيا',
  'Indian/Chagos': 'توقيت المحيط الهندي',
  'Indian/Christmas': 'توقيت جزر الكريسماس',
  'Indian/Cocos': 'توقيت جزر كوكوس',
  'Indian/Comoro': 'توقيت شرق أفريقيا',
  'Indian/Kerguelen': 'توقيت المقاطعات الفرنسية الجنوبية والأنتارتيكية',
  'Indian/Mahe': 'توقيت سيشل',
  'Indian/Maldives': 'توقيت الـمالديف',
  'Indian/Mauritius': 'توقيت موريشيوس الرسمي',
  'Indian/Mayotte': 'توقيت شرق أفريقيا',
  'Indian/Reunion': 'توقيت ريونيون',
  'Pacific/Apia': 'التوقيت الرسمي لآبيا',
  'Pacific/Auckland': 'توقيت نيوزيلندا الرسمي',
  'Pacific/Bougainville': 'غرينتش+١١:٠٠',
  'Pacific/Chatham': 'توقيت تشاتام الرسمي',
  'Pacific/Chuuk': 'توقيت شوك',
  'Pacific/Easter': 'توقيت جزيرة استر الرسمي',
  'Pacific/Efate': 'توقيت فانواتو الرسمي',
  'Pacific/Enderbury': 'توقيت جزر فينكس',
  'Pacific/Fakaofo': 'توقيت توكيلاو',
  'Pacific/Fiji': 'توقيت فيجي الرسمي',
  'Pacific/Funafuti': 'توقيت توفالو',
  'Pacific/Galapagos': 'توقيت غلاباغوس',
  'Pacific/Gambier': 'توقيت جامبير',
  'Pacific/Guadalcanal': 'توقيت جزر سليمان',
  'Pacific/Guam': 'توقيت تشامورو',
  'Pacific/Honolulu': 'توقيت هاواي ألوتيان الرسمي',
  'Pacific/Kiritimati': 'توقيت جزر لاين',
  'Pacific/Kosrae': 'توقيت كوسرا',
  'Pacific/Kwajalein': 'توقيت جزر مارشال',
  'Pacific/Majuro': 'توقيت جزر مارشال',
  'Pacific/Marquesas': 'توقيت ماركيساس',
  'Pacific/Midway': 'توقيت ساموا الرسمي',
  'Pacific/Nauru': 'توقيت ناورو',
  'Pacific/Niue': 'توقيت نيوي',
  'Pacific/Norfolk': 'توقيت جزيرة نورفولك',
  'Pacific/Noumea': 'توقيت كاليدونيا الجديدة الرسمي',
  'Pacific/Pago_Pago': 'توقيت ساموا الرسمي',
  'Pacific/Palau': 'توقيت بالاو',
  'Pacific/Pitcairn': 'توقيت بيتكيرن',
  'Pacific/Pohnpei': 'توقيت بونابي',
  'Pacific/Port_Moresby': 'توقيت بابوا غينيا الجديدة',
  'Pacific/Rarotonga': 'توقيت جزر كووك الرسمي',
  'Pacific/Saipan': 'توقيت تشامورو',
  'Pacific/Tahiti': 'توقيت تاهيتي',
  'Pacific/Tarawa': 'توقيت جزر جيلبرت',
  'Pacific/Tongatapu': 'توقيت تونغا الرسمي',
  'Pacific/Wake': 'توقيت جزيرة ويك',
  'Pacific/Wallis': 'توقيت واليس و فوتونا',
  UTC: 'التوقيت العالمي المنسق',
};
