module.exports = {
  'Africa/Abidjan': 'Qrinviç Orta Vaxtı',
  'Africa/Accra': 'Qrinviç Orta Vaxtı',
  'Africa/Addis_Ababa': 'Şərqi Afrika Vaxtı',
  'Africa/Algiers': 'Mərkəzi Avropa Standart Vaxtı',
  'Africa/Asmara': 'Şərqi Afrika Vaxtı',
  'Africa/Bamako': 'Qrinviç Orta Vaxtı',
  'Africa/Bangui': 'Qərbi Afrika Standart Vaxtı',
  'Africa/Banjul': 'Qrinviç Orta Vaxtı',
  'Africa/Bissau': 'Qrinviç Orta Vaxtı',
  'Africa/Blantyre': 'Mərkəzi Afrika Vaxtı',
  'Africa/Brazzaville': 'Qərbi Afrika Standart Vaxtı',
  'Africa/Bujumbura': 'Mərkəzi Afrika Vaxtı',
  'Africa/Cairo': 'Şərqi Avropa Standart Vaxtı',
  'Africa/Casablanca': 'Qərbi Avropa Standart Vaxtı',
  'Africa/Ceuta': 'Mərkəzi Avropa Standart Vaxtı',
  'Africa/Conakry': 'Qrinviç Orta Vaxtı',
  'Africa/Dakar': 'Qrinviç Orta Vaxtı',
  'Africa/Dar_es_Salaam': 'Şərqi Afrika Vaxtı',
  'Africa/Djibouti': 'Şərqi Afrika Vaxtı',
  'Africa/Douala': 'Qərbi Afrika Standart Vaxtı',
  'Africa/El_Aaiun': 'Qərbi Avropa Standart Vaxtı',
  'Africa/Freetown': 'Qrinviç Orta Vaxtı',
  'Africa/Gaborone': 'Mərkəzi Afrika Vaxtı',
  'Africa/Harare': 'Mərkəzi Afrika Vaxtı',
  'Africa/Johannesburg': 'Cənubi Afrika Vaxtı',
  'Africa/Juba': 'Şərqi Afrika Vaxtı',
  'Africa/Kampala': 'Şərqi Afrika Vaxtı',
  'Africa/Khartoum': 'Mərkəzi Afrika Vaxtı',
  'Africa/Kigali': 'Mərkəzi Afrika Vaxtı',
  'Africa/Kinshasa': 'Qərbi Afrika Standart Vaxtı',
  'Africa/Lagos': 'Qərbi Afrika Standart Vaxtı',
  'Africa/Libreville': 'Qərbi Afrika Standart Vaxtı',
  'Africa/Lome': 'Qrinviç Orta Vaxtı',
  'Africa/Luanda': 'Qərbi Afrika Standart Vaxtı',
  'Africa/Lubumbashi': 'Mərkəzi Afrika Vaxtı',
  'Africa/Lusaka': 'Mərkəzi Afrika Vaxtı',
  'Africa/Malabo': 'Qərbi Afrika Standart Vaxtı',
  'Africa/Maputo': 'Mərkəzi Afrika Vaxtı',
  'Africa/Maseru': 'Cənubi Afrika Vaxtı',
  'Africa/Mbabane': 'Cənubi Afrika Vaxtı',
  'Africa/Mogadishu': 'Şərqi Afrika Vaxtı',
  'Africa/Monrovia': 'Qrinviç Orta Vaxtı',
  'Africa/Nairobi': 'Şərqi Afrika Vaxtı',
  'Africa/Ndjamena': 'Qərbi Afrika Standart Vaxtı',
  'Africa/Niamey': 'Qərbi Afrika Standart Vaxtı',
  'Africa/Nouakchott': 'Qrinviç Orta Vaxtı',
  'Africa/Ouagadougou': 'Qrinviç Orta Vaxtı',
  'Africa/Porto-Novo': 'Qərbi Afrika Standart Vaxtı',
  'Africa/Sao_Tome': 'Qrinviç Orta Vaxtı',
  'Africa/Tripoli': 'Şərqi Avropa Standart Vaxtı',
  'Africa/Tunis': 'Mərkəzi Avropa Standart Vaxtı',
  'Africa/Windhoek': 'Mərkəzi Afrika Vaxtı',
  'America/Adak': 'Havay-Aleut Standart Vaxtı',
  'America/Anchorage': 'Alyaska Standart Vaxtı',
  'America/Anguilla': 'Atlantik Standart Vaxt',
  'America/Antigua': 'Atlantik Standart Vaxt',
  'America/Araguaina': 'Braziliya Standart Vaxtı',
  'America/Argentina/Buenos_Aires': 'Argentina Standart Vaxtı',
  'America/Argentina/Catamarca': 'Argentina Standart Vaxtı',
  'America/Argentina/Cordoba': 'Argentina Standart Vaxtı',
  'America/Argentina/Jujuy': 'Argentina Standart Vaxtı',
  'America/Argentina/La_Rioja': 'Argentina Standart Vaxtı',
  'America/Argentina/Mendoza': 'Argentina Standart Vaxtı',
  'America/Argentina/Rio_Gallegos': 'Argentina Standart Vaxtı',
  'America/Argentina/Salta': 'Argentina Standart Vaxtı',
  'America/Argentina/San_Juan': 'Argentina Standart Vaxtı',
  'America/Argentina/San_Luis': 'Qərbi Argentina Standart Vaxtı',
  'America/Argentina/Tucuman': 'Argentina Standart Vaxtı',
  'America/Argentina/Ushuaia': 'Argentina Standart Vaxtı',
  'America/Aruba': 'Atlantik Standart Vaxt',
  'America/Asuncion': 'Paraqvay Standart Vaxtı',
  'America/Atikokan': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Bahia': 'Braziliya Standart Vaxtı',
  'America/Bahia_Banderas': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Barbados': 'Atlantik Standart Vaxt',
  'America/Belem': 'Braziliya Standart Vaxtı',
  'America/Belize': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Blanc-Sablon': 'Atlantik Standart Vaxt',
  'America/Boa_Vista': 'Amazon Standart Vaxtı',
  'America/Bogota': 'Kolumbiya Standart Vaxtı',
  'America/Boise': 'Şimali Dağlıq Amerika Standart Vaxtı',
  'America/Cambridge_Bay': 'Şimali Dağlıq Amerika Standart Vaxtı',
  'America/Campo_Grande': 'Amazon Standart Vaxtı',
  'America/Cancun': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Caracas': 'Venesuela Vaxtı',
  'America/Cayenne': 'Fransız Qvianası Vaxtı',
  'America/Cayman': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Chicago': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Chihuahua': 'Meksika Sakit Okean Standart Vaxtı',
  'America/Costa_Rica': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Creston': 'Şimali Dağlıq Amerika Standart Vaxtı',
  'America/Cuiaba': 'Amazon Standart Vaxtı',
  'America/Curacao': 'Atlantik Standart Vaxt',
  'America/Danmarkshavn': 'Qrinviç Orta Vaxtı',
  'America/Dawson': 'Şimali Amerika Sakit Okean Standart Vaxtı',
  'America/Dawson_Creek': 'Şimali Dağlıq Amerika Standart Vaxtı',
  'America/Denver': 'Şimali Dağlıq Amerika Standart Vaxtı',
  'America/Detroit': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Dominica': 'Atlantik Standart Vaxt',
  'America/Edmonton': 'Şimali Dağlıq Amerika Standart Vaxtı',
  'America/Eirunepe': 'GMT-05:00',
  'America/El_Salvador': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Fort_Nelson': 'Şimali Dağlıq Amerika Standart Vaxtı',
  'America/Fortaleza': 'Braziliya Standart Vaxtı',
  'America/Glace_Bay': 'Atlantik Standart Vaxt',
  'America/Godthab': 'Qərbi Qrenlandiya Standart Vaxtı',
  'America/Goose_Bay': 'Atlantik Standart Vaxt',
  'America/Grand_Turk': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Grenada': 'Atlantik Standart Vaxt',
  'America/Guadeloupe': 'Atlantik Standart Vaxt',
  'America/Guatemala': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Guayaquil': 'Ekvador Vaxtı',
  'America/Guyana': 'Qayana Vaxtı',
  'America/Halifax': 'Atlantik Standart Vaxt',
  'America/Havana': 'Kuba Standart Vaxtı',
  'America/Hermosillo': 'Meksika Sakit Okean Standart Vaxtı',
  'America/Indiana/Indianapolis': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Indiana/Knox': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Indiana/Marengo': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Indiana/Petersburg': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Indiana/Tell_City': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Indiana/Vevay': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Indiana/Vincennes': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Indiana/Winamac': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Inuvik': 'Şimali Dağlıq Amerika Standart Vaxtı',
  'America/Iqaluit': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Jamaica': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Juneau': 'Alyaska Standart Vaxtı',
  'America/Kentucky/Louisville': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Kentucky/Monticello': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Kralendijk': 'Atlantik Standart Vaxt',
  'America/La_Paz': 'Boliviya Vaxtı',
  'America/Lima': 'Peru Standart Vaxtı',
  'America/Los_Angeles': 'Şimali Amerika Sakit Okean Standart Vaxtı',
  'America/Lower_Princes': 'Atlantik Standart Vaxt',
  'America/Maceio': 'Braziliya Standart Vaxtı',
  'America/Managua': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Manaus': 'Amazon Standart Vaxtı',
  'America/Marigot': 'Atlantik Standart Vaxt',
  'America/Martinique': 'Atlantik Standart Vaxt',
  'America/Matamoros': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Mazatlan': 'Meksika Sakit Okean Standart Vaxtı',
  'America/Menominee': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Merida': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Metlakatla': 'Alyaska Standart Vaxtı',
  'America/Mexico_City': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Miquelon': 'Müqəddəs Pyer və Mikelon Standart Vaxtı',
  'America/Moncton': 'Atlantik Standart Vaxt',
  'America/Monterrey': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Montevideo': 'Uruqvay Standart Vaxtı',
  'America/Montserrat': 'Atlantik Standart Vaxt',
  'America/Nassau': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/New_York': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Nipigon': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Nome': 'Alyaska Standart Vaxtı',
  'America/Noronha': 'Fernando de Noronya Standart Vaxtı',
  'America/North_Dakota/Beulah': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/North_Dakota/Center': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/North_Dakota/New_Salem': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Ojinaga': 'Şimali Dağlıq Amerika Standart Vaxtı',
  'America/Panama': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Pangnirtung': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Paramaribo': 'Surinam Vaxtı',
  'America/Phoenix': 'Şimali Dağlıq Amerika Standart Vaxtı',
  'America/Port-au-Prince': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Port_of_Spain': 'Atlantik Standart Vaxt',
  'America/Porto_Velho': 'Amazon Standart Vaxtı',
  'America/Puerto_Rico': 'Atlantik Standart Vaxt',
  'America/Punta_Arenas': 'GMT-03:00',
  'America/Rainy_River': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Rankin_Inlet': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Recife': 'Braziliya Standart Vaxtı',
  'America/Regina': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Resolute': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Rio_Branco': 'GMT-05:00',
  'America/Santarem': 'Braziliya Standart Vaxtı',
  'America/Santiago': 'Çili Standart Vaxtı',
  'America/Santo_Domingo': 'Atlantik Standart Vaxt',
  'America/Sao_Paulo': 'Braziliya Standart Vaxtı',
  'America/Scoresbysund': 'Şərqi Qrenlandiya Standart Vaxtı',
  'America/Sitka': 'Alyaska Standart Vaxtı',
  'America/St_Barthelemy': 'Atlantik Standart Vaxt',
  'America/St_Johns': 'Nyufaundlend Standart Vaxtı',
  'America/St_Kitts': 'Atlantik Standart Vaxt',
  'America/St_Lucia': 'Atlantik Standart Vaxt',
  'America/St_Thomas': 'Atlantik Standart Vaxt',
  'America/St_Vincent': 'Atlantik Standart Vaxt',
  'America/Swift_Current': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Tegucigalpa': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Thule': 'Atlantik Standart Vaxt',
  'America/Thunder_Bay': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Tijuana': 'Şimali Amerika Sakit Okean Standart Vaxtı',
  'America/Toronto': 'Şimali Şərqi Amerika Standart Vaxtı',
  'America/Tortola': 'Atlantik Standart Vaxt',
  'America/Vancouver': 'Şimali Amerika Sakit Okean Standart Vaxtı',
  'America/Whitehorse': 'Şimali Amerika Sakit Okean Standart Vaxtı',
  'America/Winnipeg': 'Şimali Mərkəzi Amerika Standart Vaxtı',
  'America/Yakutat': 'Alyaska Standart Vaxtı',
  'America/Yellowknife': 'Şimali Dağlıq Amerika Standart Vaxtı',
  'Antarctica/Casey': 'GMT+11:00',
  'Antarctica/Davis': 'Devis Vaxtı',
  'Antarctica/DumontDUrville': 'Dümon-d’Ürvil Vaxtı',
  'Antarctica/Macquarie': 'Makari Adası Vaxtı',
  'Antarctica/Mawson': 'Mouson Vaxtı',
  'Antarctica/McMurdo': 'Yeni Zelandiya Standart Vaxtı',
  'Antarctica/Palmer': 'GMT-03:00',
  'Antarctica/Rothera': 'Rotera Vaxtı',
  'Antarctica/Syowa': 'Syova Vaxtı',
  'Antarctica/Troll': 'Qrinviç Orta Vaxtı',
  'Antarctica/Vostok': 'Vostok Vaxtı',
  'Arctic/Longyearbyen': 'Mərkəzi Avropa Standart Vaxtı',
  'Asia/Aden': 'Ərəbistan Standart Vaxtı',
  'Asia/Almaty': 'Şərqi Qazaxıstan Vaxtı',
  'Asia/Amman': 'Şərqi Avropa Standart Vaxtı',
  'Asia/Anadyr': 'GMT+12:00',
  'Asia/Aqtau': 'Qərbi Qazaxıstan Vaxtı',
  'Asia/Aqtobe': 'Qərbi Qazaxıstan Vaxtı',
  'Asia/Ashgabat': 'Türkmənistan Standart Vaxtı',
  'Asia/Atyrau': 'Qərbi Qazaxıstan Vaxtı',
  'Asia/Baghdad': 'Ərəbistan Standart Vaxtı',
  'Asia/Bahrain': 'Ərəbistan Standart Vaxtı',
  'Asia/Baku': 'Azərbaycan Standart Vaxtı',
  'Asia/Bangkok': 'Hindçin Vaxtı',
  'Asia/Barnaul': 'GMT+07:00',
  'Asia/Beirut': 'Şərqi Avropa Standart Vaxtı',
  'Asia/Bishkek': 'Qırğızıstan Vaxtı',
  'Asia/Brunei': 'Brunei Darussalam vaxtı',
  'Asia/Chita': 'Yakutsk Standart Vaxtı',
  'Asia/Choibalsan': 'Çoybalsan Standart Vaxtı',
  'Asia/Colombo': 'Hindistan Vaxtı',
  'Asia/Damascus': 'Şərqi Avropa Standart Vaxtı',
  'Asia/Dhaka': 'Banqladeş Standart Vaxtı',
  'Asia/Dili': 'Şərqi Timor Vaxtı',
  'Asia/Dubai': 'Körfəz Vaxtı',
  'Asia/Dushanbe': 'Tacikistan Vaxtı',
  'Asia/Famagusta': 'GMT+02:00',
  'Asia/Gaza': 'Şərqi Avropa Standart Vaxtı',
  'Asia/Hebron': 'Şərqi Avropa Standart Vaxtı',
  'Asia/Ho_Chi_Minh': 'Hindçin Vaxtı',
  'Asia/Hong_Kong': 'Honq Konq Standart Vaxtı',
  'Asia/Hovd': 'Hovd Standart Vaxtı',
  'Asia/Irkutsk': 'İrkutsk Standart Vaxtı',
  'Asia/Jakarta': 'Qərbi İndoneziya Vaxtı',
  'Asia/Jayapura': 'Şərqi İndoneziya Vaxtı',
  'Asia/Jerusalem': 'İsrail Standart Vaxtı',
  'Asia/Kabul': 'Əfqanıstan Vaxtı',
  'Asia/Kamchatka': 'GMT+12:00',
  'Asia/Karachi': 'Pakistan Standart vaxtı',
  'Asia/Kathmandu': 'Nepal vaxtı',
  'Asia/Khandyga': 'Yakutsk Standart Vaxtı',
  'Asia/Kolkata': 'Hindistan Vaxtı',
  'Asia/Krasnoyarsk': 'Krasnoyarsk Standart Vaxtı',
  'Asia/Kuala_Lumpur': 'Malayziya Vaxtı',
  'Asia/Kuching': 'Malayziya Vaxtı',
  'Asia/Kuwait': 'Ərəbistan Standart Vaxtı',
  'Asia/Macau': 'Çin Standart Vaxtı',
  'Asia/Magadan': 'Maqadan Standart Vaxtı',
  'Asia/Makassar': 'Mərkəzi İndoneziya Vaxtı',
  'Asia/Manila': 'Filippin Standart Vaxtı',
  'Asia/Muscat': 'Körfəz Vaxtı',
  'Asia/Nicosia': 'Şərqi Avropa Standart Vaxtı',
  'Asia/Novokuznetsk': 'Krasnoyarsk Standart Vaxtı',
  'Asia/Novosibirsk': 'Novosibirsk Standart Vaxtı',
  'Asia/Omsk': 'Omsk Standart Vaxtı',
  'Asia/Oral': 'Qərbi Qazaxıstan Vaxtı',
  'Asia/Phnom_Penh': 'Hindçin Vaxtı',
  'Asia/Pontianak': 'Qərbi İndoneziya Vaxtı',
  'Asia/Pyongyang': 'Pxenyan Vaxtı',
  'Asia/Qatar': 'Ərəbistan Standart Vaxtı',
  'Asia/Qyzylorda': 'Şərqi Qazaxıstan Vaxtı',
  'Asia/Riyadh': 'Ərəbistan Standart Vaxtı',
  'Asia/Sakhalin': 'Saxalin Standart Vaxtı',
  'Asia/Samarkand': 'Özbəkistan Standart Vaxtı',
  'Asia/Seoul': 'Koreya Standart Vaxtı',
  'Asia/Shanghai': 'Çin Standart Vaxtı',
  'Asia/Singapore': 'Sinqapur Vaxtı',
  'Asia/Srednekolymsk': 'GMT+11:00',
  'Asia/Taipei': 'Taybey Standart Vaxtı',
  'Asia/Tashkent': 'Özbəkistan Standart Vaxtı',
  'Asia/Tbilisi': 'Gurcüstan Standart Vaxtı',
  'Asia/Tehran': 'İran Standart Vaxtı',
  'Asia/Thimphu': 'Butan Vaxtı',
  'Asia/Tokyo': 'Yaponiya Standart Vaxtı',
  'Asia/Tomsk': 'GMT+07:00',
  'Asia/Ulaanbaatar': 'Ulanbator Standart Vaxtı',
  'Asia/Urumqi': 'GMT+06:00',
  'Asia/Ust-Nera': 'Vladivostok Standart Vaxtı',
  'Asia/Vientiane': 'Hindçin Vaxtı',
  'Asia/Vladivostok': 'Vladivostok Standart Vaxtı',
  'Asia/Yakutsk': 'Yakutsk Standart Vaxtı',
  'Asia/Yangon': 'Myanma Vaxtı',
  'Asia/Yekaterinburg': 'Yekaterinburq Standart Vaxtı',
  'Asia/Yerevan': 'Ermənistan Standart Vaxtı',
  'Atlantic/Azores': 'Azor Standart Vaxtı',
  'Atlantic/Bermuda': 'Atlantik Standart Vaxt',
  'Atlantic/Canary': 'Qərbi Avropa Standart Vaxtı',
  'Atlantic/Cape_Verde': 'Kape Verde Standart Vaxtı',
  'Atlantic/Faroe': 'Qərbi Avropa Standart Vaxtı',
  'Atlantic/Madeira': 'Qərbi Avropa Standart Vaxtı',
  'Atlantic/Reykjavik': 'Qrinviç Orta Vaxtı',
  'Atlantic/South_Georgia': 'Cənubi Corciya Vaxtı',
  'Atlantic/St_Helena': 'Qrinviç Orta Vaxtı',
  'Atlantic/Stanley': 'Folklend Adaları Standart Vaxtı',
  'Australia/Adelaide': 'Mərkəzi Avstraliya Standart Vaxtı',
  'Australia/Brisbane': 'Şərqi Avstraliya Standart Vaxtı',
  'Australia/Broken_Hill': 'Mərkəzi Avstraliya Standart Vaxtı',
  'Australia/Currie': 'Şərqi Avstraliya Standart Vaxtı',
  'Australia/Darwin': 'Mərkəzi Avstraliya Standart Vaxtı',
  'Australia/Eucla': 'Mərkəzi Qərbi Avstraliya Standart Vaxtı',
  'Australia/Hobart': 'Şərqi Avstraliya Standart Vaxtı',
  'Australia/Lindeman': 'Şərqi Avstraliya Standart Vaxtı',
  'Australia/Lord_Howe': 'Lord Hau Standart Vaxtı',
  'Australia/Melbourne': 'Şərqi Avstraliya Standart Vaxtı',
  'Australia/Perth': 'Qərbi Avstraliya Standart Vaxtı',
  'Australia/Sydney': 'Şərqi Avstraliya Standart Vaxtı',
  'Europe/Amsterdam': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Andorra': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Astrakhan': 'GMT+04:00',
  'Europe/Athens': 'Şərqi Avropa Standart Vaxtı',
  'Europe/Belgrade': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Berlin': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Bratislava': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Brussels': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Bucharest': 'Şərqi Avropa Standart Vaxtı',
  'Europe/Budapest': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Busingen': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Chisinau': 'Şərqi Avropa Standart Vaxtı',
  'Europe/Copenhagen': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Dublin': 'Qrinviç Orta Vaxtı',
  'Europe/Gibraltar': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Guernsey': 'Qrinviç Orta Vaxtı',
  'Europe/Helsinki': 'Şərqi Avropa Standart Vaxtı',
  'Europe/Isle_of_Man': 'Qrinviç Orta Vaxtı',
  'Europe/Istanbul': 'GMT+03:00',
  'Europe/Jersey': 'Qrinviç Orta Vaxtı',
  'Europe/Kaliningrad': 'Şərqi Avropa Standart Vaxtı',
  'Europe/Kiev': 'Şərqi Avropa Standart Vaxtı',
  'Europe/Kirov': 'GMT+03:00',
  'Europe/Lisbon': 'Qərbi Avropa Standart Vaxtı',
  'Europe/Ljubljana': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/London': 'Qrinviç Orta Vaxtı',
  'Europe/Luxembourg': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Madrid': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Malta': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Mariehamn': 'Şərqi Avropa Standart Vaxtı',
  'Europe/Minsk': 'Moskva Standart Vaxtı',
  'Europe/Monaco': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Moscow': 'Moskva Standart Vaxtı',
  'Europe/Oslo': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Paris': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Podgorica': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Prague': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Riga': 'Şərqi Avropa Standart Vaxtı',
  'Europe/Rome': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Samara': 'Samara standart vaxtı',
  'Europe/San_Marino': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Sarajevo': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Saratov': 'GMT+04:00',
  'Europe/Simferopol': 'Moskva Standart Vaxtı',
  'Europe/Skopje': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Sofia': 'Şərqi Avropa Standart Vaxtı',
  'Europe/Stockholm': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Tallinn': 'Şərqi Avropa Standart Vaxtı',
  'Europe/Tirane': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Ulyanovsk': 'GMT+04:00',
  'Europe/Uzhgorod': 'Şərqi Avropa Standart Vaxtı',
  'Europe/Vaduz': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Vatican': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Vienna': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Vilnius': 'Şərqi Avropa Standart Vaxtı',
  'Europe/Volgograd': 'Moskva Standart Vaxtı',
  'Europe/Warsaw': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Zagreb': 'Mərkəzi Avropa Standart Vaxtı',
  'Europe/Zaporozhye': 'Şərqi Avropa Standart Vaxtı',
  'Europe/Zurich': 'Mərkəzi Avropa Standart Vaxtı',
  'Indian/Antananarivo': 'Şərqi Afrika Vaxtı',
  'Indian/Chagos': 'Hind Okeanı Vaxtı',
  'Indian/Christmas': 'Milad Adası Vaxtı',
  'Indian/Cocos': 'Kokos Adaları Vaxtı',
  'Indian/Comoro': 'Şərqi Afrika Vaxtı',
  'Indian/Kerguelen': 'Fransız Cənubi və Antarktik Vaxtı',
  'Indian/Mahe': 'Seyşel Adaları Vaxtı',
  'Indian/Maldives': 'Maldiv Vaxtı',
  'Indian/Mauritius': 'Mavriki Standart Vaxtı',
  'Indian/Mayotte': 'Şərqi Afrika Vaxtı',
  'Indian/Reunion': 'Reunion Vaxtı',
  'Pacific/Apia': 'Apia Standart Vaxtı',
  'Pacific/Auckland': 'Yeni Zelandiya Standart Vaxtı',
  'Pacific/Bougainville': 'GMT+11:00',
  'Pacific/Chatham': 'Çatham Standart Vaxtı',
  'Pacific/Chuuk': 'Çuuk Vaxtı',
  'Pacific/Easter': 'Pasxa Adası Standart Vaxtı',
  'Pacific/Efate': 'Vanuatu Standart Vaxtı',
  'Pacific/Enderbury': 'Feniks Adaları Vaxtı',
  'Pacific/Fakaofo': 'Tokelau Vaxtı',
  'Pacific/Fiji': 'Fici Standart Vaxtı',
  'Pacific/Funafuti': 'Tuvalu Vaxtı',
  'Pacific/Galapagos': 'Qalapaqos Vaxtı',
  'Pacific/Gambier': 'Qambier Vaxtı',
  'Pacific/Guadalcanal': 'Solomon Adaları Vaxtı',
  'Pacific/Guam': 'Çamorro Vaxtı',
  'Pacific/Honolulu': 'Havay-Aleut Standart Vaxtı',
  'Pacific/Kiritimati': 'Layn Adaları Vaxtı',
  'Pacific/Kosrae': 'Korse Vaxtı',
  'Pacific/Kwajalein': 'Marşal Adaları Vaxtı',
  'Pacific/Majuro': 'Marşal Adaları Vaxtı',
  'Pacific/Marquesas': 'Markesas Vaxtı',
  'Pacific/Midway': 'Samoa Standart Vaxtı',
  'Pacific/Nauru': 'Nauru Vaxtı',
  'Pacific/Niue': 'Niue Vaxtı',
  'Pacific/Norfolk': 'Norfolk Adası Vaxtı',
  'Pacific/Noumea': 'Yeni Kaledoniya Standart Vaxtı',
  'Pacific/Pago_Pago': 'Samoa Standart Vaxtı',
  'Pacific/Palau': 'Palau Vaxtı',
  'Pacific/Pitcairn': 'Pitkern Vaxtı',
  'Pacific/Pohnpei': 'Ponape Vaxtı',
  'Pacific/Port_Moresby': 'Papua Yeni Qvineya Vaxtı',
  'Pacific/Rarotonga': 'Kuk Adaları Standart Vaxtı',
  'Pacific/Saipan': 'Çamorro Vaxtı',
  'Pacific/Tahiti': 'Tahiti Vaxtı',
  'Pacific/Tarawa': 'Gilbert Adaları Vaxtı',
  'Pacific/Tongatapu': 'Tonqa Standart Vaxtı',
  'Pacific/Wake': 'Ueyk Vaxtı',
  'Pacific/Wallis': 'Uollis və Futuna Vaxtı',
  UTC: 'Koordinasiya edilmiş ümumdünya vaxtı',
};
