module.exports = {
  'Africa/Abidjan': 'Greenwich Mean Time',
  'Africa/Accra': 'Greenwich Mean Time',
  'Africa/Addis_Ababa': 'East Africa Time',
  'Africa/Algiers': 'Central European Standard Time',
  'Africa/Asmara': 'East Africa Time',
  'Africa/Bamako': 'Greenwich Mean Time',
  'Africa/Bangui': 'West Africa Standard Time',
  'Africa/Banjul': 'Greenwich Mean Time',
  'Africa/Bissau': 'Greenwich Mean Time',
  'Africa/Blantyre': 'Central Africa Time',
  'Africa/Brazzaville': 'West Africa Standard Time',
  'Africa/Bujumbura': 'Central Africa Time',
  'Africa/Cairo': 'Eastern European Standard Time',
  'Africa/Casablanca': 'Western European Standard Time',
  'Africa/Ceuta': 'Central European Standard Time',
  'Africa/Conakry': 'Greenwich Mean Time',
  'Africa/Dakar': 'Greenwich Mean Time',
  'Africa/Dar_es_Salaam': 'East Africa Time',
  'Africa/Djibouti': 'East Africa Time',
  'Africa/Douala': 'West Africa Standard Time',
  'Africa/El_Aaiun': 'Western European Standard Time',
  'Africa/Freetown': 'Greenwich Mean Time',
  'Africa/Gaborone': 'Central Africa Time',
  'Africa/Harare': 'Central Africa Time',
  'Africa/Johannesburg': 'South Africa Standard Time',
  'Africa/Juba': 'East Africa Time',
  'Africa/Kampala': 'East Africa Time',
  'Africa/Khartoum': 'Central Africa Time',
  'Africa/Kigali': 'Central Africa Time',
  'Africa/Kinshasa': 'West Africa Standard Time',
  'Africa/Lagos': 'West Africa Standard Time',
  'Africa/Libreville': 'West Africa Standard Time',
  'Africa/Lome': 'Greenwich Mean Time',
  'Africa/Luanda': 'West Africa Standard Time',
  'Africa/Lubumbashi': 'Central Africa Time',
  'Africa/Lusaka': 'Central Africa Time',
  'Africa/Malabo': 'West Africa Standard Time',
  'Africa/Maputo': 'Central Africa Time',
  'Africa/Maseru': 'South Africa Standard Time',
  'Africa/Mbabane': 'South Africa Standard Time',
  'Africa/Mogadishu': 'East Africa Time',
  'Africa/Monrovia': 'Greenwich Mean Time',
  'Africa/Nairobi': 'East Africa Time',
  'Africa/Ndjamena': 'West Africa Standard Time',
  'Africa/Niamey': 'West Africa Standard Time',
  'Africa/Nouakchott': 'Greenwich Mean Time',
  'Africa/Ouagadougou': 'Greenwich Mean Time',
  'Africa/Porto-Novo': 'West Africa Standard Time',
  'Africa/Sao_Tome': 'Greenwich Mean Time',
  'Africa/Tripoli': 'Eastern European Standard Time',
  'Africa/Tunis': 'Central European Standard Time',
  'Africa/Windhoek': 'Central Africa Time',
  'America/Adak': 'Hawaii-Aleutian Standard Time',
  'America/Anchorage': 'Alaska Standard Time',
  'America/Anguilla': 'Atlantic Standard Time',
  'America/Antigua': 'Atlantic Standard Time',
  'America/Araguaina': 'Brasilia Standard Time',
  'America/Argentina/Buenos_Aires': 'Argentina Standard Time',
  'America/Argentina/Catamarca': 'Argentina Standard Time',
  'America/Argentina/Cordoba': 'Argentina Standard Time',
  'America/Argentina/Jujuy': 'Argentina Standard Time',
  'America/Argentina/La_Rioja': 'Argentina Standard Time',
  'America/Argentina/Mendoza': 'Argentina Standard Time',
  'America/Argentina/Rio_Gallegos': 'Argentina Standard Time',
  'America/Argentina/Salta': 'Argentina Standard Time',
  'America/Argentina/San_Juan': 'Argentina Standard Time',
  'America/Argentina/San_Luis': 'Western Argentina Standard Time',
  'America/Argentina/Tucuman': 'Argentina Standard Time',
  'America/Argentina/Ushuaia': 'Argentina Standard Time',
  'America/Aruba': 'Atlantic Standard Time',
  'America/Asuncion': 'Paraguay Standard Time',
  'America/Atikokan': 'Eastern Standard Time',
  'America/Bahia': 'Brasilia Standard Time',
  'America/Bahia_Banderas': 'Central Standard Time',
  'America/Barbados': 'Atlantic Standard Time',
  'America/Belem': 'Brasilia Standard Time',
  'America/Belize': 'Central Standard Time',
  'America/Blanc-Sablon': 'Atlantic Standard Time',
  'America/Boa_Vista': 'Amazon Standard Time',
  'America/Bogota': 'Colombia Standard Time',
  'America/Boise': 'Mountain Standard Time',
  'America/Cambridge_Bay': 'Mountain Standard Time',
  'America/Campo_Grande': 'Amazon Standard Time',
  'America/Cancun': 'Eastern Standard Time',
  'America/Caracas': 'Venezuela Time',
  'America/Cayenne': 'French Guiana Time',
  'America/Cayman': 'Eastern Standard Time',
  'America/Chicago': 'Central Standard Time',
  'America/Chihuahua': 'Mexican Pacific Standard Time',
  'America/Costa_Rica': 'Central Standard Time',
  'America/Creston': 'Mountain Standard Time',
  'America/Cuiaba': 'Amazon Standard Time',
  'America/Curacao': 'Atlantic Standard Time',
  'America/Danmarkshavn': 'Greenwich Mean Time',
  'America/Dawson': 'Pacific Standard Time',
  'America/Dawson_Creek': 'Mountain Standard Time',
  'America/Denver': 'Mountain Standard Time',
  'America/Detroit': 'Eastern Standard Time',
  'America/Dominica': 'Atlantic Standard Time',
  'America/Edmonton': 'Mountain Standard Time',
  'America/Eirunepe': 'Acre Standard Time',
  'America/El_Salvador': 'Central Standard Time',
  'America/Fort_Nelson': 'Mountain Standard Time',
  'America/Fortaleza': 'Brasilia Standard Time',
  'America/Glace_Bay': 'Atlantic Standard Time',
  'America/Godthab': 'West Greenland Standard Time',
  'America/Goose_Bay': 'Atlantic Standard Time',
  'America/Grand_Turk': 'Eastern Standard Time',
  'America/Grenada': 'Atlantic Standard Time',
  'America/Guadeloupe': 'Atlantic Standard Time',
  'America/Guatemala': 'Central Standard Time',
  'America/Guayaquil': 'Ecuador Time',
  'America/Guyana': 'Guyana Time',
  'America/Halifax': 'Atlantic Standard Time',
  'America/Havana': 'Cuba Standard Time',
  'America/Hermosillo': 'Mexican Pacific Standard Time',
  'America/Indiana/Indianapolis': 'Eastern Standard Time',
  'America/Indiana/Knox': 'Central Standard Time',
  'America/Indiana/Marengo': 'Eastern Standard Time',
  'America/Indiana/Petersburg': 'Eastern Standard Time',
  'America/Indiana/Tell_City': 'Central Standard Time',
  'America/Indiana/Vevay': 'Eastern Standard Time',
  'America/Indiana/Vincennes': 'Eastern Standard Time',
  'America/Indiana/Winamac': 'Eastern Standard Time',
  'America/Inuvik': 'Mountain Standard Time',
  'America/Iqaluit': 'Eastern Standard Time',
  'America/Jamaica': 'Eastern Standard Time',
  'America/Juneau': 'Alaska Standard Time',
  'America/Kentucky/Louisville': 'Eastern Standard Time',
  'America/Kentucky/Monticello': 'Eastern Standard Time',
  'America/Kralendijk': 'Atlantic Standard Time',
  'America/La_Paz': 'Bolivia Time',
  'America/Lima': 'Peru Standard Time',
  'America/Los_Angeles': 'Pacific Standard Time',
  'America/Lower_Princes': 'Atlantic Standard Time',
  'America/Maceio': 'Brasilia Standard Time',
  'America/Managua': 'Central Standard Time',
  'America/Manaus': 'Amazon Standard Time',
  'America/Marigot': 'Atlantic Standard Time',
  'America/Martinique': 'Atlantic Standard Time',
  'America/Matamoros': 'Central Standard Time',
  'America/Mazatlan': 'Mexican Pacific Standard Time',
  'America/Menominee': 'Central Standard Time',
  'America/Merida': 'Central Standard Time',
  'America/Metlakatla': 'Alaska Standard Time',
  'America/Mexico_City': 'Central Standard Time',
  'America/Miquelon': 'St. Pierre & Miquelon Standard Time',
  'America/Moncton': 'Atlantic Standard Time',
  'America/Monterrey': 'Central Standard Time',
  'America/Montevideo': 'Uruguay Standard Time',
  'America/Montserrat': 'Atlantic Standard Time',
  'America/Nassau': 'Eastern Standard Time',
  'America/New_York': 'Eastern Standard Time',
  'America/Nipigon': 'Eastern Standard Time',
  'America/Nome': 'Alaska Standard Time',
  'America/Noronha': 'Fernando de Noronha Standard Time',
  'America/North_Dakota/Beulah': 'Central Standard Time',
  'America/North_Dakota/Center': 'Central Standard Time',
  'America/North_Dakota/New_Salem': 'Central Standard Time',
  'America/Ojinaga': 'Mountain Standard Time',
  'America/Panama': 'Eastern Standard Time',
  'America/Pangnirtung': 'Eastern Standard Time',
  'America/Paramaribo': 'Suriname Time',
  'America/Phoenix': 'Mountain Standard Time',
  'America/Port-au-Prince': 'Eastern Standard Time',
  'America/Port_of_Spain': 'Atlantic Standard Time',
  'America/Porto_Velho': 'Amazon Standard Time',
  'America/Puerto_Rico': 'Atlantic Standard Time',
  'America/Punta_Arenas': 'GMT-03:00',
  'America/Rainy_River': 'Central Standard Time',
  'America/Rankin_Inlet': 'Central Standard Time',
  'America/Recife': 'Brasilia Standard Time',
  'America/Regina': 'Central Standard Time',
  'America/Resolute': 'Central Standard Time',
  'America/Rio_Branco': 'Acre Standard Time',
  'America/Santarem': 'Brasilia Standard Time',
  'America/Santiago': 'Chile Standard Time',
  'America/Santo_Domingo': 'Atlantic Standard Time',
  'America/Sao_Paulo': 'Brasilia Standard Time',
  'America/Scoresbysund': 'East Greenland Standard Time',
  'America/Sitka': 'Alaska Standard Time',
  'America/St_Barthelemy': 'Atlantic Standard Time',
  'America/St_Johns': 'Newfoundland Standard Time',
  'America/St_Kitts': 'Atlantic Standard Time',
  'America/St_Lucia': 'Atlantic Standard Time',
  'America/St_Thomas': 'Atlantic Standard Time',
  'America/St_Vincent': 'Atlantic Standard Time',
  'America/Swift_Current': 'Central Standard Time',
  'America/Tegucigalpa': 'Central Standard Time',
  'America/Thule': 'Atlantic Standard Time',
  'America/Thunder_Bay': 'Eastern Standard Time',
  'America/Tijuana': 'Pacific Standard Time',
  'America/Toronto': 'Eastern Standard Time',
  'America/Tortola': 'Atlantic Standard Time',
  'America/Vancouver': 'Pacific Standard Time',
  'America/Whitehorse': 'Pacific Standard Time',
  'America/Winnipeg': 'Central Standard Time',
  'America/Yakutat': 'Alaska Standard Time',
  'America/Yellowknife': 'Mountain Standard Time',
  'Antarctica/Casey': 'Casey Time',
  'Antarctica/Davis': 'Davis Time',
  'Antarctica/DumontDUrville': 'Dumont-d’Urville Time',
  'Antarctica/Macquarie': 'Macquarie Island Time',
  'Antarctica/Mawson': 'Mawson Time',
  'Antarctica/McMurdo': 'New Zealand Standard Time',
  'Antarctica/Palmer': 'GMT-03:00',
  'Antarctica/Rothera': 'Rothera Time',
  'Antarctica/Syowa': 'Syowa Time',
  'Antarctica/Troll': 'Greenwich Mean Time',
  'Antarctica/Vostok': 'Vostok Time',
  'Arctic/Longyearbyen': 'Central European Standard Time',
  'Asia/Aden': 'Arabian Standard Time',
  'Asia/Almaty': 'East Kazakhstan Time',
  'Asia/Amman': 'Eastern European Standard Time',
  'Asia/Anadyr': 'Anadyr Standard Time',
  'Asia/Aqtau': 'West Kazakhstan Time',
  'Asia/Aqtobe': 'West Kazakhstan Time',
  'Asia/Ashgabat': 'Turkmenistan Standard Time',
  'Asia/Atyrau': 'West Kazakhstan Time',
  'Asia/Baghdad': 'Arabian Standard Time',
  'Asia/Bahrain': 'Arabian Standard Time',
  'Asia/Baku': 'Azerbaijan Standard Time',
  'Asia/Bangkok': 'Indochina Time',
  'Asia/Barnaul': 'GMT+07:00',
  'Asia/Beirut': 'Eastern European Standard Time',
  'Asia/Bishkek': 'Kyrgyzstan Time',
  'Asia/Brunei': 'Brunei Darussalam Time',
  'Asia/Chita': 'Yakutsk Standard Time',
  'Asia/Choibalsan': 'Choibalsan Standard Time',
  'Asia/Colombo': 'India Standard Time',
  'Asia/Damascus': 'Eastern European Standard Time',
  'Asia/Dhaka': 'Bangladesh Standard Time',
  'Asia/Dili': 'East Timor Time',
  'Asia/Dubai': 'Gulf Standard Time',
  'Asia/Dushanbe': 'Tajikistan Time',
  'Asia/Famagusta': 'GMT+02:00',
  'Asia/Gaza': 'Eastern European Standard Time',
  'Asia/Hebron': 'Eastern European Standard Time',
  'Asia/Ho_Chi_Minh': 'Indochina Time',
  'Asia/Hong_Kong': 'Hong Kong Standard Time',
  'Asia/Hovd': 'Hovd Standard Time',
  'Asia/Irkutsk': 'Irkutsk Standard Time',
  'Asia/Jakarta': 'Western Indonesia Time',
  'Asia/Jayapura': 'Eastern Indonesia Time',
  'Asia/Jerusalem': 'Israel Standard Time',
  'Asia/Kabul': 'Afghanistan Time',
  'Asia/Kamchatka': 'Petropavlovsk-Kamchatski Standard Time',
  'Asia/Karachi': 'Pakistan Standard Time',
  'Asia/Kathmandu': 'Nepal Time',
  'Asia/Khandyga': 'Yakutsk Standard Time',
  'Asia/Kolkata': 'India Standard Time',
  'Asia/Krasnoyarsk': 'Krasnoyarsk Standard Time',
  'Asia/Kuala_Lumpur': 'Malaysia Time',
  'Asia/Kuching': 'Malaysia Time',
  'Asia/Kuwait': 'Arabian Standard Time',
  'Asia/Macau': 'China Standard Time',
  'Asia/Magadan': 'Magadan Standard Time',
  'Asia/Makassar': 'Central Indonesia Time',
  'Asia/Manila': 'Philippine Standard Time',
  'Asia/Muscat': 'Gulf Standard Time',
  'Asia/Nicosia': 'Eastern European Standard Time',
  'Asia/Novokuznetsk': 'Krasnoyarsk Standard Time',
  'Asia/Novosibirsk': 'Novosibirsk Standard Time',
  'Asia/Omsk': 'Omsk Standard Time',
  'Asia/Oral': 'West Kazakhstan Time',
  'Asia/Phnom_Penh': 'Indochina Time',
  'Asia/Pontianak': 'Western Indonesia Time',
  'Asia/Pyongyang': 'Pyongyang Time',
  'Asia/Qatar': 'Arabian Standard Time',
  'Asia/Qyzylorda': 'East Kazakhstan Time',
  'Asia/Riyadh': 'Arabian Standard Time',
  'Asia/Sakhalin': 'Sakhalin Standard Time',
  'Asia/Samarkand': 'Uzbekistan Standard Time',
  'Asia/Seoul': 'Korean Standard Time',
  'Asia/Shanghai': 'China Standard Time',
  'Asia/Singapore': 'Singapore Standard Time',
  'Asia/Srednekolymsk': 'GMT+11:00',
  'Asia/Taipei': 'Taipei Standard Time',
  'Asia/Tashkent': 'Uzbekistan Standard Time',
  'Asia/Tbilisi': 'Georgia Standard Time',
  'Asia/Tehran': 'Iran Standard Time',
  'Asia/Thimphu': 'Bhutan Time',
  'Asia/Tokyo': 'Japan Standard Time',
  'Asia/Tomsk': 'GMT+07:00',
  'Asia/Ulaanbaatar': 'Ulaanbaatar Standard Time',
  'Asia/Urumqi': 'GMT+06:00',
  'Asia/Ust-Nera': 'Vladivostok Standard Time',
  'Asia/Vientiane': 'Indochina Time',
  'Asia/Vladivostok': 'Vladivostok Standard Time',
  'Asia/Yakutsk': 'Yakutsk Standard Time',
  'Asia/Yangon': 'Myanmar Time',
  'Asia/Yekaterinburg': 'Yekaterinburg Standard Time',
  'Asia/Yerevan': 'Armenia Standard Time',
  'Atlantic/Azores': 'Azores Standard Time',
  'Atlantic/Bermuda': 'Atlantic Standard Time',
  'Atlantic/Canary': 'Western European Standard Time',
  'Atlantic/Cape_Verde': 'Cape Verde Standard Time',
  'Atlantic/Faroe': 'Western European Standard Time',
  'Atlantic/Madeira': 'Western European Standard Time',
  'Atlantic/Reykjavik': 'Greenwich Mean Time',
  'Atlantic/South_Georgia': 'South Georgia Time',
  'Atlantic/St_Helena': 'Greenwich Mean Time',
  'Atlantic/Stanley': 'Falkland Islands Standard Time',
  'Australia/Adelaide': 'Australian Central Standard Time',
  'Australia/Brisbane': 'Australian Eastern Standard Time',
  'Australia/Broken_Hill': 'Australian Central Standard Time',
  'Australia/Currie': 'Australian Eastern Standard Time',
  'Australia/Darwin': 'Australian Central Standard Time',
  'Australia/Eucla': 'Australian Central Western Standard Time',
  'Australia/Hobart': 'Australian Eastern Standard Time',
  'Australia/Lindeman': 'Australian Eastern Standard Time',
  'Australia/Lord_Howe': 'Lord Howe Standard Time',
  'Australia/Melbourne': 'Australian Eastern Standard Time',
  'Australia/Perth': 'Australian Western Standard Time',
  'Australia/Sydney': 'Australian Eastern Standard Time',
  'Europe/Amsterdam': 'Central European Standard Time',
  'Europe/Andorra': 'Central European Standard Time',
  'Europe/Astrakhan': 'GMT+04:00',
  'Europe/Athens': 'Eastern European Standard Time',
  'Europe/Belgrade': 'Central European Standard Time',
  'Europe/Berlin': 'Central European Standard Time',
  'Europe/Bratislava': 'Central European Standard Time',
  'Europe/Brussels': 'Central European Standard Time',
  'Europe/Bucharest': 'Eastern European Standard Time',
  'Europe/Budapest': 'Central European Standard Time',
  'Europe/Busingen': 'Central European Standard Time',
  'Europe/Chisinau': 'Eastern European Standard Time',
  'Europe/Copenhagen': 'Central European Standard Time',
  'Europe/Dublin': 'Greenwich Mean Time',
  'Europe/Gibraltar': 'Central European Standard Time',
  'Europe/Guernsey': 'Greenwich Mean Time',
  'Europe/Helsinki': 'Eastern European Standard Time',
  'Europe/Isle_of_Man': 'Greenwich Mean Time',
  'Europe/Istanbul': 'GMT+03:00',
  'Europe/Jersey': 'Greenwich Mean Time',
  'Europe/Kaliningrad': 'Eastern European Standard Time',
  'Europe/Kiev': 'Eastern European Standard Time',
  'Europe/Kirov': 'GMT+03:00',
  'Europe/Lisbon': 'Western European Standard Time',
  'Europe/Ljubljana': 'Central European Standard Time',
  'Europe/London': 'Greenwich Mean Time',
  'Europe/Luxembourg': 'Central European Standard Time',
  'Europe/Madrid': 'Central European Standard Time',
  'Europe/Malta': 'Central European Standard Time',
  'Europe/Mariehamn': 'Eastern European Standard Time',
  'Europe/Minsk': 'Moscow Standard Time',
  'Europe/Monaco': 'Central European Standard Time',
  'Europe/Moscow': 'Moscow Standard Time',
  'Europe/Oslo': 'Central European Standard Time',
  'Europe/Paris': 'Central European Standard Time',
  'Europe/Podgorica': 'Central European Standard Time',
  'Europe/Prague': 'Central European Standard Time',
  'Europe/Riga': 'Eastern European Standard Time',
  'Europe/Rome': 'Central European Standard Time',
  'Europe/Samara': 'Samara Standard Time',
  'Europe/San_Marino': 'Central European Standard Time',
  'Europe/Sarajevo': 'Central European Standard Time',
  'Europe/Saratov': 'GMT+04:00',
  'Europe/Simferopol': 'Moscow Standard Time',
  'Europe/Skopje': 'Central European Standard Time',
  'Europe/Sofia': 'Eastern European Standard Time',
  'Europe/Stockholm': 'Central European Standard Time',
  'Europe/Tallinn': 'Eastern European Standard Time',
  'Europe/Tirane': 'Central European Standard Time',
  'Europe/Ulyanovsk': 'GMT+04:00',
  'Europe/Uzhgorod': 'Eastern European Standard Time',
  'Europe/Vaduz': 'Central European Standard Time',
  'Europe/Vatican': 'Central European Standard Time',
  'Europe/Vienna': 'Central European Standard Time',
  'Europe/Vilnius': 'Eastern European Standard Time',
  'Europe/Volgograd': 'Moscow Standard Time',
  'Europe/Warsaw': 'Central European Standard Time',
  'Europe/Zagreb': 'Central European Standard Time',
  'Europe/Zaporozhye': 'Eastern European Standard Time',
  'Europe/Zurich': 'Central European Standard Time',
  'Indian/Antananarivo': 'East Africa Time',
  'Indian/Chagos': 'Indian Ocean Time',
  'Indian/Christmas': 'Christmas Island Time',
  'Indian/Cocos': 'Cocos Islands Time',
  'Indian/Comoro': 'East Africa Time',
  'Indian/Kerguelen': 'French Southern & Antarctic Time',
  'Indian/Mahe': 'Seychelles Time',
  'Indian/Maldives': 'Maldives Time',
  'Indian/Mauritius': 'Mauritius Standard Time',
  'Indian/Mayotte': 'East Africa Time',
  'Indian/Reunion': 'Reunion Time',
  'Pacific/Apia': 'Apia Standard Time',
  'Pacific/Auckland': 'New Zealand Standard Time',
  'Pacific/Bougainville': 'GMT+11:00',
  'Pacific/Chatham': 'Chatham Standard Time',
  'Pacific/Chuuk': 'Chuuk Time',
  'Pacific/Easter': 'Easter Island Standard Time',
  'Pacific/Efate': 'Vanuatu Standard Time',
  'Pacific/Enderbury': 'Phoenix Islands Time',
  'Pacific/Fakaofo': 'Tokelau Time',
  'Pacific/Fiji': 'Fiji Standard Time',
  'Pacific/Funafuti': 'Tuvalu Time',
  'Pacific/Galapagos': 'Galapagos Time',
  'Pacific/Gambier': 'Gambier Time',
  'Pacific/Guadalcanal': 'Solomon Islands Time',
  'Pacific/Guam': 'Chamorro Standard Time',
  'Pacific/Honolulu': 'Hawaii-Aleutian Standard Time',
  'Pacific/Kiritimati': 'Line Islands Time',
  'Pacific/Kosrae': 'Kosrae Time',
  'Pacific/Kwajalein': 'Marshall Islands Time',
  'Pacific/Majuro': 'Marshall Islands Time',
  'Pacific/Marquesas': 'Marquesas Time',
  'Pacific/Midway': 'Samoa Standard Time',
  'Pacific/Nauru': 'Nauru Time',
  'Pacific/Niue': 'Niue Time',
  'Pacific/Norfolk': 'Norfolk Island Time',
  'Pacific/Noumea': 'New Caledonia Standard Time',
  'Pacific/Pago_Pago': 'Samoa Standard Time',
  'Pacific/Palau': 'Palau Time',
  'Pacific/Pitcairn': 'Pitcairn Time',
  'Pacific/Pohnpei': 'Ponape Time',
  'Pacific/Port_Moresby': 'Papua New Guinea Time',
  'Pacific/Rarotonga': 'Cook Islands Standard Time',
  'Pacific/Saipan': 'Chamorro Standard Time',
  'Pacific/Tahiti': 'Tahiti Time',
  'Pacific/Tarawa': 'Gilbert Islands Time',
  'Pacific/Tongatapu': 'Tonga Standard Time',
  'Pacific/Wake': 'Wake Island Time',
  'Pacific/Wallis': 'Wallis & Futuna Time',
  UTC: 'Coordinated Universal Time',
};
