module.exports = {
  'Africa/Abidjan': 'hora del meridiano de Greenwich',
  'Africa/Accra': 'hora del meridiano de Greenwich',
  'Africa/Addis_Ababa': 'hora de África oriental',
  'Africa/Algiers': 'hora estándar de Europa central',
  'Africa/Asmara': 'hora de África oriental',
  'Africa/Bamako': 'hora del meridiano de Greenwich',
  'Africa/Bangui': 'hora estándar de África occidental',
  'Africa/Banjul': 'hora del meridiano de Greenwich',
  'Africa/Bissau': 'hora del meridiano de Greenwich',
  'Africa/Blantyre': 'hora de África central',
  'Africa/Brazzaville': 'hora estándar de África occidental',
  'Africa/Bujumbura': 'hora de África central',
  'Africa/Cairo': 'hora estándar de Europa oriental',
  'Africa/Casablanca': 'hora estándar de Europa occidental',
  'Africa/Ceuta': 'hora estándar de Europa central',
  'Africa/Conakry': 'hora del meridiano de Greenwich',
  'Africa/Dakar': 'hora del meridiano de Greenwich',
  'Africa/Dar_es_Salaam': 'hora de África oriental',
  'Africa/Djibouti': 'hora de África oriental',
  'Africa/Douala': 'hora estándar de África occidental',
  'Africa/El_Aaiun': 'hora estándar de Europa occidental',
  'Africa/Freetown': 'hora del meridiano de Greenwich',
  'Africa/Gaborone': 'hora de África central',
  'Africa/Harare': 'hora de África central',
  'Africa/Johannesburg': 'hora de Sudáfrica',
  'Africa/Juba': 'hora de África oriental',
  'Africa/Kampala': 'hora de África oriental',
  'Africa/Khartoum': 'hora de África central',
  'Africa/Kigali': 'hora de África central',
  'Africa/Kinshasa': 'hora estándar de África occidental',
  'Africa/Lagos': 'hora estándar de África occidental',
  'Africa/Libreville': 'hora estándar de África occidental',
  'Africa/Lome': 'hora del meridiano de Greenwich',
  'Africa/Luanda': 'hora estándar de África occidental',
  'Africa/Lubumbashi': 'hora de África central',
  'Africa/Lusaka': 'hora de África central',
  'Africa/Malabo': 'hora estándar de África occidental',
  'Africa/Maputo': 'hora de África central',
  'Africa/Maseru': 'hora de Sudáfrica',
  'Africa/Mbabane': 'hora de Sudáfrica',
  'Africa/Mogadishu': 'hora de África oriental',
  'Africa/Monrovia': 'hora del meridiano de Greenwich',
  'Africa/Nairobi': 'hora de África oriental',
  'Africa/Ndjamena': 'hora estándar de África occidental',
  'Africa/Niamey': 'hora estándar de África occidental',
  'Africa/Nouakchott': 'hora del meridiano de Greenwich',
  'Africa/Ouagadougou': 'hora del meridiano de Greenwich',
  'Africa/Porto-Novo': 'hora estándar de África occidental',
  'Africa/Sao_Tome': 'hora del meridiano de Greenwich',
  'Africa/Tripoli': 'hora estándar de Europa oriental',
  'Africa/Tunis': 'hora estándar de Europa central',
  'Africa/Windhoek': 'hora de África central',
  'America/Adak': 'hora estándar de Hawái-Aleutianas',
  'America/Anchorage': 'hora estándar de Alaska',
  'America/Anguilla': 'hora estándar del Atlántico',
  'America/Antigua': 'hora estándar del Atlántico',
  'America/Araguaina': 'hora estándar de Brasilia',
  'America/Argentina/Buenos_Aires': 'hora estándar de Argentina',
  'America/Argentina/Catamarca': 'hora estándar de Argentina',
  'America/Argentina/Cordoba': 'hora estándar de Argentina',
  'America/Argentina/Jujuy': 'hora estándar de Argentina',
  'America/Argentina/La_Rioja': 'hora estándar de Argentina',
  'America/Argentina/Mendoza': 'hora estándar de Argentina',
  'America/Argentina/Rio_Gallegos': 'hora estándar de Argentina',
  'America/Argentina/Salta': 'hora estándar de Argentina',
  'America/Argentina/San_Juan': 'hora estándar de Argentina',
  'America/Argentina/San_Luis': 'hora estándar de Argentina occidental',
  'America/Argentina/Tucuman': 'hora estándar de Argentina',
  'America/Argentina/Ushuaia': 'hora estándar de Argentina',
  'America/Aruba': 'hora estándar del Atlántico',
  'America/Asuncion': 'hora estándar de Paraguay',
  'America/Atikokan': 'hora estándar oriental',
  'America/Bahia': 'hora estándar de Brasilia',
  'America/Bahia_Banderas': 'hora estándar central',
  'America/Barbados': 'hora estándar del Atlántico',
  'America/Belem': 'hora estándar de Brasilia',
  'America/Belize': 'hora estándar central',
  'America/Blanc-Sablon': 'hora estándar del Atlántico',
  'America/Boa_Vista': 'hora estándar del Amazonas',
  'America/Bogota': 'hora estándar de Colombia',
  'America/Boise': 'hora estándar de las Montañas Rocosas',
  'America/Cambridge_Bay': 'hora estándar de las Montañas Rocosas',
  'America/Campo_Grande': 'hora estándar del Amazonas',
  'America/Cancun': 'hora estándar oriental',
  'America/Caracas': 'hora de Venezuela',
  'America/Cayenne': 'hora de la Guayana Francesa',
  'America/Cayman': 'hora estándar oriental',
  'America/Chicago': 'hora estándar central',
  'America/Chihuahua': 'hora estándar del Pacífico de México',
  'America/Costa_Rica': 'hora estándar central',
  'America/Creston': 'hora estándar de las Montañas Rocosas',
  'America/Cuiaba': 'hora estándar del Amazonas',
  'America/Curacao': 'hora estándar del Atlántico',
  'America/Danmarkshavn': 'hora del meridiano de Greenwich',
  'America/Dawson': 'hora estándar del Pacífico',
  'America/Dawson_Creek': 'hora estándar de las Montañas Rocosas',
  'America/Denver': 'hora estándar de las Montañas Rocosas',
  'America/Detroit': 'hora estándar oriental',
  'America/Dominica': 'hora estándar del Atlántico',
  'America/Edmonton': 'hora estándar de las Montañas Rocosas',
  'America/Eirunepe': 'Hora estándar de Acre',
  'America/El_Salvador': 'hora estándar central',
  'America/Fort_Nelson': 'hora estándar de las Montañas Rocosas',
  'America/Fortaleza': 'hora estándar de Brasilia',
  'America/Glace_Bay': 'hora estándar del Atlántico',
  'America/Godthab': 'hora estándar de Groenlandia occidental',
  'America/Goose_Bay': 'hora estándar del Atlántico',
  'America/Grand_Turk': 'hora estándar oriental',
  'America/Grenada': 'hora estándar del Atlántico',
  'America/Guadeloupe': 'hora estándar del Atlántico',
  'America/Guatemala': 'hora estándar central',
  'America/Guayaquil': 'hora de Ecuador',
  'America/Guyana': 'hora de Guyana',
  'America/Halifax': 'hora estándar del Atlántico',
  'America/Havana': 'hora estándar de Cuba',
  'America/Hermosillo': 'hora estándar del Pacífico de México',
  'America/Indiana/Indianapolis': 'hora estándar oriental',
  'America/Indiana/Knox': 'hora estándar central',
  'America/Indiana/Marengo': 'hora estándar oriental',
  'America/Indiana/Petersburg': 'hora estándar oriental',
  'America/Indiana/Tell_City': 'hora estándar central',
  'America/Indiana/Vevay': 'hora estándar oriental',
  'America/Indiana/Vincennes': 'hora estándar oriental',
  'America/Indiana/Winamac': 'hora estándar oriental',
  'America/Inuvik': 'hora estándar de las Montañas Rocosas',
  'America/Iqaluit': 'hora estándar oriental',
  'America/Jamaica': 'hora estándar oriental',
  'America/Juneau': 'hora estándar de Alaska',
  'America/Kentucky/Louisville': 'hora estándar oriental',
  'America/Kentucky/Monticello': 'hora estándar oriental',
  'America/Kralendijk': 'hora estándar del Atlántico',
  'America/La_Paz': 'hora de Bolivia',
  'America/Lima': 'hora estándar de Perú',
  'America/Los_Angeles': 'hora estándar del Pacífico',
  'America/Lower_Princes': 'hora estándar del Atlántico',
  'America/Maceio': 'hora estándar de Brasilia',
  'America/Managua': 'hora estándar central',
  'America/Manaus': 'hora estándar del Amazonas',
  'America/Marigot': 'hora estándar del Atlántico',
  'America/Martinique': 'hora estándar del Atlántico',
  'America/Matamoros': 'hora estándar central',
  'America/Mazatlan': 'hora estándar del Pacífico de México',
  'America/Menominee': 'hora estándar central',
  'America/Merida': 'hora estándar central',
  'America/Metlakatla': 'hora estándar de Alaska',
  'America/Mexico_City': 'hora estándar central',
  'America/Miquelon': 'hora estándar de San Pedro y Miquelón',
  'America/Moncton': 'hora estándar del Atlántico',
  'America/Monterrey': 'hora estándar central',
  'America/Montevideo': 'hora estándar de Uruguay',
  'America/Montserrat': 'hora estándar del Atlántico',
  'America/Nassau': 'hora estándar oriental',
  'America/New_York': 'hora estándar oriental',
  'America/Nipigon': 'hora estándar oriental',
  'America/Nome': 'hora estándar de Alaska',
  'America/Noronha': 'hora estándar de Fernando de Noronha',
  'America/North_Dakota/Beulah': 'hora estándar central',
  'America/North_Dakota/Center': 'hora estándar central',
  'America/North_Dakota/New_Salem': 'hora estándar central',
  'America/Ojinaga': 'hora estándar de las Montañas Rocosas',
  'America/Panama': 'hora estándar oriental',
  'America/Pangnirtung': 'hora estándar oriental',
  'America/Paramaribo': 'hora de Surinam',
  'America/Phoenix': 'hora estándar de las Montañas Rocosas',
  'America/Port-au-Prince': 'hora estándar oriental',
  'America/Port_of_Spain': 'hora estándar del Atlántico',
  'America/Porto_Velho': 'hora estándar del Amazonas',
  'America/Puerto_Rico': 'hora estándar del Atlántico',
  'America/Punta_Arenas': 'GMT-03:00',
  'America/Rainy_River': 'hora estándar central',
  'America/Rankin_Inlet': 'hora estándar central',
  'America/Recife': 'hora estándar de Brasilia',
  'America/Regina': 'hora estándar central',
  'America/Resolute': 'hora estándar central',
  'America/Rio_Branco': 'Hora estándar de Acre',
  'America/Santarem': 'hora estándar de Brasilia',
  'America/Santiago': 'hora estándar de Chile',
  'America/Santo_Domingo': 'hora estándar del Atlántico',
  'America/Sao_Paulo': 'hora estándar de Brasilia',
  'America/Scoresbysund': 'hora estándar de Groenlandia oriental',
  'America/Sitka': 'hora estándar de Alaska',
  'America/St_Barthelemy': 'hora estándar del Atlántico',
  'America/St_Johns': 'hora estándar de Terranova',
  'America/St_Kitts': 'hora estándar del Atlántico',
  'America/St_Lucia': 'hora estándar del Atlántico',
  'America/St_Thomas': 'hora estándar del Atlántico',
  'America/St_Vincent': 'hora estándar del Atlántico',
  'America/Swift_Current': 'hora estándar central',
  'America/Tegucigalpa': 'hora estándar central',
  'America/Thule': 'hora estándar del Atlántico',
  'America/Thunder_Bay': 'hora estándar oriental',
  'America/Tijuana': 'hora estándar del Pacífico',
  'America/Toronto': 'hora estándar oriental',
  'America/Tortola': 'hora estándar del Atlántico',
  'America/Vancouver': 'hora estándar del Pacífico',
  'America/Whitehorse': 'hora estándar del Pacífico',
  'America/Winnipeg': 'hora estándar central',
  'America/Yakutat': 'hora estándar de Alaska',
  'America/Yellowknife': 'hora estándar de las Montañas Rocosas',
  'Antarctica/Casey': 'GMT+11:00',
  'Antarctica/Davis': 'hora de Davis',
  'Antarctica/DumontDUrville': 'hora de Dumont-d’Urville',
  'Antarctica/Macquarie': 'hora de la isla Macquarie',
  'Antarctica/Mawson': 'hora de Mawson',
  'Antarctica/McMurdo': 'hora estándar de Nueva Zelanda',
  'Antarctica/Palmer': 'GMT-03:00',
  'Antarctica/Rothera': 'hora de Rothera',
  'Antarctica/Syowa': 'hora de Syowa',
  'Antarctica/Troll': 'hora del meridiano de Greenwich',
  'Antarctica/Vostok': 'hora de Vostok',
  'Arctic/Longyearbyen': 'hora estándar de Europa central',
  'Asia/Aden': 'hora estándar de Arabia',
  'Asia/Almaty': 'hora de Kazajistán oriental',
  'Asia/Amman': 'hora estándar de Europa oriental',
  'Asia/Anadyr': 'hora estándar de Anadyr',
  'Asia/Aqtau': 'hora de Kazajistán occidental',
  'Asia/Aqtobe': 'hora de Kazajistán occidental',
  'Asia/Ashgabat': 'hora estándar de Turkmenistán',
  'Asia/Atyrau': 'hora de Kazajistán occidental',
  'Asia/Baghdad': 'hora estándar de Arabia',
  'Asia/Bahrain': 'hora estándar de Arabia',
  'Asia/Baku': 'hora estándar de Azerbaiyán',
  'Asia/Bangkok': 'hora de Indochina',
  'Asia/Barnaul': 'GMT+07:00',
  'Asia/Beirut': 'hora estándar de Europa oriental',
  'Asia/Bishkek': 'hora de Kirguistán',
  'Asia/Brunei': 'hora de Brunéi',
  'Asia/Chita': 'hora estándar de Yakutsk',
  'Asia/Choibalsan': 'hora estándar de Choibalsan',
  'Asia/Colombo': 'hora estándar de la India',
  'Asia/Damascus': 'hora estándar de Europa oriental',
  'Asia/Dhaka': 'hora estándar de Bangladés',
  'Asia/Dili': 'hora de Timor Oriental',
  'Asia/Dubai': 'hora estándar del Golfo',
  'Asia/Dushanbe': 'hora de Tayikistán',
  'Asia/Famagusta': 'GMT+02:00',
  'Asia/Gaza': 'hora estándar de Europa oriental',
  'Asia/Hebron': 'hora estándar de Europa oriental',
  'Asia/Ho_Chi_Minh': 'hora de Indochina',
  'Asia/Hong_Kong': 'hora estándar de Hong Kong',
  'Asia/Hovd': 'hora estándar de Hovd',
  'Asia/Irkutsk': 'hora estándar de Irkutsk',
  'Asia/Jakarta': 'hora de Indonesia occidental',
  'Asia/Jayapura': 'hora de Indonesia oriental',
  'Asia/Jerusalem': 'hora estándar de Israel',
  'Asia/Kabul': 'hora de Afganistán',
  'Asia/Kamchatka': 'hora estándar de Kamchatka',
  'Asia/Karachi': 'hora estándar de Pakistán',
  'Asia/Kathmandu': 'hora de Nepal',
  'Asia/Khandyga': 'hora estándar de Yakutsk',
  'Asia/Kolkata': 'hora estándar de la India',
  'Asia/Krasnoyarsk': 'hora estándar de Krasnoyarsk',
  'Asia/Kuala_Lumpur': 'hora de Malasia',
  'Asia/Kuching': 'hora de Malasia',
  'Asia/Kuwait': 'hora estándar de Arabia',
  'Asia/Macau': 'hora estándar de China',
  'Asia/Magadan': 'hora estándar de Magadán',
  'Asia/Makassar': 'hora de Indonesia central',
  'Asia/Manila': 'hora estándar de Filipinas',
  'Asia/Muscat': 'hora estándar del Golfo',
  'Asia/Nicosia': 'hora estándar de Europa oriental',
  'Asia/Novokuznetsk': 'hora estándar de Krasnoyarsk',
  'Asia/Novosibirsk': 'hora estándar de Novosibirsk',
  'Asia/Omsk': 'hora estándar de Omsk',
  'Asia/Oral': 'hora de Kazajistán occidental',
  'Asia/Phnom_Penh': 'hora de Indochina',
  'Asia/Pontianak': 'hora de Indonesia occidental',
  'Asia/Pyongyang': 'hora de Pyongyang',
  'Asia/Qatar': 'hora estándar de Arabia',
  'Asia/Qyzylorda': 'hora de Kazajistán oriental',
  'Asia/Riyadh': 'hora estándar de Arabia',
  'Asia/Sakhalin': 'hora estándar de Sajalín',
  'Asia/Samarkand': 'hora estándar de Uzbekistán',
  'Asia/Seoul': 'hora estándar de Corea',
  'Asia/Shanghai': 'hora estándar de China',
  'Asia/Singapore': 'hora de Singapur',
  'Asia/Srednekolymsk': 'GMT+11:00',
  'Asia/Taipei': 'hora estándar de Taipéi',
  'Asia/Tashkent': 'hora estándar de Uzbekistán',
  'Asia/Tbilisi': 'hora estándar de Georgia',
  'Asia/Tehran': 'hora estándar de Irán',
  'Asia/Thimphu': 'hora de Bután',
  'Asia/Tokyo': 'hora estándar de Japón',
  'Asia/Tomsk': 'GMT+07:00',
  'Asia/Ulaanbaatar': 'hora estándar de Ulán Bator',
  'Asia/Urumqi': 'GMT+06:00',
  'Asia/Ust-Nera': 'hora estándar de Vladivostok',
  'Asia/Vientiane': 'hora de Indochina',
  'Asia/Vladivostok': 'hora estándar de Vladivostok',
  'Asia/Yakutsk': 'hora estándar de Yakutsk',
  'Asia/Yangon': 'hora de Myanmar (Birmania)',
  'Asia/Yekaterinburg': 'hora estándar de Ekaterimburgo',
  'Asia/Yerevan': 'hora estándar de Armenia',
  'Atlantic/Azores': 'hora estándar de las Azores',
  'Atlantic/Bermuda': 'hora estándar del Atlántico',
  'Atlantic/Canary': 'hora estándar de Europa occidental',
  'Atlantic/Cape_Verde': 'hora estándar de Cabo Verde',
  'Atlantic/Faroe': 'hora estándar de Europa occidental',
  'Atlantic/Madeira': 'hora estándar de Europa occidental',
  'Atlantic/Reykjavik': 'hora del meridiano de Greenwich',
  'Atlantic/South_Georgia': 'hora de Georgia del Sur',
  'Atlantic/St_Helena': 'hora del meridiano de Greenwich',
  'Atlantic/Stanley': 'hora estándar de las islas Malvinas',
  'Australia/Adelaide': 'hora estándar de Australia central',
  'Australia/Brisbane': 'hora estándar de Australia oriental',
  'Australia/Broken_Hill': 'hora estándar de Australia central',
  'Australia/Currie': 'hora estándar de Australia oriental',
  'Australia/Darwin': 'hora estándar de Australia central',
  'Australia/Eucla': 'hora estándar de Australia centroccidental',
  'Australia/Hobart': 'hora estándar de Australia oriental',
  'Australia/Lindeman': 'hora estándar de Australia oriental',
  'Australia/Lord_Howe': 'hora estándar de Lord Howe',
  'Australia/Melbourne': 'hora estándar de Australia oriental',
  'Australia/Perth': 'hora estándar de Australia occidental',
  'Australia/Sydney': 'hora estándar de Australia oriental',
  'Europe/Amsterdam': 'hora estándar de Europa central',
  'Europe/Andorra': 'hora estándar de Europa central',
  'Europe/Astrakhan': 'GMT+04:00',
  'Europe/Athens': 'hora estándar de Europa oriental',
  'Europe/Belgrade': 'hora estándar de Europa central',
  'Europe/Berlin': 'hora estándar de Europa central',
  'Europe/Bratislava': 'hora estándar de Europa central',
  'Europe/Brussels': 'hora estándar de Europa central',
  'Europe/Bucharest': 'hora estándar de Europa oriental',
  'Europe/Budapest': 'hora estándar de Europa central',
  'Europe/Busingen': 'hora estándar de Europa central',
  'Europe/Chisinau': 'hora estándar de Europa oriental',
  'Europe/Copenhagen': 'hora estándar de Europa central',
  'Europe/Dublin': 'hora del meridiano de Greenwich',
  'Europe/Gibraltar': 'hora estándar de Europa central',
  'Europe/Guernsey': 'hora del meridiano de Greenwich',
  'Europe/Helsinki': 'hora estándar de Europa oriental',
  'Europe/Isle_of_Man': 'hora del meridiano de Greenwich',
  'Europe/Istanbul': 'GMT+03:00',
  'Europe/Jersey': 'hora del meridiano de Greenwich',
  'Europe/Kaliningrad': 'hora estándar de Europa oriental',
  'Europe/Kiev': 'hora estándar de Europa oriental',
  'Europe/Kirov': 'GMT+03:00',
  'Europe/Lisbon': 'hora estándar de Europa occidental',
  'Europe/Ljubljana': 'hora estándar de Europa central',
  'Europe/London': 'hora del meridiano de Greenwich',
  'Europe/Luxembourg': 'hora estándar de Europa central',
  'Europe/Madrid': 'hora estándar de Europa central',
  'Europe/Malta': 'hora estándar de Europa central',
  'Europe/Mariehamn': 'hora estándar de Europa oriental',
  'Europe/Minsk': 'hora estándar de Moscú',
  'Europe/Monaco': 'hora estándar de Europa central',
  'Europe/Moscow': 'hora estándar de Moscú',
  'Europe/Oslo': 'hora estándar de Europa central',
  'Europe/Paris': 'hora estándar de Europa central',
  'Europe/Podgorica': 'hora estándar de Europa central',
  'Europe/Prague': 'hora estándar de Europa central',
  'Europe/Riga': 'hora estándar de Europa oriental',
  'Europe/Rome': 'hora estándar de Europa central',
  'Europe/Samara': 'hora estándar de Samara',
  'Europe/San_Marino': 'hora estándar de Europa central',
  'Europe/Sarajevo': 'hora estándar de Europa central',
  'Europe/Saratov': 'GMT+04:00',
  'Europe/Simferopol': 'hora estándar de Moscú',
  'Europe/Skopje': 'hora estándar de Europa central',
  'Europe/Sofia': 'hora estándar de Europa oriental',
  'Europe/Stockholm': 'hora estándar de Europa central',
  'Europe/Tallinn': 'hora estándar de Europa oriental',
  'Europe/Tirane': 'hora estándar de Europa central',
  'Europe/Ulyanovsk': 'GMT+04:00',
  'Europe/Uzhgorod': 'hora estándar de Europa oriental',
  'Europe/Vaduz': 'hora estándar de Europa central',
  'Europe/Vatican': 'hora estándar de Europa central',
  'Europe/Vienna': 'hora estándar de Europa central',
  'Europe/Vilnius': 'hora estándar de Europa oriental',
  'Europe/Volgograd': 'hora estándar de Moscú',
  'Europe/Warsaw': 'hora estándar de Europa central',
  'Europe/Zagreb': 'hora estándar de Europa central',
  'Europe/Zaporozhye': 'hora estándar de Europa oriental',
  'Europe/Zurich': 'hora estándar de Europa central',
  'Indian/Antananarivo': 'hora de África oriental',
  'Indian/Chagos': 'hora del océano Índico',
  'Indian/Christmas': 'hora de la Isla de Navidad',
  'Indian/Cocos': 'hora de las Islas Cocos',
  'Indian/Comoro': 'hora de África oriental',
  'Indian/Kerguelen': 'hora de las Tierras Australes y Antárticas Francesas',
  'Indian/Mahe': 'hora de Seychelles',
  'Indian/Maldives': 'hora de Maldivas',
  'Indian/Mauritius': 'hora estándar de Mauricio',
  'Indian/Mayotte': 'hora de África oriental',
  'Indian/Reunion': 'hora de Reunión',
  'Pacific/Apia': 'hora estándar de Apia',
  'Pacific/Auckland': 'hora estándar de Nueva Zelanda',
  'Pacific/Bougainville': 'GMT+11:00',
  'Pacific/Chatham': 'hora estándar de Chatham',
  'Pacific/Chuuk': 'hora de Chuuk',
  'Pacific/Easter': 'hora estándar de la isla de Pascua',
  'Pacific/Efate': 'hora estándar de Vanuatu',
  'Pacific/Enderbury': 'hora de las Islas Fénix',
  'Pacific/Fakaofo': 'hora de Tokelau',
  'Pacific/Fiji': 'hora estándar de Fiyi',
  'Pacific/Funafuti': 'hora de Tuvalu',
  'Pacific/Galapagos': 'hora de Galápagos',
  'Pacific/Gambier': 'hora de Gambier',
  'Pacific/Guadalcanal': 'hora de las Islas Salomón',
  'Pacific/Guam': 'hora estándar de Chamorro',
  'Pacific/Honolulu': 'hora estándar de Hawái-Aleutianas',
  'Pacific/Kiritimati': 'hora de las Espóradas Ecuatoriales',
  'Pacific/Kosrae': 'hora de Kosrae',
  'Pacific/Kwajalein': 'hora de las Islas Marshall',
  'Pacific/Majuro': 'hora de las Islas Marshall',
  'Pacific/Marquesas': 'hora de Marquesas',
  'Pacific/Midway': 'hora estándar de Samoa',
  'Pacific/Nauru': 'hora de Nauru',
  'Pacific/Niue': 'hora de Niue',
  'Pacific/Norfolk': 'hora de la isla Norfolk',
  'Pacific/Noumea': 'hora estándar de Nueva Caledonia',
  'Pacific/Pago_Pago': 'hora estándar de Samoa',
  'Pacific/Palau': 'hora de Palaos',
  'Pacific/Pitcairn': 'hora de Pitcairn',
  'Pacific/Pohnpei': 'hora de Pohnpei',
  'Pacific/Port_Moresby': 'hora de Papúa Nueva Guinea',
  'Pacific/Rarotonga': 'hora estándar de las Islas Cook',
  'Pacific/Saipan': 'hora estándar de Chamorro',
  'Pacific/Tahiti': 'hora de Tahití',
  'Pacific/Tarawa': 'hora de las islas Gilbert',
  'Pacific/Tongatapu': 'hora estándar de Tonga',
  'Pacific/Wake': 'hora de la isla Wake',
  'Pacific/Wallis': 'hora de Wallis y Futuna',
  UTC: 'tiempo universal coordinado',
};
