module.exports = {
  'Africa/Abidjan': 'heure moyenne de Greenwich',
  'Africa/Accra': 'heure moyenne de Greenwich',
  'Africa/Addis_Ababa': 'heure normale d’Afrique de l’Est',
  'Africa/Algiers': 'heure normale d’Europe centrale',
  'Africa/Asmara': 'heure normale d’Afrique de l’Est',
  'Africa/Bamako': 'heure moyenne de Greenwich',
  'Africa/Bangui': 'heure normale d’Afrique de l’Ouest',
  'Africa/Banjul': 'heure moyenne de Greenwich',
  'Africa/Bissau': 'heure moyenne de Greenwich',
  'Africa/Blantyre': 'heure normale d’Afrique centrale',
  'Africa/Brazzaville': 'heure normale d’Afrique de l’Ouest',
  'Africa/Bujumbura': 'heure normale d’Afrique centrale',
  'Africa/Cairo': 'heure normale d’Europe de l’Est',
  'Africa/Casablanca': 'heure normale d’Europe de l’Ouest',
  'Africa/Ceuta': 'heure normale d’Europe centrale',
  'Africa/Conakry': 'heure moyenne de Greenwich',
  'Africa/Dakar': 'heure moyenne de Greenwich',
  'Africa/Dar_es_Salaam': 'heure normale d’Afrique de l’Est',
  'Africa/Djibouti': 'heure normale d’Afrique de l’Est',
  'Africa/Douala': 'heure normale d’Afrique de l’Ouest',
  'Africa/El_Aaiun': 'heure normale d’Europe de l’Ouest',
  'Africa/Freetown': 'heure moyenne de Greenwich',
  'Africa/Gaborone': 'heure normale d’Afrique centrale',
  'Africa/Harare': 'heure normale d’Afrique centrale',
  'Africa/Johannesburg': 'heure normale d’Afrique méridionale',
  'Africa/Juba': 'heure normale d’Afrique de l’Est',
  'Africa/Kampala': 'heure normale d’Afrique de l’Est',
  'Africa/Khartoum': 'heure normale d’Afrique centrale',
  'Africa/Kigali': 'heure normale d’Afrique centrale',
  'Africa/Kinshasa': 'heure normale d’Afrique de l’Ouest',
  'Africa/Lagos': 'heure normale d’Afrique de l’Ouest',
  'Africa/Libreville': 'heure normale d’Afrique de l’Ouest',
  'Africa/Lome': 'heure moyenne de Greenwich',
  'Africa/Luanda': 'heure normale d’Afrique de l’Ouest',
  'Africa/Lubumbashi': 'heure normale d’Afrique centrale',
  'Africa/Lusaka': 'heure normale d’Afrique centrale',
  'Africa/Malabo': 'heure normale d’Afrique de l’Ouest',
  'Africa/Maputo': 'heure normale d’Afrique centrale',
  'Africa/Maseru': 'heure normale d’Afrique méridionale',
  'Africa/Mbabane': 'heure normale d’Afrique méridionale',
  'Africa/Mogadishu': 'heure normale d’Afrique de l’Est',
  'Africa/Monrovia': 'heure moyenne de Greenwich',
  'Africa/Nairobi': 'heure normale d’Afrique de l’Est',
  'Africa/Ndjamena': 'heure normale d’Afrique de l’Ouest',
  'Africa/Niamey': 'heure normale d’Afrique de l’Ouest',
  'Africa/Nouakchott': 'heure moyenne de Greenwich',
  'Africa/Ouagadougou': 'heure moyenne de Greenwich',
  'Africa/Porto-Novo': 'heure normale d’Afrique de l’Ouest',
  'Africa/Sao_Tome': 'heure moyenne de Greenwich',
  'Africa/Tripoli': 'heure normale d’Europe de l’Est',
  'Africa/Tunis': 'heure normale d’Europe centrale',
  'Africa/Windhoek': 'heure normale d’Afrique centrale',
  'America/Adak': 'heure normale d’Hawaii - Aléoutiennes',
  'America/Anchorage': 'heure normale de l’Alaska',
  'America/Anguilla': 'heure normale de l’Atlantique',
  'America/Antigua': 'heure normale de l’Atlantique',
  'America/Araguaina': 'heure normale de Brasilia',
  'America/Argentina/Buenos_Aires': 'heure normale d’Argentine',
  'America/Argentina/Catamarca': 'heure normale d’Argentine',
  'America/Argentina/Cordoba': 'heure normale d’Argentine',
  'America/Argentina/Jujuy': 'heure normale d’Argentine',
  'America/Argentina/La_Rioja': 'heure normale d’Argentine',
  'America/Argentina/Mendoza': 'heure normale d’Argentine',
  'America/Argentina/Rio_Gallegos': 'heure normale d’Argentine',
  'America/Argentina/Salta': 'heure normale d’Argentine',
  'America/Argentina/San_Juan': 'heure normale d’Argentine',
  'America/Argentina/San_Luis': 'heure normale de l’Ouest argentin',
  'America/Argentina/Tucuman': 'heure normale d’Argentine',
  'America/Argentina/Ushuaia': 'heure normale d’Argentine',
  'America/Aruba': 'heure normale de l’Atlantique',
  'America/Asuncion': 'heure normale du Paraguay',
  'America/Atikokan': 'heure normale de l’Est nord-américain',
  'America/Bahia': 'heure normale de Brasilia',
  'America/Bahia_Banderas': 'heure normale du centre nord-américain',
  'America/Barbados': 'heure normale de l’Atlantique',
  'America/Belem': 'heure normale de Brasilia',
  'America/Belize': 'heure normale du centre nord-américain',
  'America/Blanc-Sablon': 'heure normale de l’Atlantique',
  'America/Boa_Vista': 'heure normale de l’Amazonie',
  'America/Bogota': 'heure normale de Colombie',
  'America/Boise': 'heure normale des Rocheuses',
  'America/Cambridge_Bay': 'heure normale des Rocheuses',
  'America/Campo_Grande': 'heure normale de l’Amazonie',
  'America/Cancun': 'heure normale de l’Est nord-américain',
  'America/Caracas': 'heure du Venezuela',
  'America/Cayenne': 'heure de la Guyane française',
  'America/Cayman': 'heure normale de l’Est nord-américain',
  'America/Chicago': 'heure normale du centre nord-américain',
  'America/Chihuahua': 'heure normale du Pacifique mexicain',
  'America/Costa_Rica': 'heure normale du centre nord-américain',
  'America/Creston': 'heure normale des Rocheuses',
  'America/Cuiaba': 'heure normale de l’Amazonie',
  'America/Curacao': 'heure normale de l’Atlantique',
  'America/Danmarkshavn': 'heure moyenne de Greenwich',
  'America/Dawson': 'heure normale du Pacifique nord-américain',
  'America/Dawson_Creek': 'heure normale des Rocheuses',
  'America/Denver': 'heure normale des Rocheuses',
  'America/Detroit': 'heure normale de l’Est nord-américain',
  'America/Dominica': 'heure normale de l’Atlantique',
  'America/Edmonton': 'heure normale des Rocheuses',
  'America/Eirunepe': 'heure normale de l’Acre',
  'America/El_Salvador': 'heure normale du centre nord-américain',
  'America/Fort_Nelson': 'heure normale des Rocheuses',
  'America/Fortaleza': 'heure normale de Brasilia',
  'America/Glace_Bay': 'heure normale de l’Atlantique',
  'America/Godthab': 'heure normale de l’Ouest du Groenland',
  'America/Goose_Bay': 'heure normale de l’Atlantique',
  'America/Grand_Turk': 'heure normale de l’Est nord-américain',
  'America/Grenada': 'heure normale de l’Atlantique',
  'America/Guadeloupe': 'heure normale de l’Atlantique',
  'America/Guatemala': 'heure normale du centre nord-américain',
  'America/Guayaquil': 'heure de l’Équateur',
  'America/Guyana': 'heure du Guyana',
  'America/Halifax': 'heure normale de l’Atlantique',
  'America/Havana': 'heure normale de Cuba',
  'America/Hermosillo': 'heure normale du Pacifique mexicain',
  'America/Indiana/Indianapolis': 'heure normale de l’Est nord-américain',
  'America/Indiana/Knox': 'heure normale du centre nord-américain',
  'America/Indiana/Marengo': 'heure normale de l’Est nord-américain',
  'America/Indiana/Petersburg': 'heure normale de l’Est nord-américain',
  'America/Indiana/Tell_City': 'heure normale du centre nord-américain',
  'America/Indiana/Vevay': 'heure normale de l’Est nord-américain',
  'America/Indiana/Vincennes': 'heure normale de l’Est nord-américain',
  'America/Indiana/Winamac': 'heure normale de l’Est nord-américain',
  'America/Inuvik': 'heure normale des Rocheuses',
  'America/Iqaluit': 'heure normale de l’Est nord-américain',
  'America/Jamaica': 'heure normale de l’Est nord-américain',
  'America/Juneau': 'heure normale de l’Alaska',
  'America/Kentucky/Louisville': 'heure normale de l’Est nord-américain',
  'America/Kentucky/Monticello': 'heure normale de l’Est nord-américain',
  'America/Kralendijk': 'heure normale de l’Atlantique',
  'America/La_Paz': 'heure de Bolivie',
  'America/Lima': 'heure normale du Pérou',
  'America/Los_Angeles': 'heure normale du Pacifique nord-américain',
  'America/Lower_Princes': 'heure normale de l’Atlantique',
  'America/Maceio': 'heure normale de Brasilia',
  'America/Managua': 'heure normale du centre nord-américain',
  'America/Manaus': 'heure normale de l’Amazonie',
  'America/Marigot': 'heure normale de l’Atlantique',
  'America/Martinique': 'heure normale de l’Atlantique',
  'America/Matamoros': 'heure normale du centre nord-américain',
  'America/Mazatlan': 'heure normale du Pacifique mexicain',
  'America/Menominee': 'heure normale du centre nord-américain',
  'America/Merida': 'heure normale du centre nord-américain',
  'America/Metlakatla': 'heure normale de l’Alaska',
  'America/Mexico_City': 'heure normale du centre nord-américain',
  'America/Miquelon': 'heure normale de Saint-Pierre-et-Miquelon',
  'America/Moncton': 'heure normale de l’Atlantique',
  'America/Monterrey': 'heure normale du centre nord-américain',
  'America/Montevideo': 'heure normale de l’Uruguay',
  'America/Montserrat': 'heure normale de l’Atlantique',
  'America/Nassau': 'heure normale de l’Est nord-américain',
  'America/New_York': 'heure normale de l’Est nord-américain',
  'America/Nipigon': 'heure normale de l’Est nord-américain',
  'America/Nome': 'heure normale de l’Alaska',
  'America/Noronha': 'heure normale de Fernando de Noronha',
  'America/North_Dakota/Beulah': 'heure normale du centre nord-américain',
  'America/North_Dakota/Center': 'heure normale du centre nord-américain',
  'America/North_Dakota/New_Salem': 'heure normale du centre nord-américain',
  'America/Ojinaga': 'heure normale des Rocheuses',
  'America/Panama': 'heure normale de l’Est nord-américain',
  'America/Pangnirtung': 'heure normale de l’Est nord-américain',
  'America/Paramaribo': 'heure du Suriname',
  'America/Phoenix': 'heure normale des Rocheuses',
  'America/Port-au-Prince': 'heure normale de l’Est nord-américain',
  'America/Port_of_Spain': 'heure normale de l’Atlantique',
  'America/Porto_Velho': 'heure normale de l’Amazonie',
  'America/Puerto_Rico': 'heure normale de l’Atlantique',
  'America/Punta_Arenas': 'UTC−03:00',
  'America/Rainy_River': 'heure normale du centre nord-américain',
  'America/Rankin_Inlet': 'heure normale du centre nord-américain',
  'America/Recife': 'heure normale de Brasilia',
  'America/Regina': 'heure normale du centre nord-américain',
  'America/Resolute': 'heure normale du centre nord-américain',
  'America/Rio_Branco': 'heure normale de l’Acre',
  'America/Santarem': 'heure normale de Brasilia',
  'America/Santiago': 'heure normale du Chili',
  'America/Santo_Domingo': 'heure normale de l’Atlantique',
  'America/Sao_Paulo': 'heure normale de Brasilia',
  'America/Scoresbysund': 'heure normale de l’Est du Groenland',
  'America/Sitka': 'heure normale de l’Alaska',
  'America/St_Barthelemy': 'heure normale de l’Atlantique',
  'America/St_Johns': 'heure normale de Terre-Neuve',
  'America/St_Kitts': 'heure normale de l’Atlantique',
  'America/St_Lucia': 'heure normale de l’Atlantique',
  'America/St_Thomas': 'heure normale de l’Atlantique',
  'America/St_Vincent': 'heure normale de l’Atlantique',
  'America/Swift_Current': 'heure normale du centre nord-américain',
  'America/Tegucigalpa': 'heure normale du centre nord-américain',
  'America/Thule': 'heure normale de l’Atlantique',
  'America/Thunder_Bay': 'heure normale de l’Est nord-américain',
  'America/Tijuana': 'heure normale du Pacifique nord-américain',
  'America/Toronto': 'heure normale de l’Est nord-américain',
  'America/Tortola': 'heure normale de l’Atlantique',
  'America/Vancouver': 'heure normale du Pacifique nord-américain',
  'America/Whitehorse': 'heure normale du Pacifique nord-américain',
  'America/Winnipeg': 'heure normale du centre nord-américain',
  'America/Yakutat': 'heure normale de l’Alaska',
  'America/Yellowknife': 'heure normale des Rocheuses',
  'Antarctica/Casey': 'UTC+11:00',
  'Antarctica/Davis': 'heure de Davis',
  'Antarctica/DumontDUrville': 'heure de Dumont-d’Urville',
  'Antarctica/Macquarie': 'heure de l’île Macquarie',
  'Antarctica/Mawson': 'heure de Mawson',
  'Antarctica/McMurdo': 'heure normale de la Nouvelle-Zélande',
  'Antarctica/Palmer': 'UTC−03:00',
  'Antarctica/Rothera': 'heure de Rothera',
  'Antarctica/Syowa': 'heure de Syowa',
  'Antarctica/Troll': 'heure moyenne de Greenwich',
  'Antarctica/Vostok': 'heure de Vostok',
  'Arctic/Longyearbyen': 'heure normale d’Europe centrale',
  'Asia/Aden': 'heure normale de l’Arabie',
  'Asia/Almaty': 'heure de l’Est du Kazakhstan',
  'Asia/Amman': 'heure normale d’Europe de l’Est',
  'Asia/Anadyr': 'heure normale d’Anadyr',
  'Asia/Aqtau': 'heure de l’Ouest du Kazakhstan',
  'Asia/Aqtobe': 'heure de l’Ouest du Kazakhstan',
  'Asia/Ashgabat': 'heure normale du Turkménistan',
  'Asia/Atyrau': 'heure de l’Ouest du Kazakhstan',
  'Asia/Baghdad': 'heure normale de l’Arabie',
  'Asia/Bahrain': 'heure normale de l’Arabie',
  'Asia/Baku': 'heure normale de l’Azerbaïdjan',
  'Asia/Bangkok': 'heure d’Indochine',
  'Asia/Barnaul': 'UTC+07:00',
  'Asia/Beirut': 'heure normale d’Europe de l’Est',
  'Asia/Bishkek': 'heure du Kirghizistan',
  'Asia/Brunei': 'heure du Brunéi',
  'Asia/Chita': 'heure normale de Iakoutsk',
  'Asia/Choibalsan': 'heure normale de Choibalsan',
  'Asia/Colombo': 'heure de l’Inde',
  'Asia/Damascus': 'heure normale d’Europe de l’Est',
  'Asia/Dhaka': 'heure normale du Bangladesh',
  'Asia/Dili': 'heure du Timor oriental',
  'Asia/Dubai': 'heure du Golfe',
  'Asia/Dushanbe': 'heure du Tadjikistan',
  'Asia/Famagusta': 'UTC+02:00',
  'Asia/Gaza': 'heure normale d’Europe de l’Est',
  'Asia/Hebron': 'heure normale d’Europe de l’Est',
  'Asia/Ho_Chi_Minh': 'heure d’Indochine',
  'Asia/Hong_Kong': 'heure normale de Hong Kong',
  'Asia/Hovd': 'heure normale de Hovd',
  'Asia/Irkutsk': 'heure normale d’Irkoutsk',
  'Asia/Jakarta': 'heure de l’Ouest indonésien',
  'Asia/Jayapura': 'heure de l’Est indonésien',
  'Asia/Jerusalem': 'heure normale d’Israël',
  'Asia/Kabul': 'heure de l’Afghanistan',
  'Asia/Kamchatka': 'heure normale de Petropavlovsk-Kamchatski',
  'Asia/Karachi': 'heure normale du Pakistan',
  'Asia/Kathmandu': 'heure du Népal',
  'Asia/Khandyga': 'heure normale de Iakoutsk',
  'Asia/Kolkata': 'heure de l’Inde',
  'Asia/Krasnoyarsk': 'heure normale de Krasnoïarsk',
  'Asia/Kuala_Lumpur': 'heure de la Malaisie',
  'Asia/Kuching': 'heure de la Malaisie',
  'Asia/Kuwait': 'heure normale de l’Arabie',
  'Asia/Macau': 'heure normale de la Chine',
  'Asia/Magadan': 'heure normale de Magadan',
  'Asia/Makassar': 'heure du Centre indonésien',
  'Asia/Manila': 'heure normale des Philippines',
  'Asia/Muscat': 'heure du Golfe',
  'Asia/Nicosia': 'heure normale d’Europe de l’Est',
  'Asia/Novokuznetsk': 'heure normale de Krasnoïarsk',
  'Asia/Novosibirsk': 'heure normale de Novossibirsk',
  'Asia/Omsk': 'heure normale de Omsk',
  'Asia/Oral': 'heure de l’Ouest du Kazakhstan',
  'Asia/Phnom_Penh': 'heure d’Indochine',
  'Asia/Pontianak': 'heure de l’Ouest indonésien',
  'Asia/Pyongyang': 'heure de Pyongyang',
  'Asia/Qatar': 'heure normale de l’Arabie',
  'Asia/Qyzylorda': 'heure de l’Est du Kazakhstan',
  'Asia/Riyadh': 'heure normale de l’Arabie',
  'Asia/Sakhalin': 'heure normale de Sakhaline',
  'Asia/Samarkand': 'heure normale de l’Ouzbékistan',
  'Asia/Seoul': 'heure normale de la Corée',
  'Asia/Shanghai': 'heure normale de la Chine',
  'Asia/Singapore': 'heure de Singapour',
  'Asia/Srednekolymsk': 'UTC+11:00',
  'Asia/Taipei': 'heure normale de Taipei',
  'Asia/Tashkent': 'heure normale de l’Ouzbékistan',
  'Asia/Tbilisi': 'heure normale de la Géorgie',
  'Asia/Tehran': 'heure normale d’Iran',
  'Asia/Thimphu': 'heure du Bhoutan',
  'Asia/Tokyo': 'heure normale du Japon',
  'Asia/Tomsk': 'UTC+07:00',
  'Asia/Ulaanbaatar': 'heure normale d’Oulan-Bator',
  'Asia/Urumqi': 'UTC+06:00',
  'Asia/Ust-Nera': 'heure normale de Vladivostok',
  'Asia/Vientiane': 'heure d’Indochine',
  'Asia/Vladivostok': 'heure normale de Vladivostok',
  'Asia/Yakutsk': 'heure normale de Iakoutsk',
  'Asia/Yangon': 'heure du Myanmar',
  'Asia/Yekaterinburg': 'heure normale d’Ekaterinbourg',
  'Asia/Yerevan': 'heure normale de l’Arménie',
  'Atlantic/Azores': 'heure normale des Açores',
  'Atlantic/Bermuda': 'heure normale de l’Atlantique',
  'Atlantic/Canary': 'heure normale d’Europe de l’Ouest',
  'Atlantic/Cape_Verde': 'heure normale du Cap-Vert',
  'Atlantic/Faroe': 'heure normale d’Europe de l’Ouest',
  'Atlantic/Madeira': 'heure normale d’Europe de l’Ouest',
  'Atlantic/Reykjavik': 'heure moyenne de Greenwich',
  'Atlantic/South_Georgia': 'heure de Géorgie du Sud',
  'Atlantic/St_Helena': 'heure moyenne de Greenwich',
  'Atlantic/Stanley': 'heure normale des îles Malouines',
  'Australia/Adelaide': 'heure normale du centre de l’Australie',
  'Australia/Brisbane': 'heure normale de l’Est de l’Australie',
  'Australia/Broken_Hill': 'heure normale du centre de l’Australie',
  'Australia/Currie': 'heure normale de l’Est de l’Australie',
  'Australia/Darwin': 'heure normale du centre de l’Australie',
  'Australia/Eucla': 'heure normale du centre-ouest de l’Australie',
  'Australia/Hobart': 'heure normale de l’Est de l’Australie',
  'Australia/Lindeman': 'heure normale de l’Est de l’Australie',
  'Australia/Lord_Howe': 'heure normale de Lord Howe',
  'Australia/Melbourne': 'heure normale de l’Est de l’Australie',
  'Australia/Perth': 'heure normale de l’Ouest de l’Australie',
  'Australia/Sydney': 'heure normale de l’Est de l’Australie',
  'Europe/Amsterdam': 'heure normale d’Europe centrale',
  'Europe/Andorra': 'heure normale d’Europe centrale',
  'Europe/Astrakhan': 'UTC+04:00',
  'Europe/Athens': 'heure normale d’Europe de l’Est',
  'Europe/Belgrade': 'heure normale d’Europe centrale',
  'Europe/Berlin': 'heure normale d’Europe centrale',
  'Europe/Bratislava': 'heure normale d’Europe centrale',
  'Europe/Brussels': 'heure normale d’Europe centrale',
  'Europe/Bucharest': 'heure normale d’Europe de l’Est',
  'Europe/Budapest': 'heure normale d’Europe centrale',
  'Europe/Busingen': 'heure normale d’Europe centrale',
  'Europe/Chisinau': 'heure normale d’Europe de l’Est',
  'Europe/Copenhagen': 'heure normale d’Europe centrale',
  'Europe/Dublin': 'heure moyenne de Greenwich',
  'Europe/Gibraltar': 'heure normale d’Europe centrale',
  'Europe/Guernsey': 'heure moyenne de Greenwich',
  'Europe/Helsinki': 'heure normale d’Europe de l’Est',
  'Europe/Isle_of_Man': 'heure moyenne de Greenwich',
  'Europe/Istanbul': 'UTC+03:00',
  'Europe/Jersey': 'heure moyenne de Greenwich',
  'Europe/Kaliningrad': 'heure normale d’Europe de l’Est',
  'Europe/Kiev': 'heure normale d’Europe de l’Est',
  'Europe/Kirov': 'UTC+03:00',
  'Europe/Lisbon': 'heure normale d’Europe de l’Ouest',
  'Europe/Ljubljana': 'heure normale d’Europe centrale',
  'Europe/London': 'heure moyenne de Greenwich',
  'Europe/Luxembourg': 'heure normale d’Europe centrale',
  'Europe/Madrid': 'heure normale d’Europe centrale',
  'Europe/Malta': 'heure normale d’Europe centrale',
  'Europe/Mariehamn': 'heure normale d’Europe de l’Est',
  'Europe/Minsk': 'heure normale de Moscou',
  'Europe/Monaco': 'heure normale d’Europe centrale',
  'Europe/Moscow': 'heure normale de Moscou',
  'Europe/Oslo': 'heure normale d’Europe centrale',
  'Europe/Paris': 'heure normale d’Europe centrale',
  'Europe/Podgorica': 'heure normale d’Europe centrale',
  'Europe/Prague': 'heure normale d’Europe centrale',
  'Europe/Riga': 'heure normale d’Europe de l’Est',
  'Europe/Rome': 'heure normale d’Europe centrale',
  'Europe/Samara': 'heure normale de Samara',
  'Europe/San_Marino': 'heure normale d’Europe centrale',
  'Europe/Sarajevo': 'heure normale d’Europe centrale',
  'Europe/Saratov': 'UTC+04:00',
  'Europe/Simferopol': 'heure normale de Moscou',
  'Europe/Skopje': 'heure normale d’Europe centrale',
  'Europe/Sofia': 'heure normale d’Europe de l’Est',
  'Europe/Stockholm': 'heure normale d’Europe centrale',
  'Europe/Tallinn': 'heure normale d’Europe de l’Est',
  'Europe/Tirane': 'heure normale d’Europe centrale',
  'Europe/Ulyanovsk': 'UTC+04:00',
  'Europe/Uzhgorod': 'heure normale d’Europe de l’Est',
  'Europe/Vaduz': 'heure normale d’Europe centrale',
  'Europe/Vatican': 'heure normale d’Europe centrale',
  'Europe/Vienna': 'heure normale d’Europe centrale',
  'Europe/Vilnius': 'heure normale d’Europe de l’Est',
  'Europe/Volgograd': 'heure normale de Moscou',
  'Europe/Warsaw': 'heure normale d’Europe centrale',
  'Europe/Zagreb': 'heure normale d’Europe centrale',
  'Europe/Zaporozhye': 'heure normale d’Europe de l’Est',
  'Europe/Zurich': 'heure normale d’Europe centrale',
  'Indian/Antananarivo': 'heure normale d’Afrique de l’Est',
  'Indian/Chagos': 'heure de l’Océan Indien',
  'Indian/Christmas': 'heure de l’île Christmas',
  'Indian/Cocos': 'heure des îles Cocos',
  'Indian/Comoro': 'heure normale d’Afrique de l’Est',
  'Indian/Kerguelen': 'heure des Terres australes et antarctiques françaises',
  'Indian/Mahe': 'heure des Seychelles',
  'Indian/Maldives': 'heure des Maldives',
  'Indian/Mauritius': 'heure normale de Maurice',
  'Indian/Mayotte': 'heure normale d’Afrique de l’Est',
  'Indian/Reunion': 'heure de La Réunion',
  'Pacific/Apia': 'heure normale d’Apia',
  'Pacific/Auckland': 'heure normale de la Nouvelle-Zélande',
  'Pacific/Bougainville': 'UTC+11:00',
  'Pacific/Chatham': 'heure normale des îles Chatham',
  'Pacific/Chuuk': 'heure de Chuuk',
  'Pacific/Easter': 'heure normale de l’île de Pâques',
  'Pacific/Efate': 'heure normale du Vanuatu',
  'Pacific/Enderbury': 'heure des îles Phoenix',
  'Pacific/Fakaofo': 'heure de Tokelau',
  'Pacific/Fiji': 'heure normale des îles Fidji',
  'Pacific/Funafuti': 'heure des Tuvalu',
  'Pacific/Galapagos': 'heure des îles Galápagos',
  'Pacific/Gambier': 'heure des îles Gambier',
  'Pacific/Guadalcanal': 'heure des îles Salomon',
  'Pacific/Guam': 'heure des Chamorro',
  'Pacific/Honolulu': 'heure normale d’Hawaii - Aléoutiennes',
  'Pacific/Kiritimati': 'heure des îles de la Ligne',
  'Pacific/Kosrae': 'heure de Kosrae',
  'Pacific/Kwajalein': 'heure des îles Marshall',
  'Pacific/Majuro': 'heure des îles Marshall',
  'Pacific/Marquesas': 'heure des îles Marquises',
  'Pacific/Midway': 'heure normale des Samoa',
  'Pacific/Nauru': 'heure de Nauru',
  'Pacific/Niue': 'heure de Nioué',
  'Pacific/Norfolk': 'heure de l’île Norfolk',
  'Pacific/Noumea': 'heure normale de la Nouvelle-Calédonie',
  'Pacific/Pago_Pago': 'heure normale des Samoa',
  'Pacific/Palau': 'heure des Palaos',
  'Pacific/Pitcairn': 'heure des îles Pitcairn',
  'Pacific/Pohnpei': 'heure de l’île de Pohnpei',
  'Pacific/Port_Moresby': 'heure de la Papouasie-Nouvelle-Guinée',
  'Pacific/Rarotonga': 'heure normale des îles Cook',
  'Pacific/Saipan': 'heure des Chamorro',
  'Pacific/Tahiti': 'heure de Tahiti',
  'Pacific/Tarawa': 'heure des îles Gilbert',
  'Pacific/Tongatapu': 'heure normale des Tonga',
  'Pacific/Wake': 'heure de l’île Wake',
  'Pacific/Wallis': 'heure de Wallis-et-Futuna',
  UTC: 'Temps universel coordonné',
};
