module.exports = {
  'Africa/Abidjan': 'Ora del meridiano di Greenwich',
  'Africa/Accra': 'Ora del meridiano di Greenwich',
  'Africa/Addis_Ababa': 'Ora dell’Africa orientale',
  'Africa/Algiers': 'Ora standard dell’Europa centrale',
  'Africa/Asmara': 'Ora dell’Africa orientale',
  'Africa/Bamako': 'Ora del meridiano di Greenwich',
  'Africa/Bangui': 'Ora standard dell’Africa occidentale',
  'Africa/Banjul': 'Ora del meridiano di Greenwich',
  'Africa/Bissau': 'Ora del meridiano di Greenwich',
  'Africa/Blantyre': 'Ora dell’Africa centrale',
  'Africa/Brazzaville': 'Ora standard dell’Africa occidentale',
  'Africa/Bujumbura': 'Ora dell’Africa centrale',
  'Africa/Cairo': 'Ora standard dell’Europa orientale',
  'Africa/Casablanca': 'Ora standard dell’Europa occidentale',
  'Africa/Ceuta': 'Ora standard dell’Europa centrale',
  'Africa/Conakry': 'Ora del meridiano di Greenwich',
  'Africa/Dakar': 'Ora del meridiano di Greenwich',
  'Africa/Dar_es_Salaam': 'Ora dell’Africa orientale',
  'Africa/Djibouti': 'Ora dell’Africa orientale',
  'Africa/Douala': 'Ora standard dell’Africa occidentale',
  'Africa/El_Aaiun': 'Ora standard dell’Europa occidentale',
  'Africa/Freetown': 'Ora del meridiano di Greenwich',
  'Africa/Gaborone': 'Ora dell’Africa centrale',
  'Africa/Harare': 'Ora dell’Africa centrale',
  'Africa/Johannesburg': 'Ora dell’Africa meridionale',
  'Africa/Juba': 'Ora dell’Africa orientale',
  'Africa/Kampala': 'Ora dell’Africa orientale',
  'Africa/Khartoum': 'Ora dell’Africa centrale',
  'Africa/Kigali': 'Ora dell’Africa centrale',
  'Africa/Kinshasa': 'Ora standard dell’Africa occidentale',
  'Africa/Lagos': 'Ora standard dell’Africa occidentale',
  'Africa/Libreville': 'Ora standard dell’Africa occidentale',
  'Africa/Lome': 'Ora del meridiano di Greenwich',
  'Africa/Luanda': 'Ora standard dell’Africa occidentale',
  'Africa/Lubumbashi': 'Ora dell’Africa centrale',
  'Africa/Lusaka': 'Ora dell’Africa centrale',
  'Africa/Malabo': 'Ora standard dell’Africa occidentale',
  'Africa/Maputo': 'Ora dell’Africa centrale',
  'Africa/Maseru': 'Ora dell’Africa meridionale',
  'Africa/Mbabane': 'Ora dell’Africa meridionale',
  'Africa/Mogadishu': 'Ora dell’Africa orientale',
  'Africa/Monrovia': 'Ora del meridiano di Greenwich',
  'Africa/Nairobi': 'Ora dell’Africa orientale',
  'Africa/Ndjamena': 'Ora standard dell’Africa occidentale',
  'Africa/Niamey': 'Ora standard dell’Africa occidentale',
  'Africa/Nouakchott': 'Ora del meridiano di Greenwich',
  'Africa/Ouagadougou': 'Ora del meridiano di Greenwich',
  'Africa/Porto-Novo': 'Ora standard dell’Africa occidentale',
  'Africa/Sao_Tome': 'Ora del meridiano di Greenwich',
  'Africa/Tripoli': 'Ora standard dell’Europa orientale',
  'Africa/Tunis': 'Ora standard dell’Europa centrale',
  'Africa/Windhoek': 'Ora dell’Africa centrale',
  'America/Adak': 'Ora standard delle Isole Hawaii-Aleutine',
  'America/Anchorage': 'Ora standard dell’Alaska',
  'America/Anguilla': 'Ora standard dell’Atlantico',
  'America/Antigua': 'Ora standard dell’Atlantico',
  'America/Araguaina': 'Ora standard di Brasilia',
  'America/Argentina/Buenos_Aires': 'Ora standard dell’Argentina',
  'America/Argentina/Catamarca': 'Ora standard dell’Argentina',
  'America/Argentina/Cordoba': 'Ora standard dell’Argentina',
  'America/Argentina/Jujuy': 'Ora standard dell’Argentina',
  'America/Argentina/La_Rioja': 'Ora standard dell’Argentina',
  'America/Argentina/Mendoza': 'Ora standard dell’Argentina',
  'America/Argentina/Rio_Gallegos': 'Ora standard dell’Argentina',
  'America/Argentina/Salta': 'Ora standard dell’Argentina',
  'America/Argentina/San_Juan': 'Ora standard dell’Argentina',
  'America/Argentina/San_Luis': 'Ora standard dell’Argentina occidentale',
  'America/Argentina/Tucuman': 'Ora standard dell’Argentina',
  'America/Argentina/Ushuaia': 'Ora standard dell’Argentina',
  'America/Aruba': 'Ora standard dell’Atlantico',
  'America/Asuncion': 'Ora standard del Paraguay',
  'America/Atikokan': 'Ora standard orientale USA',
  'America/Bahia': 'Ora standard di Brasilia',
  'America/Bahia_Banderas': 'Ora standard centrale USA',
  'America/Barbados': 'Ora standard dell’Atlantico',
  'America/Belem': 'Ora standard di Brasilia',
  'America/Belize': 'Ora standard centrale USA',
  'America/Blanc-Sablon': 'Ora standard dell’Atlantico',
  'America/Boa_Vista': 'Ora standard dell’Amazzonia',
  'America/Bogota': 'Ora standard della Colombia',
  'America/Boise': 'Ora standard Montagne Rocciose USA',
  'America/Cambridge_Bay': 'Ora standard Montagne Rocciose USA',
  'America/Campo_Grande': 'Ora standard dell’Amazzonia',
  'America/Cancun': 'Ora standard orientale USA',
  'America/Caracas': 'Ora del Venezuela',
  'America/Cayenne': 'Ora della Guiana francese',
  'America/Cayman': 'Ora standard orientale USA',
  'America/Chicago': 'Ora standard centrale USA',
  'America/Chihuahua': 'Ora standard del Pacifico (Messico)',
  'America/Costa_Rica': 'Ora standard centrale USA',
  'America/Creston': 'Ora standard Montagne Rocciose USA',
  'America/Cuiaba': 'Ora standard dell’Amazzonia',
  'America/Curacao': 'Ora standard dell’Atlantico',
  'America/Danmarkshavn': 'Ora del meridiano di Greenwich',
  'America/Dawson': 'Ora standard del Pacifico USA',
  'America/Dawson_Creek': 'Ora standard Montagne Rocciose USA',
  'America/Denver': 'Ora standard Montagne Rocciose USA',
  'America/Detroit': 'Ora standard orientale USA',
  'America/Dominica': 'Ora standard dell’Atlantico',
  'America/Edmonton': 'Ora standard Montagne Rocciose USA',
  'America/Eirunepe': 'GMT-05:00',
  'America/El_Salvador': 'Ora standard centrale USA',
  'America/Fort_Nelson': 'Ora standard Montagne Rocciose USA',
  'America/Fortaleza': 'Ora standard di Brasilia',
  'America/Glace_Bay': 'Ora standard dell’Atlantico',
  'America/Godthab': 'Ora standard della Groenlandia occidentale',
  'America/Goose_Bay': 'Ora standard dell’Atlantico',
  'America/Grand_Turk': 'Ora standard orientale USA',
  'America/Grenada': 'Ora standard dell’Atlantico',
  'America/Guadeloupe': 'Ora standard dell’Atlantico',
  'America/Guatemala': 'Ora standard centrale USA',
  'America/Guayaquil': 'Ora dell’Ecuador',
  'America/Guyana': 'Ora della Guyana',
  'America/Halifax': 'Ora standard dell’Atlantico',
  'America/Havana': 'Ora standard di Cuba',
  'America/Hermosillo': 'Ora standard del Pacifico (Messico)',
  'America/Indiana/Indianapolis': 'Ora standard orientale USA',
  'America/Indiana/Knox': 'Ora standard centrale USA',
  'America/Indiana/Marengo': 'Ora standard orientale USA',
  'America/Indiana/Petersburg': 'Ora standard orientale USA',
  'America/Indiana/Tell_City': 'Ora standard centrale USA',
  'America/Indiana/Vevay': 'Ora standard orientale USA',
  'America/Indiana/Vincennes': 'Ora standard orientale USA',
  'America/Indiana/Winamac': 'Ora standard orientale USA',
  'America/Inuvik': 'Ora standard Montagne Rocciose USA',
  'America/Iqaluit': 'Ora standard orientale USA',
  'America/Jamaica': 'Ora standard orientale USA',
  'America/Juneau': 'Ora standard dell’Alaska',
  'America/Kentucky/Louisville': 'Ora standard orientale USA',
  'America/Kentucky/Monticello': 'Ora standard orientale USA',
  'America/Kralendijk': 'Ora standard dell’Atlantico',
  'America/La_Paz': 'Ora della Bolivia',
  'America/Lima': 'Ora standard del Perù',
  'America/Los_Angeles': 'Ora standard del Pacifico USA',
  'America/Lower_Princes': 'Ora standard dell’Atlantico',
  'America/Maceio': 'Ora standard di Brasilia',
  'America/Managua': 'Ora standard centrale USA',
  'America/Manaus': 'Ora standard dell’Amazzonia',
  'America/Marigot': 'Ora standard dell’Atlantico',
  'America/Martinique': 'Ora standard dell’Atlantico',
  'America/Matamoros': 'Ora standard centrale USA',
  'America/Mazatlan': 'Ora standard del Pacifico (Messico)',
  'America/Menominee': 'Ora standard centrale USA',
  'America/Merida': 'Ora standard centrale USA',
  'America/Metlakatla': 'Ora standard dell’Alaska',
  'America/Mexico_City': 'Ora standard centrale USA',
  'America/Miquelon': 'Ora standard di Saint-Pierre e Miquelon',
  'America/Moncton': 'Ora standard dell’Atlantico',
  'America/Monterrey': 'Ora standard centrale USA',
  'America/Montevideo': 'Ora standard dell’Uruguay',
  'America/Montserrat': 'Ora standard dell’Atlantico',
  'America/Nassau': 'Ora standard orientale USA',
  'America/New_York': 'Ora standard orientale USA',
  'America/Nipigon': 'Ora standard orientale USA',
  'America/Nome': 'Ora standard dell’Alaska',
  'America/Noronha': 'Ora standard di Fernando de Noronha',
  'America/North_Dakota/Beulah': 'Ora standard centrale USA',
  'America/North_Dakota/Center': 'Ora standard centrale USA',
  'America/North_Dakota/New_Salem': 'Ora standard centrale USA',
  'America/Ojinaga': 'Ora standard Montagne Rocciose USA',
  'America/Panama': 'Ora standard orientale USA',
  'America/Pangnirtung': 'Ora standard orientale USA',
  'America/Paramaribo': 'Ora del Suriname',
  'America/Phoenix': 'Ora standard Montagne Rocciose USA',
  'America/Port-au-Prince': 'Ora standard orientale USA',
  'America/Port_of_Spain': 'Ora standard dell’Atlantico',
  'America/Porto_Velho': 'Ora standard dell’Amazzonia',
  'America/Puerto_Rico': 'Ora standard dell’Atlantico',
  'America/Punta_Arenas': 'GMT-03:00',
  'America/Rainy_River': 'Ora standard centrale USA',
  'America/Rankin_Inlet': 'Ora standard centrale USA',
  'America/Recife': 'Ora standard di Brasilia',
  'America/Regina': 'Ora standard centrale USA',
  'America/Resolute': 'Ora standard centrale USA',
  'America/Rio_Branco': 'GMT-05:00',
  'America/Santarem': 'Ora standard di Brasilia',
  'America/Santiago': 'Ora standard del Cile',
  'America/Santo_Domingo': 'Ora standard dell’Atlantico',
  'America/Sao_Paulo': 'Ora standard di Brasilia',
  'America/Scoresbysund': 'Ora standard della Groenlandia orientale',
  'America/Sitka': 'Ora standard dell’Alaska',
  'America/St_Barthelemy': 'Ora standard dell’Atlantico',
  'America/St_Johns': 'Ora standard di Terranova',
  'America/St_Kitts': 'Ora standard dell’Atlantico',
  'America/St_Lucia': 'Ora standard dell’Atlantico',
  'America/St_Thomas': 'Ora standard dell’Atlantico',
  'America/St_Vincent': 'Ora standard dell’Atlantico',
  'America/Swift_Current': 'Ora standard centrale USA',
  'America/Tegucigalpa': 'Ora standard centrale USA',
  'America/Thule': 'Ora standard dell’Atlantico',
  'America/Thunder_Bay': 'Ora standard orientale USA',
  'America/Tijuana': 'Ora standard del Pacifico USA',
  'America/Toronto': 'Ora standard orientale USA',
  'America/Tortola': 'Ora standard dell’Atlantico',
  'America/Vancouver': 'Ora standard del Pacifico USA',
  'America/Whitehorse': 'Ora standard del Pacifico USA',
  'America/Winnipeg': 'Ora standard centrale USA',
  'America/Yakutat': 'Ora standard dell’Alaska',
  'America/Yellowknife': 'Ora standard Montagne Rocciose USA',
  'Antarctica/Casey': 'GMT+11:00',
  'Antarctica/Davis': 'Ora di Davis',
  'Antarctica/DumontDUrville': 'Ora di Dumont-d’Urville',
  'Antarctica/Macquarie': 'Ora dell’Isola Macquarie',
  'Antarctica/Mawson': 'Ora di Mawson',
  'Antarctica/McMurdo': 'Ora standard della Nuova Zelanda',
  'Antarctica/Palmer': 'GMT-03:00',
  'Antarctica/Rothera': 'Ora di Rothera',
  'Antarctica/Syowa': 'Ora di Syowa',
  'Antarctica/Troll': 'Ora del meridiano di Greenwich',
  'Antarctica/Vostok': 'Ora di Vostok',
  'Arctic/Longyearbyen': 'Ora standard dell’Europa centrale',
  'Asia/Aden': 'Ora standard araba',
  'Asia/Almaty': 'Ora del Kazakistan orientale',
  'Asia/Amman': 'Ora standard dell’Europa orientale',
  'Asia/Anadyr': 'Ora standard di Anadyr',
  'Asia/Aqtau': 'Ora del Kazakistan occidentale',
  'Asia/Aqtobe': 'Ora del Kazakistan occidentale',
  'Asia/Ashgabat': 'Ora standard del Turkmenistan',
  'Asia/Atyrau': 'Ora del Kazakistan occidentale',
  'Asia/Baghdad': 'Ora standard araba',
  'Asia/Bahrain': 'Ora standard araba',
  'Asia/Baku': 'Ora standard dell’Azerbaigian',
  'Asia/Bangkok': 'Ora dell’Indocina',
  'Asia/Barnaul': 'GMT+07:00',
  'Asia/Beirut': 'Ora standard dell’Europa orientale',
  'Asia/Bishkek': 'Ora del Kirghizistan',
  'Asia/Brunei': 'Ora del Brunei Darussalam',
  'Asia/Chita': 'Ora standard di Yakutsk',
  'Asia/Choibalsan': 'Ora standard di Choibalsan',
  'Asia/Colombo': 'Ora standard dell’India',
  'Asia/Damascus': 'Ora standard dell’Europa orientale',
  'Asia/Dhaka': 'Ora standard del Bangladesh',
  'Asia/Dili': 'Ora di Timor Est',
  'Asia/Dubai': 'Ora del Golfo',
  'Asia/Dushanbe': 'Ora del Tagikistan',
  'Asia/Famagusta': 'GMT+02:00',
  'Asia/Gaza': 'Ora standard dell’Europa orientale',
  'Asia/Hebron': 'Ora standard dell’Europa orientale',
  'Asia/Ho_Chi_Minh': 'Ora dell’Indocina',
  'Asia/Hong_Kong': 'Ora standard di Hong Kong',
  'Asia/Hovd': 'Ora standard di Hovd',
  'Asia/Irkutsk': 'Ora standard di Irkutsk',
  'Asia/Jakarta': 'Ora dell’Indonesia occidentale',
  'Asia/Jayapura': 'Ora dell’Indonesia orientale',
  'Asia/Jerusalem': 'Ora standard di Israele',
  'Asia/Kabul': 'Ora dell’Afghanistan',
  'Asia/Kamchatka': 'Ora standard di Petropavlovsk-Kamchatski',
  'Asia/Karachi': 'Ora standard del Pakistan',
  'Asia/Kathmandu': 'Ora del Nepal',
  'Asia/Khandyga': 'Ora standard di Yakutsk',
  'Asia/Kolkata': 'Ora standard dell’India',
  'Asia/Krasnoyarsk': 'Ora standard di Krasnoyarsk',
  'Asia/Kuala_Lumpur': 'Ora della Malesia',
  'Asia/Kuching': 'Ora della Malesia',
  'Asia/Kuwait': 'Ora standard araba',
  'Asia/Macau': 'Ora standard della Cina',
  'Asia/Magadan': 'Ora standard di Magadan',
  'Asia/Makassar': 'Ora dell’Indonesia centrale',
  'Asia/Manila': 'Ora standard delle Filippine',
  'Asia/Muscat': 'Ora del Golfo',
  'Asia/Nicosia': 'Ora standard dell’Europa orientale',
  'Asia/Novokuznetsk': 'Ora standard di Krasnoyarsk',
  'Asia/Novosibirsk': 'Ora standard di Novosibirsk',
  'Asia/Omsk': 'Ora standard di Omsk',
  'Asia/Oral': 'Ora del Kazakistan occidentale',
  'Asia/Phnom_Penh': 'Ora dell’Indocina',
  'Asia/Pontianak': 'Ora dell’Indonesia occidentale',
  'Asia/Pyongyang': 'Ora di Pyongyang',
  'Asia/Qatar': 'Ora standard araba',
  'Asia/Qyzylorda': 'Ora del Kazakistan orientale',
  'Asia/Riyadh': 'Ora standard araba',
  'Asia/Sakhalin': 'Ora standard di Sakhalin',
  'Asia/Samarkand': 'Ora standard dell’Uzbekistan',
  'Asia/Seoul': 'Ora standard coreana',
  'Asia/Shanghai': 'Ora standard della Cina',
  'Asia/Singapore': 'Ora di Singapore',
  'Asia/Srednekolymsk': 'GMT+11:00',
  'Asia/Taipei': 'Ora standard di Taipei',
  'Asia/Tashkent': 'Ora standard dell’Uzbekistan',
  'Asia/Tbilisi': 'Ora standard della Georgia',
  'Asia/Tehran': 'Ora standard dell’Iran',
  'Asia/Thimphu': 'Ora del Bhutan',
  'Asia/Tokyo': 'Ora standard del Giappone',
  'Asia/Tomsk': 'GMT+07:00',
  'Asia/Ulaanbaatar': 'Ora standard di Ulan Bator',
  'Asia/Urumqi': 'GMT+06:00',
  'Asia/Ust-Nera': 'Ora standard di Vladivostok',
  'Asia/Vientiane': 'Ora dell’Indocina',
  'Asia/Vladivostok': 'Ora standard di Vladivostok',
  'Asia/Yakutsk': 'Ora standard di Yakutsk',
  'Asia/Yangon': 'Ora della Birmania',
  'Asia/Yekaterinburg': 'Ora standard di Ekaterinburg',
  'Asia/Yerevan': 'Ora standard dell’Armenia',
  'Atlantic/Azores': 'Ora standard delle Azzorre',
  'Atlantic/Bermuda': 'Ora standard dell’Atlantico',
  'Atlantic/Canary': 'Ora standard dell’Europa occidentale',
  'Atlantic/Cape_Verde': 'Ora standard di Capo Verde',
  'Atlantic/Faroe': 'Ora standard dell’Europa occidentale',
  'Atlantic/Madeira': 'Ora standard dell’Europa occidentale',
  'Atlantic/Reykjavik': 'Ora del meridiano di Greenwich',
  'Atlantic/South_Georgia': 'Ora della Georgia del Sud',
  'Atlantic/St_Helena': 'Ora del meridiano di Greenwich',
  'Atlantic/Stanley': 'Ora standard delle Isole Falkland',
  'Australia/Adelaide': 'Ora standard dell’Australia centrale',
  'Australia/Brisbane': 'Ora standard dell’Australia orientale',
  'Australia/Broken_Hill': 'Ora standard dell’Australia centrale',
  'Australia/Currie': 'Ora standard dell’Australia orientale',
  'Australia/Darwin': 'Ora standard dell’Australia centrale',
  'Australia/Eucla': 'Ora standard dell’Australia centroccidentale',
  'Australia/Hobart': 'Ora standard dell’Australia orientale',
  'Australia/Lindeman': 'Ora standard dell’Australia orientale',
  'Australia/Lord_Howe': 'Ora standard di Lord Howe',
  'Australia/Melbourne': 'Ora standard dell’Australia orientale',
  'Australia/Perth': 'Ora standard dell’Australia occidentale',
  'Australia/Sydney': 'Ora standard dell’Australia orientale',
  'Europe/Amsterdam': 'Ora standard dell’Europa centrale',
  'Europe/Andorra': 'Ora standard dell’Europa centrale',
  'Europe/Astrakhan': 'GMT+04:00',
  'Europe/Athens': 'Ora standard dell’Europa orientale',
  'Europe/Belgrade': 'Ora standard dell’Europa centrale',
  'Europe/Berlin': 'Ora standard dell’Europa centrale',
  'Europe/Bratislava': 'Ora standard dell’Europa centrale',
  'Europe/Brussels': 'Ora standard dell’Europa centrale',
  'Europe/Bucharest': 'Ora standard dell’Europa orientale',
  'Europe/Budapest': 'Ora standard dell’Europa centrale',
  'Europe/Busingen': 'Ora standard dell’Europa centrale',
  'Europe/Chisinau': 'Ora standard dell’Europa orientale',
  'Europe/Copenhagen': 'Ora standard dell’Europa centrale',
  'Europe/Dublin': 'Ora del meridiano di Greenwich',
  'Europe/Gibraltar': 'Ora standard dell’Europa centrale',
  'Europe/Guernsey': 'Ora del meridiano di Greenwich',
  'Europe/Helsinki': 'Ora standard dell’Europa orientale',
  'Europe/Isle_of_Man': 'Ora del meridiano di Greenwich',
  'Europe/Istanbul': 'GMT+03:00',
  'Europe/Jersey': 'Ora del meridiano di Greenwich',
  'Europe/Kaliningrad': 'Ora standard dell’Europa orientale',
  'Europe/Kiev': 'Ora standard dell’Europa orientale',
  'Europe/Kirov': 'GMT+03:00',
  'Europe/Lisbon': 'Ora standard dell’Europa occidentale',
  'Europe/Ljubljana': 'Ora standard dell’Europa centrale',
  'Europe/London': 'Ora del meridiano di Greenwich',
  'Europe/Luxembourg': 'Ora standard dell’Europa centrale',
  'Europe/Madrid': 'Ora standard dell’Europa centrale',
  'Europe/Malta': 'Ora standard dell’Europa centrale',
  'Europe/Mariehamn': 'Ora standard dell’Europa orientale',
  'Europe/Minsk': 'Ora standard di Mosca',
  'Europe/Monaco': 'Ora standard dell’Europa centrale',
  'Europe/Moscow': 'Ora standard di Mosca',
  'Europe/Oslo': 'Ora standard dell’Europa centrale',
  'Europe/Paris': 'Ora standard dell’Europa centrale',
  'Europe/Podgorica': 'Ora standard dell’Europa centrale',
  'Europe/Prague': 'Ora standard dell’Europa centrale',
  'Europe/Riga': 'Ora standard dell’Europa orientale',
  'Europe/Rome': 'Ora standard dell’Europa centrale',
  'Europe/Samara': 'Ora standard di Samara',
  'Europe/San_Marino': 'Ora standard dell’Europa centrale',
  'Europe/Sarajevo': 'Ora standard dell’Europa centrale',
  'Europe/Saratov': 'GMT+04:00',
  'Europe/Simferopol': 'Ora standard di Mosca',
  'Europe/Skopje': 'Ora standard dell’Europa centrale',
  'Europe/Sofia': 'Ora standard dell’Europa orientale',
  'Europe/Stockholm': 'Ora standard dell’Europa centrale',
  'Europe/Tallinn': 'Ora standard dell’Europa orientale',
  'Europe/Tirane': 'Ora standard dell’Europa centrale',
  'Europe/Ulyanovsk': 'GMT+04:00',
  'Europe/Uzhgorod': 'Ora standard dell’Europa orientale',
  'Europe/Vaduz': 'Ora standard dell’Europa centrale',
  'Europe/Vatican': 'Ora standard dell’Europa centrale',
  'Europe/Vienna': 'Ora standard dell’Europa centrale',
  'Europe/Vilnius': 'Ora standard dell’Europa orientale',
  'Europe/Volgograd': 'Ora standard di Mosca',
  'Europe/Warsaw': 'Ora standard dell’Europa centrale',
  'Europe/Zagreb': 'Ora standard dell’Europa centrale',
  'Europe/Zaporozhye': 'Ora standard dell’Europa orientale',
  'Europe/Zurich': 'Ora standard dell’Europa centrale',
  'Indian/Antananarivo': 'Ora dell’Africa orientale',
  'Indian/Chagos': 'Ora dell’Oceano Indiano',
  'Indian/Christmas': 'Ora dell’Isola Christmas',
  'Indian/Cocos': 'Ora delle Isole Cocos',
  'Indian/Comoro': 'Ora dell’Africa orientale',
  'Indian/Kerguelen': 'Ora delle Terre australi e antartiche francesi',
  'Indian/Mahe': 'Ora delle Seychelles',
  'Indian/Maldives': 'Ora delle Maldive',
  'Indian/Mauritius': 'Ora standard delle Mauritius',
  'Indian/Mayotte': 'Ora dell’Africa orientale',
  'Indian/Reunion': 'Ora di Riunione',
  'Pacific/Apia': 'Ora standard di Apia',
  'Pacific/Auckland': 'Ora standard della Nuova Zelanda',
  'Pacific/Bougainville': 'GMT+11:00',
  'Pacific/Chatham': 'Ora standard delle Chatham',
  'Pacific/Chuuk': 'Ora del Chuuk',
  'Pacific/Easter': 'Ora standard dell’Isola di Pasqua',
  'Pacific/Efate': 'Ora standard del Vanuatu',
  'Pacific/Enderbury': 'Ora delle Isole della Fenice',
  'Pacific/Fakaofo': 'Ora di Tokelau',
  'Pacific/Fiji': 'Ora standard delle Figi',
  'Pacific/Funafuti': 'Ora di Tuvalu',
  'Pacific/Galapagos': 'Ora delle Galapagos',
  'Pacific/Gambier': 'Ora di Gambier',
  'Pacific/Guadalcanal': 'Ora delle Isole Salomone',
  'Pacific/Guam': 'Ora di Chamorro',
  'Pacific/Honolulu': 'Ora standard delle Isole Hawaii-Aleutine',
  'Pacific/Kiritimati': 'Ora delle Sporadi equatoriali',
  'Pacific/Kosrae': 'Ora del Kosrae',
  'Pacific/Kwajalein': 'Ora delle Isole Marshall',
  'Pacific/Majuro': 'Ora delle Isole Marshall',
  'Pacific/Marquesas': 'Ora delle Marchesi',
  'Pacific/Midway': 'Ora standard di Samoa',
  'Pacific/Nauru': 'Ora di Nauru',
  'Pacific/Niue': 'Ora di Niue',
  'Pacific/Norfolk': 'Ora delle Isole Norfolk',
  'Pacific/Noumea': 'Ora standard della Nuova Caledonia',
  'Pacific/Pago_Pago': 'Ora standard di Samoa',
  'Pacific/Palau': 'Ora di Palau',
  'Pacific/Pitcairn': 'Ora delle Pitcairn',
  'Pacific/Pohnpei': 'Ora di Pohnpei',
  'Pacific/Port_Moresby': 'Ora della Papua Nuova Guinea',
  'Pacific/Rarotonga': 'Ora standard delle isole Cook',
  'Pacific/Saipan': 'Ora di Chamorro',
  'Pacific/Tahiti': 'Ora di Tahiti',
  'Pacific/Tarawa': 'Ora delle isole Gilbert',
  'Pacific/Tongatapu': 'Ora standard di Tonga',
  'Pacific/Wake': 'Ora dell’Isola di Wake',
  'Pacific/Wallis': 'Ora di Wallis e Futuna',
  UTC: 'Tempo coordinato universale',
};
