module.exports = {
  'Africa/Abidjan': 'Greenwich Mean Time',
  'Africa/Accra': 'Greenwich Mean Time',
  'Africa/Addis_Ababa': 'Oost-Afrikaanse tijd',
  'Africa/Algiers': 'Midden-Europese standaardtijd',
  'Africa/Asmara': 'Oost-Afrikaanse tijd',
  'Africa/Bamako': 'Greenwich Mean Time',
  'Africa/Bangui': 'West-Afrikaanse standaardtijd',
  'Africa/Banjul': 'Greenwich Mean Time',
  'Africa/Bissau': 'Greenwich Mean Time',
  'Africa/Blantyre': 'Centraal-Afrikaanse tijd',
  'Africa/Brazzaville': 'West-Afrikaanse standaardtijd',
  'Africa/Bujumbura': 'Centraal-Afrikaanse tijd',
  'Africa/Cairo': 'Oost-Europese standaardtijd',
  'Africa/Casablanca': 'West-Europese standaardtijd',
  'Africa/Ceuta': 'Midden-Europese standaardtijd',
  'Africa/Conakry': 'Greenwich Mean Time',
  'Africa/Dakar': 'Greenwich Mean Time',
  'Africa/Dar_es_Salaam': 'Oost-Afrikaanse tijd',
  'Africa/Djibouti': 'Oost-Afrikaanse tijd',
  'Africa/Douala': 'West-Afrikaanse standaardtijd',
  'Africa/El_Aaiun': 'West-Europese standaardtijd',
  'Africa/Freetown': 'Greenwich Mean Time',
  'Africa/Gaborone': 'Centraal-Afrikaanse tijd',
  'Africa/Harare': 'Centraal-Afrikaanse tijd',
  'Africa/Johannesburg': 'Zuid-Afrikaanse tijd',
  'Africa/Juba': 'Oost-Afrikaanse tijd',
  'Africa/Kampala': 'Oost-Afrikaanse tijd',
  'Africa/Khartoum': 'Centraal-Afrikaanse tijd',
  'Africa/Kigali': 'Centraal-Afrikaanse tijd',
  'Africa/Kinshasa': 'West-Afrikaanse standaardtijd',
  'Africa/Lagos': 'West-Afrikaanse standaardtijd',
  'Africa/Libreville': 'West-Afrikaanse standaardtijd',
  'Africa/Lome': 'Greenwich Mean Time',
  'Africa/Luanda': 'West-Afrikaanse standaardtijd',
  'Africa/Lubumbashi': 'Centraal-Afrikaanse tijd',
  'Africa/Lusaka': 'Centraal-Afrikaanse tijd',
  'Africa/Malabo': 'West-Afrikaanse standaardtijd',
  'Africa/Maputo': 'Centraal-Afrikaanse tijd',
  'Africa/Maseru': 'Zuid-Afrikaanse tijd',
  'Africa/Mbabane': 'Zuid-Afrikaanse tijd',
  'Africa/Mogadishu': 'Oost-Afrikaanse tijd',
  'Africa/Monrovia': 'Greenwich Mean Time',
  'Africa/Nairobi': 'Oost-Afrikaanse tijd',
  'Africa/Ndjamena': 'West-Afrikaanse standaardtijd',
  'Africa/Niamey': 'West-Afrikaanse standaardtijd',
  'Africa/Nouakchott': 'Greenwich Mean Time',
  'Africa/Ouagadougou': 'Greenwich Mean Time',
  'Africa/Porto-Novo': 'West-Afrikaanse standaardtijd',
  'Africa/Sao_Tome': 'Greenwich Mean Time',
  'Africa/Tripoli': 'Oost-Europese standaardtijd',
  'Africa/Tunis': 'Midden-Europese standaardtijd',
  'Africa/Windhoek': 'Centraal-Afrikaanse tijd',
  'America/Adak': 'Hawaii-Aleoetische standaardtijd',
  'America/Anchorage': 'Alaska-standaardtijd',
  'America/Anguilla': 'Atlantic-standaardtijd',
  'America/Antigua': 'Atlantic-standaardtijd',
  'America/Araguaina': 'Braziliaanse standaardtijd',
  'America/Argentina/Buenos_Aires': 'Argentijnse standaardtijd',
  'America/Argentina/Catamarca': 'Argentijnse standaardtijd',
  'America/Argentina/Cordoba': 'Argentijnse standaardtijd',
  'America/Argentina/Jujuy': 'Argentijnse standaardtijd',
  'America/Argentina/La_Rioja': 'Argentijnse standaardtijd',
  'America/Argentina/Mendoza': 'Argentijnse standaardtijd',
  'America/Argentina/Rio_Gallegos': 'Argentijnse standaardtijd',
  'America/Argentina/Salta': 'Argentijnse standaardtijd',
  'America/Argentina/San_Juan': 'Argentijnse standaardtijd',
  'America/Argentina/San_Luis': 'West-Argentijnse standaardtijd',
  'America/Argentina/Tucuman': 'Argentijnse standaardtijd',
  'America/Argentina/Ushuaia': 'Argentijnse standaardtijd',
  'America/Aruba': 'Atlantic-standaardtijd',
  'America/Asuncion': 'Paraguayaanse standaardtijd',
  'America/Atikokan': 'Eastern-standaardtijd',
  'America/Bahia': 'Braziliaanse standaardtijd',
  'America/Bahia_Banderas': 'Central-standaardtijd',
  'America/Barbados': 'Atlantic-standaardtijd',
  'America/Belem': 'Braziliaanse standaardtijd',
  'America/Belize': 'Central-standaardtijd',
  'America/Blanc-Sablon': 'Atlantic-standaardtijd',
  'America/Boa_Vista': 'Amazone-standaardtijd',
  'America/Bogota': 'Colombiaanse standaardtijd',
  'America/Boise': 'Mountain-standaardtijd',
  'America/Cambridge_Bay': 'Mountain-standaardtijd',
  'America/Campo_Grande': 'Amazone-standaardtijd',
  'America/Cancun': 'Eastern-standaardtijd',
  'America/Caracas': 'Venezolaanse tijd',
  'America/Cayenne': 'Frans-Guyaanse tijd',
  'America/Cayman': 'Eastern-standaardtijd',
  'America/Chicago': 'Central-standaardtijd',
  'America/Chihuahua': 'Mexicaanse Pacific-standaardtijd',
  'America/Costa_Rica': 'Central-standaardtijd',
  'America/Creston': 'Mountain-standaardtijd',
  'America/Cuiaba': 'Amazone-standaardtijd',
  'America/Curacao': 'Atlantic-standaardtijd',
  'America/Danmarkshavn': 'Greenwich Mean Time',
  'America/Dawson': 'Pacific-standaardtijd',
  'America/Dawson_Creek': 'Mountain-standaardtijd',
  'America/Denver': 'Mountain-standaardtijd',
  'America/Detroit': 'Eastern-standaardtijd',
  'America/Dominica': 'Atlantic-standaardtijd',
  'America/Edmonton': 'Mountain-standaardtijd',
  'America/Eirunepe': 'Acre-standaardtijd',
  'America/El_Salvador': 'Central-standaardtijd',
  'America/Fort_Nelson': 'Mountain-standaardtijd',
  'America/Fortaleza': 'Braziliaanse standaardtijd',
  'America/Glace_Bay': 'Atlantic-standaardtijd',
  'America/Godthab': 'West-Groenlandse standaardtijd',
  'America/Goose_Bay': 'Atlantic-standaardtijd',
  'America/Grand_Turk': 'Eastern-standaardtijd',
  'America/Grenada': 'Atlantic-standaardtijd',
  'America/Guadeloupe': 'Atlantic-standaardtijd',
  'America/Guatemala': 'Central-standaardtijd',
  'America/Guayaquil': 'Ecuadoraanse tijd',
  'America/Guyana': 'Guyaanse tijd',
  'America/Halifax': 'Atlantic-standaardtijd',
  'America/Havana': 'Cubaanse standaardtijd',
  'America/Hermosillo': 'Mexicaanse Pacific-standaardtijd',
  'America/Indiana/Indianapolis': 'Eastern-standaardtijd',
  'America/Indiana/Knox': 'Central-standaardtijd',
  'America/Indiana/Marengo': 'Eastern-standaardtijd',
  'America/Indiana/Petersburg': 'Eastern-standaardtijd',
  'America/Indiana/Tell_City': 'Central-standaardtijd',
  'America/Indiana/Vevay': 'Eastern-standaardtijd',
  'America/Indiana/Vincennes': 'Eastern-standaardtijd',
  'America/Indiana/Winamac': 'Eastern-standaardtijd',
  'America/Inuvik': 'Mountain-standaardtijd',
  'America/Iqaluit': 'Eastern-standaardtijd',
  'America/Jamaica': 'Eastern-standaardtijd',
  'America/Juneau': 'Alaska-standaardtijd',
  'America/Kentucky/Louisville': 'Eastern-standaardtijd',
  'America/Kentucky/Monticello': 'Eastern-standaardtijd',
  'America/Kralendijk': 'Atlantic-standaardtijd',
  'America/La_Paz': 'Boliviaanse tijd',
  'America/Lima': 'Peruaanse standaardtijd',
  'America/Los_Angeles': 'Pacific-standaardtijd',
  'America/Lower_Princes': 'Atlantic-standaardtijd',
  'America/Maceio': 'Braziliaanse standaardtijd',
  'America/Managua': 'Central-standaardtijd',
  'America/Manaus': 'Amazone-standaardtijd',
  'America/Marigot': 'Atlantic-standaardtijd',
  'America/Martinique': 'Atlantic-standaardtijd',
  'America/Matamoros': 'Central-standaardtijd',
  'America/Mazatlan': 'Mexicaanse Pacific-standaardtijd',
  'America/Menominee': 'Central-standaardtijd',
  'America/Merida': 'Central-standaardtijd',
  'America/Metlakatla': 'Alaska-standaardtijd',
  'America/Mexico_City': 'Central-standaardtijd',
  'America/Miquelon': 'Saint Pierre en Miquelon-standaardtijd',
  'America/Moncton': 'Atlantic-standaardtijd',
  'America/Monterrey': 'Central-standaardtijd',
  'America/Montevideo': 'Uruguayaanse standaardtijd',
  'America/Montserrat': 'Atlantic-standaardtijd',
  'America/Nassau': 'Eastern-standaardtijd',
  'America/New_York': 'Eastern-standaardtijd',
  'America/Nipigon': 'Eastern-standaardtijd',
  'America/Nome': 'Alaska-standaardtijd',
  'America/Noronha': 'Fernando de Noronha-standaardtijd',
  'America/North_Dakota/Beulah': 'Central-standaardtijd',
  'America/North_Dakota/Center': 'Central-standaardtijd',
  'America/North_Dakota/New_Salem': 'Central-standaardtijd',
  'America/Ojinaga': 'Mountain-standaardtijd',
  'America/Panama': 'Eastern-standaardtijd',
  'America/Pangnirtung': 'Eastern-standaardtijd',
  'America/Paramaribo': 'Surinaamse tijd',
  'America/Phoenix': 'Mountain-standaardtijd',
  'America/Port-au-Prince': 'Eastern-standaardtijd',
  'America/Port_of_Spain': 'Atlantic-standaardtijd',
  'America/Porto_Velho': 'Amazone-standaardtijd',
  'America/Puerto_Rico': 'Atlantic-standaardtijd',
  'America/Punta_Arenas': 'GMT-03:00',
  'America/Rainy_River': 'Central-standaardtijd',
  'America/Rankin_Inlet': 'Central-standaardtijd',
  'America/Recife': 'Braziliaanse standaardtijd',
  'America/Regina': 'Central-standaardtijd',
  'America/Resolute': 'Central-standaardtijd',
  'America/Rio_Branco': 'Acre-standaardtijd',
  'America/Santarem': 'Braziliaanse standaardtijd',
  'America/Santiago': 'Chileense standaardtijd',
  'America/Santo_Domingo': 'Atlantic-standaardtijd',
  'America/Sao_Paulo': 'Braziliaanse standaardtijd',
  'America/Scoresbysund': 'Oost-Groenlandse standaardtijd',
  'America/Sitka': 'Alaska-standaardtijd',
  'America/St_Barthelemy': 'Atlantic-standaardtijd',
  'America/St_Johns': 'Newfoundland-standaardtijd',
  'America/St_Kitts': 'Atlantic-standaardtijd',
  'America/St_Lucia': 'Atlantic-standaardtijd',
  'America/St_Thomas': 'Atlantic-standaardtijd',
  'America/St_Vincent': 'Atlantic-standaardtijd',
  'America/Swift_Current': 'Central-standaardtijd',
  'America/Tegucigalpa': 'Central-standaardtijd',
  'America/Thule': 'Atlantic-standaardtijd',
  'America/Thunder_Bay': 'Eastern-standaardtijd',
  'America/Tijuana': 'Pacific-standaardtijd',
  'America/Toronto': 'Eastern-standaardtijd',
  'America/Tortola': 'Atlantic-standaardtijd',
  'America/Vancouver': 'Pacific-standaardtijd',
  'America/Whitehorse': 'Pacific-standaardtijd',
  'America/Winnipeg': 'Central-standaardtijd',
  'America/Yakutat': 'Alaska-standaardtijd',
  'America/Yellowknife': 'Mountain-standaardtijd',
  'Antarctica/Casey': 'Casey tijd',
  'Antarctica/Davis': 'Davis-tijd',
  'Antarctica/DumontDUrville': 'Dumont-d’Urville-tijd',
  'Antarctica/Macquarie': 'Macquarie-eilandse tijd',
  'Antarctica/Mawson': 'Mawson-tijd',
  'Antarctica/McMurdo': 'Nieuw-Zeelandse standaardtijd',
  'Antarctica/Palmer': 'GMT-03:00',
  'Antarctica/Rothera': 'Rothera-tijd',
  'Antarctica/Syowa': 'Syowa-tijd',
  'Antarctica/Troll': 'Greenwich Mean Time',
  'Antarctica/Vostok': 'Vostok-tijd',
  'Arctic/Longyearbyen': 'Midden-Europese standaardtijd',
  'Asia/Aden': 'Arabische standaardtijd',
  'Asia/Almaty': 'Oost-Kazachse tijd',
  'Asia/Amman': 'Oost-Europese standaardtijd',
  'Asia/Anadyr': 'Anadyr-standaardtijd',
  'Asia/Aqtau': 'West-Kazachse tijd',
  'Asia/Aqtobe': 'West-Kazachse tijd',
  'Asia/Ashgabat': 'Turkmeense standaardtijd',
  'Asia/Atyrau': 'West-Kazachse tijd',
  'Asia/Baghdad': 'Arabische standaardtijd',
  'Asia/Bahrain': 'Arabische standaardtijd',
  'Asia/Baku': 'Azerbeidzjaanse standaardtijd',
  'Asia/Bangkok': 'Indochinese tijd',
  'Asia/Barnaul': 'GMT+07:00',
  'Asia/Beirut': 'Oost-Europese standaardtijd',
  'Asia/Bishkek': 'Kirgizische tijd',
  'Asia/Brunei': 'Bruneise tijd',
  'Asia/Chita': 'Jakoetsk-standaardtijd',
  'Asia/Choibalsan': 'Tsjojbalsan-standaardtijd',
  'Asia/Colombo': 'Indiase tijd',
  'Asia/Damascus': 'Oost-Europese standaardtijd',
  'Asia/Dhaka': 'Bengalese standaardtijd',
  'Asia/Dili': 'Oost-Timorese tijd',
  'Asia/Dubai': 'Golf-standaardtijd',
  'Asia/Dushanbe': 'Tadzjiekse tijd',
  'Asia/Famagusta': 'GMT+02:00',
  'Asia/Gaza': 'Oost-Europese standaardtijd',
  'Asia/Hebron': 'Oost-Europese standaardtijd',
  'Asia/Ho_Chi_Minh': 'Indochinese tijd',
  'Asia/Hong_Kong': 'Hongkongse standaardtijd',
  'Asia/Hovd': 'Hovd-standaardtijd',
  'Asia/Irkutsk': 'Irkoetsk-standaardtijd',
  'Asia/Jakarta': 'West-Indonesische tijd',
  'Asia/Jayapura': 'Oost-Indonesische tijd',
  'Asia/Jerusalem': 'Israëlische standaardtijd',
  'Asia/Kabul': 'Afghaanse tijd',
  'Asia/Kamchatka': 'Petropavlovsk-Kamtsjatski-standaardtijd',
  'Asia/Karachi': 'Pakistaanse standaardtijd',
  'Asia/Kathmandu': 'Nepalese tijd',
  'Asia/Khandyga': 'Jakoetsk-standaardtijd',
  'Asia/Kolkata': 'Indiase tijd',
  'Asia/Krasnoyarsk': 'Krasnojarsk-standaardtijd',
  'Asia/Kuala_Lumpur': 'Maleisische tijd',
  'Asia/Kuching': 'Maleisische tijd',
  'Asia/Kuwait': 'Arabische standaardtijd',
  'Asia/Macau': 'Chinese standaardtijd',
  'Asia/Magadan': 'Magadan-standaardtijd',
  'Asia/Makassar': 'Centraal-Indonesische tijd',
  'Asia/Manila': 'Filipijnse standaardtijd',
  'Asia/Muscat': 'Golf-standaardtijd',
  'Asia/Nicosia': 'Oost-Europese standaardtijd',
  'Asia/Novokuznetsk': 'Krasnojarsk-standaardtijd',
  'Asia/Novosibirsk': 'Novosibirsk-standaardtijd',
  'Asia/Omsk': 'Omsk-standaardtijd',
  'Asia/Oral': 'West-Kazachse tijd',
  'Asia/Phnom_Penh': 'Indochinese tijd',
  'Asia/Pontianak': 'West-Indonesische tijd',
  'Asia/Pyongyang': 'Pyongyang-tijd',
  'Asia/Qatar': 'Arabische standaardtijd',
  'Asia/Qyzylorda': 'Oost-Kazachse tijd',
  'Asia/Riyadh': 'Arabische standaardtijd',
  'Asia/Sakhalin': 'Sachalin-standaardtijd',
  'Asia/Samarkand': 'Oezbeekse standaardtijd',
  'Asia/Seoul': 'Koreaanse standaardtijd',
  'Asia/Shanghai': 'Chinese standaardtijd',
  'Asia/Singapore': 'Singaporese standaardtijd',
  'Asia/Srednekolymsk': 'GMT+11:00',
  'Asia/Taipei': 'Taipei-standaardtijd',
  'Asia/Tashkent': 'Oezbeekse standaardtijd',
  'Asia/Tbilisi': 'Georgische standaardtijd',
  'Asia/Tehran': 'Iraanse standaardtijd',
  'Asia/Thimphu': 'Bhutaanse tijd',
  'Asia/Tokyo': 'Japanse standaardtijd',
  'Asia/Tomsk': 'GMT+07:00',
  'Asia/Ulaanbaatar': 'Ulaanbaatar-standaardtijd',
  'Asia/Urumqi': 'GMT+06:00',
  'Asia/Ust-Nera': 'Vladivostok-standaardtijd',
  'Asia/Vientiane': 'Indochinese tijd',
  'Asia/Vladivostok': 'Vladivostok-standaardtijd',
  'Asia/Yakutsk': 'Jakoetsk-standaardtijd',
  'Asia/Yangon': 'Myanmarese tijd',
  'Asia/Yekaterinburg': 'Jekaterinenburg-standaardtijd',
  'Asia/Yerevan': 'Armeense standaardtijd',
  'Atlantic/Azores': 'Azoren-standaardtijd',
  'Atlantic/Bermuda': 'Atlantic-standaardtijd',
  'Atlantic/Canary': 'West-Europese standaardtijd',
  'Atlantic/Cape_Verde': 'Kaapverdische standaardtijd',
  'Atlantic/Faroe': 'West-Europese standaardtijd',
  'Atlantic/Madeira': 'West-Europese standaardtijd',
  'Atlantic/Reykjavik': 'Greenwich Mean Time',
  'Atlantic/South_Georgia': 'Zuid-Georgische tijd',
  'Atlantic/St_Helena': 'Greenwich Mean Time',
  'Atlantic/Stanley': 'Falklandeilandse standaardtijd',
  'Australia/Adelaide': 'Midden-Australische standaardtijd',
  'Australia/Brisbane': 'Oost-Australische standaardtijd',
  'Australia/Broken_Hill': 'Midden-Australische standaardtijd',
  'Australia/Currie': 'Oost-Australische standaardtijd',
  'Australia/Darwin': 'Midden-Australische standaardtijd',
  'Australia/Eucla': 'Midden-Australische westelijke standaardtijd',
  'Australia/Hobart': 'Oost-Australische standaardtijd',
  'Australia/Lindeman': 'Oost-Australische standaardtijd',
  'Australia/Lord_Howe': 'Lord Howe-eilandse standaardtijd',
  'Australia/Melbourne': 'Oost-Australische standaardtijd',
  'Australia/Perth': 'West-Australische standaardtijd',
  'Australia/Sydney': 'Oost-Australische standaardtijd',
  'Europe/Amsterdam': 'Midden-Europese standaardtijd',
  'Europe/Andorra': 'Midden-Europese standaardtijd',
  'Europe/Astrakhan': 'GMT+04:00',
  'Europe/Athens': 'Oost-Europese standaardtijd',
  'Europe/Belgrade': 'Midden-Europese standaardtijd',
  'Europe/Berlin': 'Midden-Europese standaardtijd',
  'Europe/Bratislava': 'Midden-Europese standaardtijd',
  'Europe/Brussels': 'Midden-Europese standaardtijd',
  'Europe/Bucharest': 'Oost-Europese standaardtijd',
  'Europe/Budapest': 'Midden-Europese standaardtijd',
  'Europe/Busingen': 'Midden-Europese standaardtijd',
  'Europe/Chisinau': 'Oost-Europese standaardtijd',
  'Europe/Copenhagen': 'Midden-Europese standaardtijd',
  'Europe/Dublin': 'Greenwich Mean Time',
  'Europe/Gibraltar': 'Midden-Europese standaardtijd',
  'Europe/Guernsey': 'Greenwich Mean Time',
  'Europe/Helsinki': 'Oost-Europese standaardtijd',
  'Europe/Isle_of_Man': 'Greenwich Mean Time',
  'Europe/Istanbul': 'GMT+03:00',
  'Europe/Jersey': 'Greenwich Mean Time',
  'Europe/Kaliningrad': 'Oost-Europese standaardtijd',
  'Europe/Kiev': 'Oost-Europese standaardtijd',
  'Europe/Kirov': 'GMT+03:00',
  'Europe/Lisbon': 'West-Europese standaardtijd',
  'Europe/Ljubljana': 'Midden-Europese standaardtijd',
  'Europe/London': 'Greenwich Mean Time',
  'Europe/Luxembourg': 'Midden-Europese standaardtijd',
  'Europe/Madrid': 'Midden-Europese standaardtijd',
  'Europe/Malta': 'Midden-Europese standaardtijd',
  'Europe/Mariehamn': 'Oost-Europese standaardtijd',
  'Europe/Minsk': 'Moskou-standaardtijd',
  'Europe/Monaco': 'Midden-Europese standaardtijd',
  'Europe/Moscow': 'Moskou-standaardtijd',
  'Europe/Oslo': 'Midden-Europese standaardtijd',
  'Europe/Paris': 'Midden-Europese standaardtijd',
  'Europe/Podgorica': 'Midden-Europese standaardtijd',
  'Europe/Prague': 'Midden-Europese standaardtijd',
  'Europe/Riga': 'Oost-Europese standaardtijd',
  'Europe/Rome': 'Midden-Europese standaardtijd',
  'Europe/Samara': 'Samara-standaardtijd',
  'Europe/San_Marino': 'Midden-Europese standaardtijd',
  'Europe/Sarajevo': 'Midden-Europese standaardtijd',
  'Europe/Saratov': 'GMT+04:00',
  'Europe/Simferopol': 'Moskou-standaardtijd',
  'Europe/Skopje': 'Midden-Europese standaardtijd',
  'Europe/Sofia': 'Oost-Europese standaardtijd',
  'Europe/Stockholm': 'Midden-Europese standaardtijd',
  'Europe/Tallinn': 'Oost-Europese standaardtijd',
  'Europe/Tirane': 'Midden-Europese standaardtijd',
  'Europe/Ulyanovsk': 'GMT+04:00',
  'Europe/Uzhgorod': 'Oost-Europese standaardtijd',
  'Europe/Vaduz': 'Midden-Europese standaardtijd',
  'Europe/Vatican': 'Midden-Europese standaardtijd',
  'Europe/Vienna': 'Midden-Europese standaardtijd',
  'Europe/Vilnius': 'Oost-Europese standaardtijd',
  'Europe/Volgograd': 'Moskou-standaardtijd',
  'Europe/Warsaw': 'Midden-Europese standaardtijd',
  'Europe/Zagreb': 'Midden-Europese standaardtijd',
  'Europe/Zaporozhye': 'Oost-Europese standaardtijd',
  'Europe/Zurich': 'Midden-Europese standaardtijd',
  'Indian/Antananarivo': 'Oost-Afrikaanse tijd',
  'Indian/Chagos': 'Indische Oceaan-tijd',
  'Indian/Christmas': 'Christmaseilandse tijd',
  'Indian/Cocos': 'Cocoseilandse tijd',
  'Indian/Comoro': 'Oost-Afrikaanse tijd',
  'Indian/Kerguelen': 'Franse zuidelijke en Antarctische tijd',
  'Indian/Mahe': 'Seychelse tijd',
  'Indian/Maldives': 'Maldivische tijd',
  'Indian/Mauritius': 'Mauritiaanse standaardtijd',
  'Indian/Mayotte': 'Oost-Afrikaanse tijd',
  'Indian/Reunion': 'Réunionse tijd',
  'Pacific/Apia': 'Apia-standaardtijd',
  'Pacific/Auckland': 'Nieuw-Zeelandse standaardtijd',
  'Pacific/Bougainville': 'GMT+11:00',
  'Pacific/Chatham': 'Chatham-standaardtijd',
  'Pacific/Chuuk': 'Chuukse tijd',
  'Pacific/Easter': 'Paaseilandse standaardtijd',
  'Pacific/Efate': 'Vanuatuaanse standaardtijd',
  'Pacific/Enderbury': 'Phoenixeilandse tijd',
  'Pacific/Fakaofo': 'Tokelau-eilandse tijd',
  'Pacific/Fiji': 'Fijische standaardtijd',
  'Pacific/Funafuti': 'Tuvaluaanse tijd',
  'Pacific/Galapagos': 'Galapagoseilandse standaardtijd',
  'Pacific/Gambier': 'Gambiereilandse tijd',
  'Pacific/Guadalcanal': 'Salomonseilandse tijd',
  'Pacific/Guam': 'Chamorro-tijd',
  'Pacific/Honolulu': 'Hawaii-Aleoetische standaardtijd',
  'Pacific/Kiritimati': 'Line-eilandse tijd',
  'Pacific/Kosrae': 'Kosraese tijd',
  'Pacific/Kwajalein': 'Marshalleilandse tijd',
  'Pacific/Majuro': 'Marshalleilandse tijd',
  'Pacific/Marquesas': 'Marquesaseilandse tijd',
  'Pacific/Midway': 'Samoaanse standaardtijd',
  'Pacific/Nauru': 'Nauruaanse tijd',
  'Pacific/Niue': 'Niuese tijd',
  'Pacific/Norfolk': 'Norfolkeilandse tijd',
  'Pacific/Noumea': 'Nieuw-Caledonische standaardtijd',
  'Pacific/Pago_Pago': 'Samoaanse standaardtijd',
  'Pacific/Palau': 'Belause tijd',
  'Pacific/Pitcairn': 'Pitcairneilandse tijd',
  'Pacific/Pohnpei': 'Pohnpei-tijd',
  'Pacific/Port_Moresby': 'Papoea-Nieuw-Guineese tijd',
  'Pacific/Rarotonga': 'Cookeilandse standaardtijd',
  'Pacific/Saipan': 'Chamorro-tijd',
  'Pacific/Tahiti': 'Tahitiaanse tijd',
  'Pacific/Tarawa': 'Gilberteilandse tijd',
  'Pacific/Tongatapu': 'Tongaanse standaardtijd',
  'Pacific/Wake': 'Wake-eilandse tijd',
  'Pacific/Wallis': 'Wallis en Futunase tijd',
  UTC: 'Gecoördineerde wereldtijd',
};
