module.exports = {
  'Africa/Abidjan': 'czas uniwersalny',
  'Africa/Accra': 'czas uniwersalny',
  'Africa/Addis_Ababa': 'czas wschodnioafrykański',
  'Africa/Algiers': 'czas środkowoeuropejski standardowy',
  'Africa/Asmara': 'czas wschodnioafrykański',
  'Africa/Bamako': 'czas uniwersalny',
  'Africa/Bangui': 'czas zachodnioafrykański standardowy',
  'Africa/Banjul': 'czas uniwersalny',
  'Africa/Bissau': 'czas uniwersalny',
  'Africa/Blantyre': 'czas środkowoafrykański',
  'Africa/Brazzaville': 'czas zachodnioafrykański standardowy',
  'Africa/Bujumbura': 'czas środkowoafrykański',
  'Africa/Cairo': 'czas wschodnioeuropejski standardowy',
  'Africa/Casablanca': 'czas zachodnioeuropejski standardowy',
  'Africa/Ceuta': 'czas środkowoeuropejski standardowy',
  'Africa/Conakry': 'czas uniwersalny',
  'Africa/Dakar': 'czas uniwersalny',
  'Africa/Dar_es_Salaam': 'czas wschodnioafrykański',
  'Africa/Djibouti': 'czas wschodnioafrykański',
  'Africa/Douala': 'czas zachodnioafrykański standardowy',
  'Africa/El_Aaiun': 'czas zachodnioeuropejski standardowy',
  'Africa/Freetown': 'czas uniwersalny',
  'Africa/Gaborone': 'czas środkowoafrykański',
  'Africa/Harare': 'czas środkowoafrykański',
  'Africa/Johannesburg': 'czas południowoafrykański',
  'Africa/Juba': 'czas wschodnioafrykański',
  'Africa/Kampala': 'czas wschodnioafrykański',
  'Africa/Khartoum': 'czas środkowoafrykański',
  'Africa/Kigali': 'czas środkowoafrykański',
  'Africa/Kinshasa': 'czas zachodnioafrykański standardowy',
  'Africa/Lagos': 'czas zachodnioafrykański standardowy',
  'Africa/Libreville': 'czas zachodnioafrykański standardowy',
  'Africa/Lome': 'czas uniwersalny',
  'Africa/Luanda': 'czas zachodnioafrykański standardowy',
  'Africa/Lubumbashi': 'czas środkowoafrykański',
  'Africa/Lusaka': 'czas środkowoafrykański',
  'Africa/Malabo': 'czas zachodnioafrykański standardowy',
  'Africa/Maputo': 'czas środkowoafrykański',
  'Africa/Maseru': 'czas południowoafrykański',
  'Africa/Mbabane': 'czas południowoafrykański',
  'Africa/Mogadishu': 'czas wschodnioafrykański',
  'Africa/Monrovia': 'czas uniwersalny',
  'Africa/Nairobi': 'czas wschodnioafrykański',
  'Africa/Ndjamena': 'czas zachodnioafrykański standardowy',
  'Africa/Niamey': 'czas zachodnioafrykański standardowy',
  'Africa/Nouakchott': 'czas uniwersalny',
  'Africa/Ouagadougou': 'czas uniwersalny',
  'Africa/Porto-Novo': 'czas zachodnioafrykański standardowy',
  'Africa/Sao_Tome': 'czas uniwersalny',
  'Africa/Tripoli': 'czas wschodnioeuropejski standardowy',
  'Africa/Tunis': 'czas środkowoeuropejski standardowy',
  'Africa/Windhoek': 'czas środkowoafrykański',
  'America/Adak': 'Hawaje-Aleuty (czas standardowy)',
  'America/Anchorage': 'Alaska (czas standardowy)',
  'America/Anguilla': 'czas atlantycki standardowy',
  'America/Antigua': 'czas atlantycki standardowy',
  'America/Araguaina': 'Brasília (czas standardowy)',
  'America/Argentina/Buenos_Aires': 'Argentyna (czas standardowy)',
  'America/Argentina/Catamarca': 'Argentyna (czas standardowy)',
  'America/Argentina/Cordoba': 'Argentyna (czas standardowy)',
  'America/Argentina/Jujuy': 'Argentyna (czas standardowy)',
  'America/Argentina/La_Rioja': 'Argentyna (czas standardowy)',
  'America/Argentina/Mendoza': 'Argentyna (czas standardowy)',
  'America/Argentina/Rio_Gallegos': 'Argentyna (czas standardowy)',
  'America/Argentina/Salta': 'Argentyna (czas standardowy)',
  'America/Argentina/San_Juan': 'Argentyna (czas standardowy)',
  'America/Argentina/San_Luis': 'Argentyna Zachodnia (czas standardowy)',
  'America/Argentina/Tucuman': 'Argentyna (czas standardowy)',
  'America/Argentina/Ushuaia': 'Argentyna (czas standardowy)',
  'America/Aruba': 'czas atlantycki standardowy',
  'America/Asuncion': 'Paragwaj (czas standardowy)',
  'America/Atikokan': 'czas wschodnioamerykański standardowy',
  'America/Bahia': 'Brasília (czas standardowy)',
  'America/Bahia_Banderas': 'czas środkowoamerykański standardowy',
  'America/Barbados': 'czas atlantycki standardowy',
  'America/Belem': 'Brasília (czas standardowy)',
  'America/Belize': 'czas środkowoamerykański standardowy',
  'America/Blanc-Sablon': 'czas atlantycki standardowy',
  'America/Boa_Vista': 'czas amazoński standardowy',
  'America/Bogota': 'Kolumbia (czas standardowy)',
  'America/Boise': 'czas górski standardowy',
  'America/Cambridge_Bay': 'czas górski standardowy',
  'America/Campo_Grande': 'czas amazoński standardowy',
  'America/Cancun': 'czas wschodnioamerykański standardowy',
  'America/Caracas': 'Wenezuela',
  'America/Cayenne': 'Gujana Francuska',
  'America/Cayman': 'czas wschodnioamerykański standardowy',
  'America/Chicago': 'czas środkowoamerykański standardowy',
  'America/Chihuahua': 'Meksyk (czas pacyficzny standardowy)',
  'America/Costa_Rica': 'czas środkowoamerykański standardowy',
  'America/Creston': 'czas górski standardowy',
  'America/Cuiaba': 'czas amazoński standardowy',
  'America/Curacao': 'czas atlantycki standardowy',
  'America/Danmarkshavn': 'czas uniwersalny',
  'America/Dawson': 'czas pacyficzny standardowy',
  'America/Dawson_Creek': 'czas górski standardowy',
  'America/Denver': 'czas górski standardowy',
  'America/Detroit': 'czas wschodnioamerykański standardowy',
  'America/Dominica': 'czas atlantycki standardowy',
  'America/Edmonton': 'czas górski standardowy',
  'America/Eirunepe': 'GMT-05:00',
  'America/El_Salvador': 'czas środkowoamerykański standardowy',
  'America/Fort_Nelson': 'czas górski standardowy',
  'America/Fortaleza': 'Brasília (czas standardowy)',
  'America/Glace_Bay': 'czas atlantycki standardowy',
  'America/Godthab': 'Grenlandia Zachodnia (czas standardowy)',
  'America/Goose_Bay': 'czas atlantycki standardowy',
  'America/Grand_Turk': 'czas wschodnioamerykański standardowy',
  'America/Grenada': 'czas atlantycki standardowy',
  'America/Guadeloupe': 'czas atlantycki standardowy',
  'America/Guatemala': 'czas środkowoamerykański standardowy',
  'America/Guayaquil': 'Ekwador',
  'America/Guyana': 'Gujana',
  'America/Halifax': 'czas atlantycki standardowy',
  'America/Havana': 'Kuba (czas standardowy)',
  'America/Hermosillo': 'Meksyk (czas pacyficzny standardowy)',
  'America/Indiana/Indianapolis': 'czas wschodnioamerykański standardowy',
  'America/Indiana/Knox': 'czas środkowoamerykański standardowy',
  'America/Indiana/Marengo': 'czas wschodnioamerykański standardowy',
  'America/Indiana/Petersburg': 'czas wschodnioamerykański standardowy',
  'America/Indiana/Tell_City': 'czas środkowoamerykański standardowy',
  'America/Indiana/Vevay': 'czas wschodnioamerykański standardowy',
  'America/Indiana/Vincennes': 'czas wschodnioamerykański standardowy',
  'America/Indiana/Winamac': 'czas wschodnioamerykański standardowy',
  'America/Inuvik': 'czas górski standardowy',
  'America/Iqaluit': 'czas wschodnioamerykański standardowy',
  'America/Jamaica': 'czas wschodnioamerykański standardowy',
  'America/Juneau': 'Alaska (czas standardowy)',
  'America/Kentucky/Louisville': 'czas wschodnioamerykański standardowy',
  'America/Kentucky/Monticello': 'czas wschodnioamerykański standardowy',
  'America/Kralendijk': 'czas atlantycki standardowy',
  'America/La_Paz': 'Boliwia',
  'America/Lima': 'Peru (czas standardowy)',
  'America/Los_Angeles': 'czas pacyficzny standardowy',
  'America/Lower_Princes': 'czas atlantycki standardowy',
  'America/Maceio': 'Brasília (czas standardowy)',
  'America/Managua': 'czas środkowoamerykański standardowy',
  'America/Manaus': 'czas amazoński standardowy',
  'America/Marigot': 'czas atlantycki standardowy',
  'America/Martinique': 'czas atlantycki standardowy',
  'America/Matamoros': 'czas środkowoamerykański standardowy',
  'America/Mazatlan': 'Meksyk (czas pacyficzny standardowy)',
  'America/Menominee': 'czas środkowoamerykański standardowy',
  'America/Merida': 'czas środkowoamerykański standardowy',
  'America/Metlakatla': 'Alaska (czas standardowy)',
  'America/Mexico_City': 'czas środkowoamerykański standardowy',
  'America/Miquelon': 'Saint-Pierre i Miquelon (czas standardowy)',
  'America/Moncton': 'czas atlantycki standardowy',
  'America/Monterrey': 'czas środkowoamerykański standardowy',
  'America/Montevideo': 'Urugwaj (czas standardowy)',
  'America/Montserrat': 'czas atlantycki standardowy',
  'America/Nassau': 'czas wschodnioamerykański standardowy',
  'America/New_York': 'czas wschodnioamerykański standardowy',
  'America/Nipigon': 'czas wschodnioamerykański standardowy',
  'America/Nome': 'Alaska (czas standardowy)',
  'America/Noronha': 'Fernando de Noronha (czas standardowy)',
  'America/North_Dakota/Beulah': 'czas środkowoamerykański standardowy',
  'America/North_Dakota/Center': 'czas środkowoamerykański standardowy',
  'America/North_Dakota/New_Salem': 'czas środkowoamerykański standardowy',
  'America/Ojinaga': 'czas górski standardowy',
  'America/Panama': 'czas wschodnioamerykański standardowy',
  'America/Pangnirtung': 'czas wschodnioamerykański standardowy',
  'America/Paramaribo': 'Surinam',
  'America/Phoenix': 'czas górski standardowy',
  'America/Port-au-Prince': 'czas wschodnioamerykański standardowy',
  'America/Port_of_Spain': 'czas atlantycki standardowy',
  'America/Porto_Velho': 'czas amazoński standardowy',
  'America/Puerto_Rico': 'czas atlantycki standardowy',
  'America/Punta_Arenas': 'GMT-03:00',
  'America/Rainy_River': 'czas środkowoamerykański standardowy',
  'America/Rankin_Inlet': 'czas środkowoamerykański standardowy',
  'America/Recife': 'Brasília (czas standardowy)',
  'America/Regina': 'czas środkowoamerykański standardowy',
  'America/Resolute': 'czas środkowoamerykański standardowy',
  'America/Rio_Branco': 'GMT-05:00',
  'America/Santarem': 'Brasília (czas standardowy)',
  'America/Santiago': 'Chile (czas standardowy)',
  'America/Santo_Domingo': 'czas atlantycki standardowy',
  'America/Sao_Paulo': 'Brasília (czas standardowy)',
  'America/Scoresbysund': 'Grenlandia Wschodnia (czas standardowy)',
  'America/Sitka': 'Alaska (czas standardowy)',
  'America/St_Barthelemy': 'czas atlantycki standardowy',
  'America/St_Johns': 'Nowa Fundlandia (czas standardowy)',
  'America/St_Kitts': 'czas atlantycki standardowy',
  'America/St_Lucia': 'czas atlantycki standardowy',
  'America/St_Thomas': 'czas atlantycki standardowy',
  'America/St_Vincent': 'czas atlantycki standardowy',
  'America/Swift_Current': 'czas środkowoamerykański standardowy',
  'America/Tegucigalpa': 'czas środkowoamerykański standardowy',
  'America/Thule': 'czas atlantycki standardowy',
  'America/Thunder_Bay': 'czas wschodnioamerykański standardowy',
  'America/Tijuana': 'czas pacyficzny standardowy',
  'America/Toronto': 'czas wschodnioamerykański standardowy',
  'America/Tortola': 'czas atlantycki standardowy',
  'America/Vancouver': 'czas pacyficzny standardowy',
  'America/Whitehorse': 'czas pacyficzny standardowy',
  'America/Winnipeg': 'czas środkowoamerykański standardowy',
  'America/Yakutat': 'Alaska (czas standardowy)',
  'America/Yellowknife': 'czas górski standardowy',
  'Antarctica/Casey': 'GMT+11:00',
  'Antarctica/Davis': 'Davis',
  'Antarctica/DumontDUrville': 'Dumont-d’Urville',
  'Antarctica/Macquarie': 'Macquarie',
  'Antarctica/Mawson': 'Mawson',
  'Antarctica/McMurdo': 'Nowa Zelandia (czas standardowy)',
  'Antarctica/Palmer': 'GMT-03:00',
  'Antarctica/Rothera': 'Rothera',
  'Antarctica/Syowa': 'Syowa',
  'Antarctica/Troll': 'czas uniwersalny',
  'Antarctica/Vostok': 'Wostok',
  'Arctic/Longyearbyen': 'czas środkowoeuropejski standardowy',
  'Asia/Aden': 'Półwysep Arabski (czas standardowy)',
  'Asia/Almaty': 'Kazachstan Wschodni',
  'Asia/Amman': 'czas wschodnioeuropejski standardowy',
  'Asia/Anadyr': 'czas standardowy Anadyr',
  'Asia/Aqtau': 'Kazachstan Zachodni',
  'Asia/Aqtobe': 'Kazachstan Zachodni',
  'Asia/Ashgabat': 'Turkmenistan (czas standardowy)',
  'Asia/Atyrau': 'Kazachstan Zachodni',
  'Asia/Baghdad': 'Półwysep Arabski (czas standardowy)',
  'Asia/Bahrain': 'Półwysep Arabski (czas standardowy)',
  'Asia/Baku': 'Azerbejdżan (czas standardowy)',
  'Asia/Bangkok': 'czas indochiński',
  'Asia/Barnaul': 'GMT+07:00',
  'Asia/Beirut': 'czas wschodnioeuropejski standardowy',
  'Asia/Bishkek': 'Kirgistan',
  'Asia/Brunei': 'Brunei',
  'Asia/Chita': 'Jakuck (czas standardowy)',
  'Asia/Choibalsan': 'Czojbalsan (czas standardowy)',
  'Asia/Colombo': 'czas indyjski',
  'Asia/Damascus': 'czas wschodnioeuropejski standardowy',
  'Asia/Dhaka': 'Bangladesz (czas standardowy)',
  'Asia/Dili': 'Timor Wschodni',
  'Asia/Dubai': 'Zatoka Perska',
  'Asia/Dushanbe': 'Tadżykistan',
  'Asia/Famagusta': 'GMT+02:00',
  'Asia/Gaza': 'czas wschodnioeuropejski standardowy',
  'Asia/Hebron': 'czas wschodnioeuropejski standardowy',
  'Asia/Ho_Chi_Minh': 'czas indochiński',
  'Asia/Hong_Kong': 'Hongkong (czas standardowy)',
  'Asia/Hovd': 'Kobdo (czas standardowy)',
  'Asia/Irkutsk': 'Irkuck (czas standardowy)',
  'Asia/Jakarta': 'Indonezja Zachodnia',
  'Asia/Jayapura': 'Indonezja Wschodnia',
  'Asia/Jerusalem': 'Izrael (czas standardowy)',
  'Asia/Kabul': 'Afganistan',
  'Asia/Kamchatka': 'czas standardowy Pietropawłowsk Kamczacki',
  'Asia/Karachi': 'Pakistan (czas standardowy)',
  'Asia/Kathmandu': 'Nepal',
  'Asia/Khandyga': 'Jakuck (czas standardowy)',
  'Asia/Kolkata': 'czas indyjski',
  'Asia/Krasnoyarsk': 'Krasnojarsk (czas standardowy)',
  'Asia/Kuala_Lumpur': 'Malezja',
  'Asia/Kuching': 'Malezja',
  'Asia/Kuwait': 'Półwysep Arabski (czas standardowy)',
  'Asia/Macau': 'Chiny (czas standardowy)',
  'Asia/Magadan': 'Magadan (czas standardowy)',
  'Asia/Makassar': 'Indonezja Środkowa',
  'Asia/Manila': 'Filipiny (czas standardowy)',
  'Asia/Muscat': 'Zatoka Perska',
  'Asia/Nicosia': 'czas wschodnioeuropejski standardowy',
  'Asia/Novokuznetsk': 'Krasnojarsk (czas standardowy)',
  'Asia/Novosibirsk': 'Nowosybirsk (czas standardowy)',
  'Asia/Omsk': 'Omsk (czas standardowy)',
  'Asia/Oral': 'Kazachstan Zachodni',
  'Asia/Phnom_Penh': 'czas indochiński',
  'Asia/Pontianak': 'Indonezja Zachodnia',
  'Asia/Pyongyang': 'Pjongjang',
  'Asia/Qatar': 'Półwysep Arabski (czas standardowy)',
  'Asia/Qyzylorda': 'Kazachstan Wschodni',
  'Asia/Riyadh': 'Półwysep Arabski (czas standardowy)',
  'Asia/Sakhalin': 'Sachalin (czas standardowy)',
  'Asia/Samarkand': 'Uzbekistan (czas standardowy)',
  'Asia/Seoul': 'Korea (czas standardowy)',
  'Asia/Shanghai': 'Chiny (czas standardowy)',
  'Asia/Singapore': 'Singapur',
  'Asia/Srednekolymsk': 'GMT+11:00',
  'Asia/Taipei': 'Tajpej (czas standardowy)',
  'Asia/Tashkent': 'Uzbekistan (czas standardowy)',
  'Asia/Tbilisi': 'Gruzja (czas standardowy)',
  'Asia/Tehran': 'Iran (czas standardowy)',
  'Asia/Thimphu': 'Bhutan',
  'Asia/Tokyo': 'Japonia (czas standardowy)',
  'Asia/Tomsk': 'GMT+07:00',
  'Asia/Ulaanbaatar': 'Ułan Bator (czas standardowy)',
  'Asia/Urumqi': 'GMT+06:00',
  'Asia/Ust-Nera': 'Władywostok (czas standardowy)',
  'Asia/Vientiane': 'czas indochiński',
  'Asia/Vladivostok': 'Władywostok (czas standardowy)',
  'Asia/Yakutsk': 'Jakuck (czas standardowy)',
  'Asia/Yangon': 'Mjanma',
  'Asia/Yekaterinburg': 'Jekaterynburg (czas standardowy)',
  'Asia/Yerevan': 'Armenia (czas standardowy)',
  'Atlantic/Azores': 'Azory (czas standardowy)',
  'Atlantic/Bermuda': 'czas atlantycki standardowy',
  'Atlantic/Canary': 'czas zachodnioeuropejski standardowy',
  'Atlantic/Cape_Verde': 'Wyspy Zielonego Przylądka (czas standardowy)',
  'Atlantic/Faroe': 'czas zachodnioeuropejski standardowy',
  'Atlantic/Madeira': 'czas zachodnioeuropejski standardowy',
  'Atlantic/Reykjavik': 'czas uniwersalny',
  'Atlantic/South_Georgia': 'Georgia Południowa',
  'Atlantic/St_Helena': 'czas uniwersalny',
  'Atlantic/Stanley': 'Falklandy (czas standardowy)',
  'Australia/Adelaide': 'czas środkowoaustralijski standardowy',
  'Australia/Brisbane': 'czas wschodnioaustralijski standardowy',
  'Australia/Broken_Hill': 'czas środkowoaustralijski standardowy',
  'Australia/Currie': 'czas wschodnioaustralijski standardowy',
  'Australia/Darwin': 'czas środkowoaustralijski standardowy',
  'Australia/Eucla': 'czas środkowo-zachodnioaustralijski standardowy',
  'Australia/Hobart': 'czas wschodnioaustralijski standardowy',
  'Australia/Lindeman': 'czas wschodnioaustralijski standardowy',
  'Australia/Lord_Howe': 'Lord Howe (czas standardowy)',
  'Australia/Melbourne': 'czas wschodnioaustralijski standardowy',
  'Australia/Perth': 'czas zachodnioaustralijski standardowy',
  'Australia/Sydney': 'czas wschodnioaustralijski standardowy',
  'Europe/Amsterdam': 'czas środkowoeuropejski standardowy',
  'Europe/Andorra': 'czas środkowoeuropejski standardowy',
  'Europe/Astrakhan': 'GMT+04:00',
  'Europe/Athens': 'czas wschodnioeuropejski standardowy',
  'Europe/Belgrade': 'czas środkowoeuropejski standardowy',
  'Europe/Berlin': 'czas środkowoeuropejski standardowy',
  'Europe/Bratislava': 'czas środkowoeuropejski standardowy',
  'Europe/Brussels': 'czas środkowoeuropejski standardowy',
  'Europe/Bucharest': 'czas wschodnioeuropejski standardowy',
  'Europe/Budapest': 'czas środkowoeuropejski standardowy',
  'Europe/Busingen': 'czas środkowoeuropejski standardowy',
  'Europe/Chisinau': 'czas wschodnioeuropejski standardowy',
  'Europe/Copenhagen': 'czas środkowoeuropejski standardowy',
  'Europe/Dublin': 'czas uniwersalny',
  'Europe/Gibraltar': 'czas środkowoeuropejski standardowy',
  'Europe/Guernsey': 'czas uniwersalny',
  'Europe/Helsinki': 'czas wschodnioeuropejski standardowy',
  'Europe/Isle_of_Man': 'czas uniwersalny',
  'Europe/Istanbul': 'GMT+03:00',
  'Europe/Jersey': 'czas uniwersalny',
  'Europe/Kaliningrad': 'czas wschodnioeuropejski standardowy',
  'Europe/Kiev': 'czas wschodnioeuropejski standardowy',
  'Europe/Kirov': 'GMT+03:00',
  'Europe/Lisbon': 'czas zachodnioeuropejski standardowy',
  'Europe/Ljubljana': 'czas środkowoeuropejski standardowy',
  'Europe/London': 'czas uniwersalny',
  'Europe/Luxembourg': 'czas środkowoeuropejski standardowy',
  'Europe/Madrid': 'czas środkowoeuropejski standardowy',
  'Europe/Malta': 'czas środkowoeuropejski standardowy',
  'Europe/Mariehamn': 'czas wschodnioeuropejski standardowy',
  'Europe/Minsk': 'czas moskiewski standardowy',
  'Europe/Monaco': 'czas środkowoeuropejski standardowy',
  'Europe/Moscow': 'czas moskiewski standardowy',
  'Europe/Oslo': 'czas środkowoeuropejski standardowy',
  'Europe/Paris': 'czas środkowoeuropejski standardowy',
  'Europe/Podgorica': 'czas środkowoeuropejski standardowy',
  'Europe/Prague': 'czas środkowoeuropejski standardowy',
  'Europe/Riga': 'czas wschodnioeuropejski standardowy',
  'Europe/Rome': 'czas środkowoeuropejski standardowy',
  'Europe/Samara': 'czas standardowy Samara',
  'Europe/San_Marino': 'czas środkowoeuropejski standardowy',
  'Europe/Sarajevo': 'czas środkowoeuropejski standardowy',
  'Europe/Saratov': 'GMT+04:00',
  'Europe/Simferopol': 'czas moskiewski standardowy',
  'Europe/Skopje': 'czas środkowoeuropejski standardowy',
  'Europe/Sofia': 'czas wschodnioeuropejski standardowy',
  'Europe/Stockholm': 'czas środkowoeuropejski standardowy',
  'Europe/Tallinn': 'czas wschodnioeuropejski standardowy',
  'Europe/Tirane': 'czas środkowoeuropejski standardowy',
  'Europe/Ulyanovsk': 'GMT+04:00',
  'Europe/Uzhgorod': 'czas wschodnioeuropejski standardowy',
  'Europe/Vaduz': 'czas środkowoeuropejski standardowy',
  'Europe/Vatican': 'czas środkowoeuropejski standardowy',
  'Europe/Vienna': 'czas środkowoeuropejski standardowy',
  'Europe/Vilnius': 'czas wschodnioeuropejski standardowy',
  'Europe/Volgograd': 'czas moskiewski standardowy',
  'Europe/Warsaw': 'czas środkowoeuropejski standardowy',
  'Europe/Zagreb': 'czas środkowoeuropejski standardowy',
  'Europe/Zaporozhye': 'czas wschodnioeuropejski standardowy',
  'Europe/Zurich': 'czas środkowoeuropejski standardowy',
  'Indian/Antananarivo': 'czas wschodnioafrykański',
  'Indian/Chagos': 'Ocean Indyjski',
  'Indian/Christmas': 'Wyspa Bożego Narodzenia',
  'Indian/Cocos': 'Wyspy Kokosowe',
  'Indian/Comoro': 'czas wschodnioafrykański',
  'Indian/Kerguelen': 'Francuskie Terytoria Południowe i Antarktyczne',
  'Indian/Mahe': 'Seszele',
  'Indian/Maldives': 'Malediwy',
  'Indian/Mauritius': 'Mauritius (czas standardowy)',
  'Indian/Mayotte': 'czas wschodnioafrykański',
  'Indian/Reunion': 'Reunion',
  'Pacific/Apia': 'Apia (czas standardowy)',
  'Pacific/Auckland': 'Nowa Zelandia (czas standardowy)',
  'Pacific/Bougainville': 'GMT+11:00',
  'Pacific/Chatham': 'Chatham (czas standardowy)',
  'Pacific/Chuuk': 'Chuuk',
  'Pacific/Easter': 'Wyspa Wielkanocna (czas standardowy)',
  'Pacific/Efate': 'Vanuatu (czas standardowy)',
  'Pacific/Enderbury': 'Feniks',
  'Pacific/Fakaofo': 'Tokelau',
  'Pacific/Fiji': 'Fidżi (czas standardowy)',
  'Pacific/Funafuti': 'Tuvalu',
  'Pacific/Galapagos': 'Galapagos',
  'Pacific/Gambier': 'Wyspy Gambiera',
  'Pacific/Guadalcanal': 'Wyspy Salomona',
  'Pacific/Guam': 'Czamorro',
  'Pacific/Honolulu': 'Hawaje-Aleuty (czas standardowy)',
  'Pacific/Kiritimati': 'Line Islands',
  'Pacific/Kosrae': 'Kosrae',
  'Pacific/Kwajalein': 'Wyspy Marshalla',
  'Pacific/Majuro': 'Wyspy Marshalla',
  'Pacific/Marquesas': 'Markizy',
  'Pacific/Midway': 'Samoa (czas standardowy)',
  'Pacific/Nauru': 'Nauru',
  'Pacific/Niue': 'Niue',
  'Pacific/Norfolk': 'Norfolk',
  'Pacific/Noumea': 'Nowa Kaledonia (czas standardowy)',
  'Pacific/Pago_Pago': 'Samoa (czas standardowy)',
  'Pacific/Palau': 'Palau',
  'Pacific/Pitcairn': 'Pitcairn',
  'Pacific/Pohnpei': 'Pohnpei',
  'Pacific/Port_Moresby': 'Papua-Nowa Gwinea',
  'Pacific/Rarotonga': 'Wyspy Cooka (czas standardowy)',
  'Pacific/Saipan': 'Czamorro',
  'Pacific/Tahiti': 'Tahiti',
  'Pacific/Tarawa': 'Wyspy Gilberta',
  'Pacific/Tongatapu': 'Tonga (czas standardowy)',
  'Pacific/Wake': 'Wake',
  'Pacific/Wallis': 'Wallis i Futuna',
  UTC: 'uniwersalny czas koordynowany',
};
