module.exports = {
  'Africa/Abidjan': 'Horário do Meridiano de Greenwich',
  'Africa/Accra': 'Horário do Meridiano de Greenwich',
  'Africa/Addis_Ababa': 'Horário da África Oriental',
  'Africa/Algiers': 'Horário Padrão da Europa Central',
  'Africa/Asmara': 'Horário da África Oriental',
  'Africa/Bamako': 'Horário do Meridiano de Greenwich',
  'Africa/Bangui': 'Horário Padrão da África Ocidental',
  'Africa/Banjul': 'Horário do Meridiano de Greenwich',
  'Africa/Bissau': 'Horário do Meridiano de Greenwich',
  'Africa/Blantyre': 'Horário da África Central',
  'Africa/Brazzaville': 'Horário Padrão da África Ocidental',
  'Africa/Bujumbura': 'Horário da África Central',
  'Africa/Cairo': 'Horário Padrão da Europa Oriental',
  'Africa/Casablanca': 'Horário Padrão da Europa Ocidental',
  'Africa/Ceuta': 'Horário Padrão da Europa Central',
  'Africa/Conakry': 'Horário do Meridiano de Greenwich',
  'Africa/Dakar': 'Horário do Meridiano de Greenwich',
  'Africa/Dar_es_Salaam': 'Horário da África Oriental',
  'Africa/Djibouti': 'Horário da África Oriental',
  'Africa/Douala': 'Horário Padrão da África Ocidental',
  'Africa/El_Aaiun': 'Horário Padrão da Europa Ocidental',
  'Africa/Freetown': 'Horário do Meridiano de Greenwich',
  'Africa/Gaborone': 'Horário da África Central',
  'Africa/Harare': 'Horário da África Central',
  'Africa/Johannesburg': 'Horário da África do Sul',
  'Africa/Juba': 'Horário da África Oriental',
  'Africa/Kampala': 'Horário da África Oriental',
  'Africa/Khartoum': 'Horário da África Central',
  'Africa/Kigali': 'Horário da África Central',
  'Africa/Kinshasa': 'Horário Padrão da África Ocidental',
  'Africa/Lagos': 'Horário Padrão da África Ocidental',
  'Africa/Libreville': 'Horário Padrão da África Ocidental',
  'Africa/Lome': 'Horário do Meridiano de Greenwich',
  'Africa/Luanda': 'Horário Padrão da África Ocidental',
  'Africa/Lubumbashi': 'Horário da África Central',
  'Africa/Lusaka': 'Horário da África Central',
  'Africa/Malabo': 'Horário Padrão da África Ocidental',
  'Africa/Maputo': 'Horário da África Central',
  'Africa/Maseru': 'Horário da África do Sul',
  'Africa/Mbabane': 'Horário da África do Sul',
  'Africa/Mogadishu': 'Horário da África Oriental',
  'Africa/Monrovia': 'Horário do Meridiano de Greenwich',
  'Africa/Nairobi': 'Horário da África Oriental',
  'Africa/Ndjamena': 'Horário Padrão da África Ocidental',
  'Africa/Niamey': 'Horário Padrão da África Ocidental',
  'Africa/Nouakchott': 'Horário do Meridiano de Greenwich',
  'Africa/Ouagadougou': 'Horário do Meridiano de Greenwich',
  'Africa/Porto-Novo': 'Horário Padrão da África Ocidental',
  'Africa/Sao_Tome': 'Horário do Meridiano de Greenwich',
  'Africa/Tripoli': 'Horário Padrão da Europa Oriental',
  'Africa/Tunis': 'Horário Padrão da Europa Central',
  'Africa/Windhoek': 'Horário da África Central',
  'America/Adak': 'Horário Padrão do Havaí e Ilhas Aleutas',
  'America/Anchorage': 'Horário Padrão do Alasca',
  'America/Anguilla': 'Horário Padrão do Atlântico',
  'America/Antigua': 'Horário Padrão do Atlântico',
  'America/Araguaina': 'Horário Padrão de Brasília',
  'America/Argentina/Buenos_Aires': 'Horário Padrão da Argentina',
  'America/Argentina/Catamarca': 'Horário Padrão da Argentina',
  'America/Argentina/Cordoba': 'Horário Padrão da Argentina',
  'America/Argentina/Jujuy': 'Horário Padrão da Argentina',
  'America/Argentina/La_Rioja': 'Horário Padrão da Argentina',
  'America/Argentina/Mendoza': 'Horário Padrão da Argentina',
  'America/Argentina/Rio_Gallegos': 'Horário Padrão da Argentina',
  'America/Argentina/Salta': 'Horário Padrão da Argentina',
  'America/Argentina/San_Juan': 'Horário Padrão da Argentina',
  'America/Argentina/San_Luis': 'Horário Padrão da Argentina Ocidental',
  'America/Argentina/Tucuman': 'Horário Padrão da Argentina',
  'America/Argentina/Ushuaia': 'Horário Padrão da Argentina',
  'America/Aruba': 'Horário Padrão do Atlântico',
  'America/Asuncion': 'Horário Padrão do Paraguai',
  'America/Atikokan': 'Horário Padrão do Leste',
  'America/Bahia': 'Horário Padrão de Brasília',
  'America/Bahia_Banderas': 'Horário Padrão Central',
  'America/Barbados': 'Horário Padrão do Atlântico',
  'America/Belem': 'Horário Padrão de Brasília',
  'America/Belize': 'Horário Padrão Central',
  'America/Blanc-Sablon': 'Horário Padrão do Atlântico',
  'America/Boa_Vista': 'Horário Padrão do Amazonas',
  'America/Bogota': 'Horário Padrão da Colômbia',
  'America/Boise': 'Horário Padrão das Montanhas',
  'America/Cambridge_Bay': 'Horário Padrão das Montanhas',
  'America/Campo_Grande': 'Horário Padrão do Amazonas',
  'America/Cancun': 'Horário Padrão do Leste',
  'America/Caracas': 'Horário da Venezuela',
  'America/Cayenne': 'Horário da Guiana Francesa',
  'America/Cayman': 'Horário Padrão do Leste',
  'America/Chicago': 'Horário Padrão Central',
  'America/Chihuahua': 'Horário Padrão do Pacífico Mexicano',
  'America/Costa_Rica': 'Horário Padrão Central',
  'America/Creston': 'Horário Padrão das Montanhas',
  'America/Cuiaba': 'Horário Padrão do Amazonas',
  'America/Curacao': 'Horário Padrão do Atlântico',
  'America/Danmarkshavn': 'Horário do Meridiano de Greenwich',
  'America/Dawson': 'Horário Padrão do Pacífico',
  'America/Dawson_Creek': 'Horário Padrão das Montanhas',
  'America/Denver': 'Horário Padrão das Montanhas',
  'America/Detroit': 'Horário Padrão do Leste',
  'America/Dominica': 'Horário Padrão do Atlântico',
  'America/Edmonton': 'Horário Padrão das Montanhas',
  'America/Eirunepe': 'Horário Padrão do Acre',
  'America/El_Salvador': 'Horário Padrão Central',
  'America/Fort_Nelson': 'Horário Padrão das Montanhas',
  'America/Fortaleza': 'Horário Padrão de Brasília',
  'America/Glace_Bay': 'Horário Padrão do Atlântico',
  'America/Godthab': 'Horário Padrão da Groenlândia Ocidental',
  'America/Goose_Bay': 'Horário Padrão do Atlântico',
  'America/Grand_Turk': 'Horário Padrão do Leste',
  'America/Grenada': 'Horário Padrão do Atlântico',
  'America/Guadeloupe': 'Horário Padrão do Atlântico',
  'America/Guatemala': 'Horário Padrão Central',
  'America/Guayaquil': 'Horário do Equador',
  'America/Guyana': 'Horário da Guiana',
  'America/Halifax': 'Horário Padrão do Atlântico',
  'America/Havana': 'Horário Padrão de Cuba',
  'America/Hermosillo': 'Horário Padrão do Pacífico Mexicano',
  'America/Indiana/Indianapolis': 'Horário Padrão do Leste',
  'America/Indiana/Knox': 'Horário Padrão Central',
  'America/Indiana/Marengo': 'Horário Padrão do Leste',
  'America/Indiana/Petersburg': 'Horário Padrão do Leste',
  'America/Indiana/Tell_City': 'Horário Padrão Central',
  'America/Indiana/Vevay': 'Horário Padrão do Leste',
  'America/Indiana/Vincennes': 'Horário Padrão do Leste',
  'America/Indiana/Winamac': 'Horário Padrão do Leste',
  'America/Inuvik': 'Horário Padrão das Montanhas',
  'America/Iqaluit': 'Horário Padrão do Leste',
  'America/Jamaica': 'Horário Padrão do Leste',
  'America/Juneau': 'Horário Padrão do Alasca',
  'America/Kentucky/Louisville': 'Horário Padrão do Leste',
  'America/Kentucky/Monticello': 'Horário Padrão do Leste',
  'America/Kralendijk': 'Horário Padrão do Atlântico',
  'America/La_Paz': 'Horário da Bolívia',
  'America/Lima': 'Horário Padrão do Peru',
  'America/Los_Angeles': 'Horário Padrão do Pacífico',
  'America/Lower_Princes': 'Horário Padrão do Atlântico',
  'America/Maceio': 'Horário Padrão de Brasília',
  'America/Managua': 'Horário Padrão Central',
  'America/Manaus': 'Horário Padrão do Amazonas',
  'America/Marigot': 'Horário Padrão do Atlântico',
  'America/Martinique': 'Horário Padrão do Atlântico',
  'America/Matamoros': 'Horário Padrão Central',
  'America/Mazatlan': 'Horário Padrão do Pacífico Mexicano',
  'America/Menominee': 'Horário Padrão Central',
  'America/Merida': 'Horário Padrão Central',
  'America/Metlakatla': 'Horário Padrão do Alasca',
  'America/Mexico_City': 'Horário Padrão Central',
  'America/Miquelon': 'Horário Padrão de Saint Pierre e Miquelon',
  'America/Moncton': 'Horário Padrão do Atlântico',
  'America/Monterrey': 'Horário Padrão Central',
  'America/Montevideo': 'Horário Padrão do Uruguai',
  'America/Montserrat': 'Horário Padrão do Atlântico',
  'America/Nassau': 'Horário Padrão do Leste',
  'America/New_York': 'Horário Padrão do Leste',
  'America/Nipigon': 'Horário Padrão do Leste',
  'America/Nome': 'Horário Padrão do Alasca',
  'America/Noronha': 'Horário Padrão de Fernando de Noronha',
  'America/North_Dakota/Beulah': 'Horário Padrão Central',
  'America/North_Dakota/Center': 'Horário Padrão Central',
  'America/North_Dakota/New_Salem': 'Horário Padrão Central',
  'America/Ojinaga': 'Horário Padrão das Montanhas',
  'America/Panama': 'Horário Padrão do Leste',
  'America/Pangnirtung': 'Horário Padrão do Leste',
  'America/Paramaribo': 'Horário do Suriname',
  'America/Phoenix': 'Horário Padrão das Montanhas',
  'America/Port-au-Prince': 'Horário Padrão do Leste',
  'America/Port_of_Spain': 'Horário Padrão do Atlântico',
  'America/Porto_Velho': 'Horário Padrão do Amazonas',
  'America/Puerto_Rico': 'Horário Padrão do Atlântico',
  'America/Punta_Arenas': 'GMT-03:00',
  'America/Rainy_River': 'Horário Padrão Central',
  'America/Rankin_Inlet': 'Horário Padrão Central',
  'America/Recife': 'Horário Padrão de Brasília',
  'America/Regina': 'Horário Padrão Central',
  'America/Resolute': 'Horário Padrão Central',
  'America/Rio_Branco': 'Horário Padrão do Acre',
  'America/Santarem': 'Horário Padrão de Brasília',
  'America/Santiago': 'Horário Padrão do Chile',
  'America/Santo_Domingo': 'Horário Padrão do Atlântico',
  'America/Sao_Paulo': 'Horário Padrão de Brasília',
  'America/Scoresbysund': 'Horário Padrão da Groelândia Oriental',
  'America/Sitka': 'Horário Padrão do Alasca',
  'America/St_Barthelemy': 'Horário Padrão do Atlântico',
  'America/St_Johns': 'Horário Padrão da Terra Nova',
  'America/St_Kitts': 'Horário Padrão do Atlântico',
  'America/St_Lucia': 'Horário Padrão do Atlântico',
  'America/St_Thomas': 'Horário Padrão do Atlântico',
  'America/St_Vincent': 'Horário Padrão do Atlântico',
  'America/Swift_Current': 'Horário Padrão Central',
  'America/Tegucigalpa': 'Horário Padrão Central',
  'America/Thule': 'Horário Padrão do Atlântico',
  'America/Thunder_Bay': 'Horário Padrão do Leste',
  'America/Tijuana': 'Horário Padrão do Pacífico',
  'America/Toronto': 'Horário Padrão do Leste',
  'America/Tortola': 'Horário Padrão do Atlântico',
  'America/Vancouver': 'Horário Padrão do Pacífico',
  'America/Whitehorse': 'Horário Padrão do Pacífico',
  'America/Winnipeg': 'Horário Padrão Central',
  'America/Yakutat': 'Horário Padrão do Alasca',
  'America/Yellowknife': 'Horário Padrão das Montanhas',
  'Antarctica/Casey': 'GMT+11:00',
  'Antarctica/Davis': 'Horário de Davis',
  'Antarctica/DumontDUrville': 'Horário de Dumont-d’Urville',
  'Antarctica/Macquarie': 'Horário da Ilha Macquarie',
  'Antarctica/Mawson': 'Horário de Mawson',
  'Antarctica/McMurdo': 'Horário Padrão da Nova Zelândia',
  'Antarctica/Palmer': 'GMT-03:00',
  'Antarctica/Rothera': 'Horário de Rothera',
  'Antarctica/Syowa': 'Horário de Syowa',
  'Antarctica/Troll': 'Horário do Meridiano de Greenwich',
  'Antarctica/Vostok': 'Horário de Vostok',
  'Arctic/Longyearbyen': 'Horário Padrão da Europa Central',
  'Asia/Aden': 'Horário Padrão da Arábia',
  'Asia/Almaty': 'Horário do Casaquistão Oriental',
  'Asia/Amman': 'Horário Padrão da Europa Oriental',
  'Asia/Anadyr': 'Horário Padrão do Anadyr',
  'Asia/Aqtau': 'Horário do Casaquistão Ocidental',
  'Asia/Aqtobe': 'Horário do Casaquistão Ocidental',
  'Asia/Ashgabat': 'Horário Padrão do Turcomenistão',
  'Asia/Atyrau': 'Horário do Casaquistão Ocidental',
  'Asia/Baghdad': 'Horário Padrão da Arábia',
  'Asia/Bahrain': 'Horário Padrão da Arábia',
  'Asia/Baku': 'Horário Padrão do Arzeibaijão',
  'Asia/Bangkok': 'Horário da Indochina',
  'Asia/Barnaul': 'GMT+07:00',
  'Asia/Beirut': 'Horário Padrão da Europa Oriental',
  'Asia/Bishkek': 'Horário do Quirguistão',
  'Asia/Brunei': 'Horário de Brunei Darussalam',
  'Asia/Chita': 'Horário Padrão de Yakutsk',
  'Asia/Choibalsan': 'Horário Padrão de Choibalsan',
  'Asia/Colombo': 'Horário Padrão da Índia',
  'Asia/Damascus': 'Horário Padrão da Europa Oriental',
  'Asia/Dhaka': 'Horário Padrão de Bangladesh',
  'Asia/Dili': 'Horário do Timor-Leste',
  'Asia/Dubai': 'Horário do Golfo',
  'Asia/Dushanbe': 'Horário do Tajiquistão',
  'Asia/Famagusta': 'GMT+02:00',
  'Asia/Gaza': 'Horário Padrão da Europa Oriental',
  'Asia/Hebron': 'Horário Padrão da Europa Oriental',
  'Asia/Ho_Chi_Minh': 'Horário da Indochina',
  'Asia/Hong_Kong': 'Horário Padrão de Hong Kong',
  'Asia/Hovd': 'Horário Padrão de Hovd',
  'Asia/Irkutsk': 'Horário Padrão de Irkutsk',
  'Asia/Jakarta': 'Horário da Indonésia Ocidental',
  'Asia/Jayapura': 'Horário da Indonésia Oriental',
  'Asia/Jerusalem': 'Horário Padrão de Israel',
  'Asia/Kabul': 'Horário do Afeganistão',
  'Asia/Kamchatka': 'Horário Padrão de Petropavlovsk-Kamchatski',
  'Asia/Karachi': 'Horário Padrão do Paquistão',
  'Asia/Kathmandu': 'Horário do Nepal',
  'Asia/Khandyga': 'Horário Padrão de Yakutsk',
  'Asia/Kolkata': 'Horário Padrão da Índia',
  'Asia/Krasnoyarsk': 'Horário Padrão de Krasnoyarsk',
  'Asia/Kuala_Lumpur': 'Horário da Malásia',
  'Asia/Kuching': 'Horário da Malásia',
  'Asia/Kuwait': 'Horário Padrão da Arábia',
  'Asia/Macau': 'Horário Padrão da China',
  'Asia/Magadan': 'Horário Padrão de Magadan',
  'Asia/Makassar': 'Horário da Indonésia Central',
  'Asia/Manila': 'Horário Padrão das Filipinas',
  'Asia/Muscat': 'Horário do Golfo',
  'Asia/Nicosia': 'Horário Padrão da Europa Oriental',
  'Asia/Novokuznetsk': 'Horário Padrão de Krasnoyarsk',
  'Asia/Novosibirsk': 'Horário Padrão de Novosibirsk',
  'Asia/Omsk': 'Horário Padrão de Omsk',
  'Asia/Oral': 'Horário do Casaquistão Ocidental',
  'Asia/Phnom_Penh': 'Horário da Indochina',
  'Asia/Pontianak': 'Horário da Indonésia Ocidental',
  'Asia/Pyongyang': 'Horário de Pyongyang',
  'Asia/Qatar': 'Horário Padrão da Arábia',
  'Asia/Qyzylorda': 'Horário do Casaquistão Oriental',
  'Asia/Riyadh': 'Horário Padrão da Arábia',
  'Asia/Sakhalin': 'Horário Padrão de Sacalina',
  'Asia/Samarkand': 'Horário Padrão do Uzbequistão',
  'Asia/Seoul': 'Horário Padrão da Coreia',
  'Asia/Shanghai': 'Horário Padrão da China',
  'Asia/Singapore': 'Horário Padrão de Cingapura',
  'Asia/Srednekolymsk': 'GMT+11:00',
  'Asia/Taipei': 'Horário Padrão de Taipei',
  'Asia/Tashkent': 'Horário Padrão do Uzbequistão',
  'Asia/Tbilisi': 'Horário Padrão da Geórgia',
  'Asia/Tehran': 'Horário Padrão do Irã',
  'Asia/Thimphu': 'Horário do Butão',
  'Asia/Tokyo': 'Horário Padrão do Japão',
  'Asia/Tomsk': 'GMT+07:00',
  'Asia/Ulaanbaatar': 'Horário Padrão de Ulan Bator',
  'Asia/Urumqi': 'GMT+06:00',
  'Asia/Ust-Nera': 'Horário Padrão de Vladivostok',
  'Asia/Vientiane': 'Horário da Indochina',
  'Asia/Vladivostok': 'Horário Padrão de Vladivostok',
  'Asia/Yakutsk': 'Horário Padrão de Yakutsk',
  'Asia/Yangon': 'Horário de Mianmar',
  'Asia/Yekaterinburg': 'Horário Padrão de Ecaterimburgo',
  'Asia/Yerevan': 'Horário Padrão da Armênia',
  'Atlantic/Azores': 'Horário Padrão dos Açores',
  'Atlantic/Bermuda': 'Horário Padrão do Atlântico',
  'Atlantic/Canary': 'Horário Padrão da Europa Ocidental',
  'Atlantic/Cape_Verde': 'Horário Padrão de Cabo Verde',
  'Atlantic/Faroe': 'Horário Padrão da Europa Ocidental',
  'Atlantic/Madeira': 'Horário Padrão da Europa Ocidental',
  'Atlantic/Reykjavik': 'Horário do Meridiano de Greenwich',
  'Atlantic/South_Georgia': 'Horário da Geórgia do Sul',
  'Atlantic/St_Helena': 'Horário do Meridiano de Greenwich',
  'Atlantic/Stanley': 'Horário Padrão das Ilhas Malvinas',
  'Australia/Adelaide': 'Horário Padrão da Austrália Central',
  'Australia/Brisbane': 'Horário Padrão da Austrália Oriental',
  'Australia/Broken_Hill': 'Horário Padrão da Austrália Central',
  'Australia/Currie': 'Horário Padrão da Austrália Oriental',
  'Australia/Darwin': 'Horário Padrão da Austrália Central',
  'Australia/Eucla': 'Horário Padrão da Austrália Centro-Ocidental',
  'Australia/Hobart': 'Horário Padrão da Austrália Oriental',
  'Australia/Lindeman': 'Horário Padrão da Austrália Oriental',
  'Australia/Lord_Howe': 'Horário Padrão de Lord Howe',
  'Australia/Melbourne': 'Horário Padrão da Austrália Oriental',
  'Australia/Perth': 'Horário Padrão da Austrália Ocidental',
  'Australia/Sydney': 'Horário Padrão da Austrália Oriental',
  'Europe/Amsterdam': 'Horário Padrão da Europa Central',
  'Europe/Andorra': 'Horário Padrão da Europa Central',
  'Europe/Astrakhan': 'GMT+04:00',
  'Europe/Athens': 'Horário Padrão da Europa Oriental',
  'Europe/Belgrade': 'Horário Padrão da Europa Central',
  'Europe/Berlin': 'Horário Padrão da Europa Central',
  'Europe/Bratislava': 'Horário Padrão da Europa Central',
  'Europe/Brussels': 'Horário Padrão da Europa Central',
  'Europe/Bucharest': 'Horário Padrão da Europa Oriental',
  'Europe/Budapest': 'Horário Padrão da Europa Central',
  'Europe/Busingen': 'Horário Padrão da Europa Central',
  'Europe/Chisinau': 'Horário Padrão da Europa Oriental',
  'Europe/Copenhagen': 'Horário Padrão da Europa Central',
  'Europe/Dublin': 'Horário do Meridiano de Greenwich',
  'Europe/Gibraltar': 'Horário Padrão da Europa Central',
  'Europe/Guernsey': 'Horário do Meridiano de Greenwich',
  'Europe/Helsinki': 'Horário Padrão da Europa Oriental',
  'Europe/Isle_of_Man': 'Horário do Meridiano de Greenwich',
  'Europe/Istanbul': 'GMT+03:00',
  'Europe/Jersey': 'Horário do Meridiano de Greenwich',
  'Europe/Kaliningrad': 'Horário Padrão da Europa Oriental',
  'Europe/Kiev': 'Horário Padrão da Europa Oriental',
  'Europe/Kirov': 'GMT+03:00',
  'Europe/Lisbon': 'Horário Padrão da Europa Ocidental',
  'Europe/Ljubljana': 'Horário Padrão da Europa Central',
  'Europe/London': 'Horário do Meridiano de Greenwich',
  'Europe/Luxembourg': 'Horário Padrão da Europa Central',
  'Europe/Madrid': 'Horário Padrão da Europa Central',
  'Europe/Malta': 'Horário Padrão da Europa Central',
  'Europe/Mariehamn': 'Horário Padrão da Europa Oriental',
  'Europe/Minsk': 'Horário Padrão de Moscou',
  'Europe/Monaco': 'Horário Padrão da Europa Central',
  'Europe/Moscow': 'Horário Padrão de Moscou',
  'Europe/Oslo': 'Horário Padrão da Europa Central',
  'Europe/Paris': 'Horário Padrão da Europa Central',
  'Europe/Podgorica': 'Horário Padrão da Europa Central',
  'Europe/Prague': 'Horário Padrão da Europa Central',
  'Europe/Riga': 'Horário Padrão da Europa Oriental',
  'Europe/Rome': 'Horário Padrão da Europa Central',
  'Europe/Samara': 'Horário Padrão de Samara',
  'Europe/San_Marino': 'Horário Padrão da Europa Central',
  'Europe/Sarajevo': 'Horário Padrão da Europa Central',
  'Europe/Saratov': 'GMT+04:00',
  'Europe/Simferopol': 'Horário Padrão de Moscou',
  'Europe/Skopje': 'Horário Padrão da Europa Central',
  'Europe/Sofia': 'Horário Padrão da Europa Oriental',
  'Europe/Stockholm': 'Horário Padrão da Europa Central',
  'Europe/Tallinn': 'Horário Padrão da Europa Oriental',
  'Europe/Tirane': 'Horário Padrão da Europa Central',
  'Europe/Ulyanovsk': 'GMT+04:00',
  'Europe/Uzhgorod': 'Horário Padrão da Europa Oriental',
  'Europe/Vaduz': 'Horário Padrão da Europa Central',
  'Europe/Vatican': 'Horário Padrão da Europa Central',
  'Europe/Vienna': 'Horário Padrão da Europa Central',
  'Europe/Vilnius': 'Horário Padrão da Europa Oriental',
  'Europe/Volgograd': 'Horário Padrão de Moscou',
  'Europe/Warsaw': 'Horário Padrão da Europa Central',
  'Europe/Zagreb': 'Horário Padrão da Europa Central',
  'Europe/Zaporozhye': 'Horário Padrão da Europa Oriental',
  'Europe/Zurich': 'Horário Padrão da Europa Central',
  'Indian/Antananarivo': 'Horário da África Oriental',
  'Indian/Chagos': 'Horário do Oceano Índico',
  'Indian/Christmas': 'Horário da Ilha Christmas',
  'Indian/Cocos': 'Horário das Ilhas Coco',
  'Indian/Comoro': 'Horário da África Oriental',
  'Indian/Kerguelen': 'Horário da Antártida e do Sul da França',
  'Indian/Mahe': 'Horário de Seicheles',
  'Indian/Maldives': 'Horário das Ilhas Maldivas',
  'Indian/Mauritius': 'Horário Padrão de Maurício',
  'Indian/Mayotte': 'Horário da África Oriental',
  'Indian/Reunion': 'Horário de Reunião',
  'Pacific/Apia': 'Horário Padrão de Apia',
  'Pacific/Auckland': 'Horário Padrão da Nova Zelândia',
  'Pacific/Bougainville': 'GMT+11:00',
  'Pacific/Chatham': 'Horário Padrão de Chatham',
  'Pacific/Chuuk': 'Horário de Chuuk',
  'Pacific/Easter': 'Horário Padrão da Ilha de Páscoa',
  'Pacific/Efate': 'Horário Padrão de Vanuatu',
  'Pacific/Enderbury': 'Horário das Ilhas Fênix',
  'Pacific/Fakaofo': 'Horário de Tokelau',
  'Pacific/Fiji': 'Horário Padrão de Fiji',
  'Pacific/Funafuti': 'Horário de Tuvalu',
  'Pacific/Galapagos': 'Horário de Galápagos',
  'Pacific/Gambier': 'Horário de Gambier',
  'Pacific/Guadalcanal': 'Horário das Ilhas Salomão',
  'Pacific/Guam': 'Horário de Chamorro',
  'Pacific/Honolulu': 'Horário Padrão do Havaí e Ilhas Aleutas',
  'Pacific/Kiritimati': 'Horário das Ilhas Line',
  'Pacific/Kosrae': 'Horário de Kosrae',
  'Pacific/Kwajalein': 'Horário das Ilhas Marshall',
  'Pacific/Majuro': 'Horário das Ilhas Marshall',
  'Pacific/Marquesas': 'Horário das Marquesas',
  'Pacific/Midway': 'Horário Padrão de Samoa',
  'Pacific/Nauru': 'Horário de Nauru',
  'Pacific/Niue': 'Horário de Niue',
  'Pacific/Norfolk': 'Horário da Ilha Norfolk',
  'Pacific/Noumea': 'Horário Padrão da Nova Caledônia',
  'Pacific/Pago_Pago': 'Horário Padrão de Samoa',
  'Pacific/Palau': 'Horário de Palau',
  'Pacific/Pitcairn': 'Horário de Pitcairn',
  'Pacific/Pohnpei': 'Horário de Ponape',
  'Pacific/Port_Moresby': 'Horário de Papua Nova Guiné',
  'Pacific/Rarotonga': 'Horário Padrão das Ilhas Cook',
  'Pacific/Saipan': 'Horário de Chamorro',
  'Pacific/Tahiti': 'Horário do Taiti',
  'Pacific/Tarawa': 'Horário das Ilhas Gilberto',
  'Pacific/Tongatapu': 'Horário Padrão de Tonga',
  'Pacific/Wake': 'Horário das Ilhas Wake',
  'Pacific/Wallis': 'Horário de Wallis e Futuna',
  UTC: 'Horário Universal Coordenado',
};
