module.exports = {
  'Africa/Abidjan': 'Среднее время по Гринвичу',
  'Africa/Accra': 'Среднее время по Гринвичу',
  'Africa/Addis_Ababa': 'Восточная Африка',
  'Africa/Algiers': 'Центральная Европа, стандартное время',
  'Africa/Asmara': 'Восточная Африка',
  'Africa/Bamako': 'Среднее время по Гринвичу',
  'Africa/Bangui': 'Западная Африка, стандартное время',
  'Africa/Banjul': 'Среднее время по Гринвичу',
  'Africa/Bissau': 'Среднее время по Гринвичу',
  'Africa/Blantyre': 'Центральная Африка',
  'Africa/Brazzaville': 'Западная Африка, стандартное время',
  'Africa/Bujumbura': 'Центральная Африка',
  'Africa/Cairo': 'Восточная Европа, стандартное время',
  'Africa/Casablanca': 'Западная Европа, стандартное время',
  'Africa/Ceuta': 'Центральная Европа, стандартное время',
  'Africa/Conakry': 'Среднее время по Гринвичу',
  'Africa/Dakar': 'Среднее время по Гринвичу',
  'Africa/Dar_es_Salaam': 'Восточная Африка',
  'Africa/Djibouti': 'Восточная Африка',
  'Africa/Douala': 'Западная Африка, стандартное время',
  'Africa/El_Aaiun': 'Западная Европа, стандартное время',
  'Africa/Freetown': 'Среднее время по Гринвичу',
  'Africa/Gaborone': 'Центральная Африка',
  'Africa/Harare': 'Центральная Африка',
  'Africa/Johannesburg': 'Южная Африка',
  'Africa/Juba': 'Восточная Африка',
  'Africa/Kampala': 'Восточная Африка',
  'Africa/Khartoum': 'Центральная Африка',
  'Africa/Kigali': 'Центральная Африка',
  'Africa/Kinshasa': 'Западная Африка, стандартное время',
  'Africa/Lagos': 'Западная Африка, стандартное время',
  'Africa/Libreville': 'Западная Африка, стандартное время',
  'Africa/Lome': 'Среднее время по Гринвичу',
  'Africa/Luanda': 'Западная Африка, стандартное время',
  'Africa/Lubumbashi': 'Центральная Африка',
  'Africa/Lusaka': 'Центральная Африка',
  'Africa/Malabo': 'Западная Африка, стандартное время',
  'Africa/Maputo': 'Центральная Африка',
  'Africa/Maseru': 'Южная Африка',
  'Africa/Mbabane': 'Южная Африка',
  'Africa/Mogadishu': 'Восточная Африка',
  'Africa/Monrovia': 'Среднее время по Гринвичу',
  'Africa/Nairobi': 'Восточная Африка',
  'Africa/Ndjamena': 'Западная Африка, стандартное время',
  'Africa/Niamey': 'Западная Африка, стандартное время',
  'Africa/Nouakchott': 'Среднее время по Гринвичу',
  'Africa/Ouagadougou': 'Среднее время по Гринвичу',
  'Africa/Porto-Novo': 'Западная Африка, стандартное время',
  'Africa/Sao_Tome': 'Среднее время по Гринвичу',
  'Africa/Tripoli': 'Восточная Европа, стандартное время',
  'Africa/Tunis': 'Центральная Европа, стандартное время',
  'Africa/Windhoek': 'Центральная Африка',
  'America/Adak': 'Гавайско-алеутское стандартное время',
  'America/Anchorage': 'Аляска, стандартное время',
  'America/Anguilla': 'Атлантическое стандартное время',
  'America/Antigua': 'Атлантическое стандартное время',
  'America/Araguaina': 'Бразилия, стандартное время',
  'America/Argentina/Buenos_Aires': 'Аргентина, стандартное время',
  'America/Argentina/Catamarca': 'Аргентина, стандартное время',
  'America/Argentina/Cordoba': 'Аргентина, стандартное время',
  'America/Argentina/Jujuy': 'Аргентина, стандартное время',
  'America/Argentina/La_Rioja': 'Аргентина, стандартное время',
  'America/Argentina/Mendoza': 'Аргентина, стандартное время',
  'America/Argentina/Rio_Gallegos': 'Аргентина, стандартное время',
  'America/Argentina/Salta': 'Аргентина, стандартное время',
  'America/Argentina/San_Juan': 'Аргентина, стандартное время',
  'America/Argentina/San_Luis': 'Западная Аргентина, стандартное время',
  'America/Argentina/Tucuman': 'Аргентина, стандартное время',
  'America/Argentina/Ushuaia': 'Аргентина, стандартное время',
  'America/Aruba': 'Атлантическое стандартное время',
  'America/Asuncion': 'Парагвай, стандартное время',
  'America/Atikokan': 'Восточная Америка, стандартное время',
  'America/Bahia': 'Бразилия, стандартное время',
  'America/Bahia_Banderas': 'Центральная Америка, стандартное время',
  'America/Barbados': 'Атлантическое стандартное время',
  'America/Belem': 'Бразилия, стандартное время',
  'America/Belize': 'Центральная Америка, стандартное время',
  'America/Blanc-Sablon': 'Атлантическое стандартное время',
  'America/Boa_Vista': 'Амазонка, стандартное время',
  'America/Bogota': 'Колумбия, стандартное время',
  'America/Boise': 'Стандартное горное время (Северная Америка)',
  'America/Cambridge_Bay': 'Стандартное горное время (Северная Америка)',
  'America/Campo_Grande': 'Амазонка, стандартное время',
  'America/Cancun': 'Восточная Америка, стандартное время',
  'America/Caracas': 'Венесуэла',
  'America/Cayenne': 'Французская Гвиана',
  'America/Cayman': 'Восточная Америка, стандартное время',
  'America/Chicago': 'Центральная Америка, стандартное время',
  'America/Chihuahua': 'Тихоокеанское мексиканское стандартное время',
  'America/Costa_Rica': 'Центральная Америка, стандартное время',
  'America/Creston': 'Стандартное горное время (Северная Америка)',
  'America/Cuiaba': 'Амазонка, стандартное время',
  'America/Curacao': 'Атлантическое стандартное время',
  'America/Danmarkshavn': 'Среднее время по Гринвичу',
  'America/Dawson': 'Тихоокеанское стандартное время',
  'America/Dawson_Creek': 'Стандартное горное время (Северная Америка)',
  'America/Denver': 'Стандартное горное время (Северная Америка)',
  'America/Detroit': 'Восточная Америка, стандартное время',
  'America/Dominica': 'Атлантическое стандартное время',
  'America/Edmonton': 'Стандартное горное время (Северная Америка)',
  'America/Eirunepe': 'Акри стандартное время',
  'America/El_Salvador': 'Центральная Америка, стандартное время',
  'America/Fort_Nelson': 'Стандартное горное время (Северная Америка)',
  'America/Fortaleza': 'Бразилия, стандартное время',
  'America/Glace_Bay': 'Атлантическое стандартное время',
  'America/Godthab': 'Западная Гренландия, стандартное время',
  'America/Goose_Bay': 'Атлантическое стандартное время',
  'America/Grand_Turk': 'Восточная Америка, стандартное время',
  'America/Grenada': 'Атлантическое стандартное время',
  'America/Guadeloupe': 'Атлантическое стандартное время',
  'America/Guatemala': 'Центральная Америка, стандартное время',
  'America/Guayaquil': 'Эквадор',
  'America/Guyana': 'Гайана',
  'America/Halifax': 'Атлантическое стандартное время',
  'America/Havana': 'Куба, стандартное время',
  'America/Hermosillo': 'Тихоокеанское мексиканское стандартное время',
  'America/Indiana/Indianapolis': 'Восточная Америка, стандартное время',
  'America/Indiana/Knox': 'Центральная Америка, стандартное время',
  'America/Indiana/Marengo': 'Восточная Америка, стандартное время',
  'America/Indiana/Petersburg': 'Восточная Америка, стандартное время',
  'America/Indiana/Tell_City': 'Центральная Америка, стандартное время',
  'America/Indiana/Vevay': 'Восточная Америка, стандартное время',
  'America/Indiana/Vincennes': 'Восточная Америка, стандартное время',
  'America/Indiana/Winamac': 'Восточная Америка, стандартное время',
  'America/Inuvik': 'Стандартное горное время (Северная Америка)',
  'America/Iqaluit': 'Восточная Америка, стандартное время',
  'America/Jamaica': 'Восточная Америка, стандартное время',
  'America/Juneau': 'Аляска, стандартное время',
  'America/Kentucky/Louisville': 'Восточная Америка, стандартное время',
  'America/Kentucky/Monticello': 'Восточная Америка, стандартное время',
  'America/Kralendijk': 'Атлантическое стандартное время',
  'America/La_Paz': 'Боливия',
  'America/Lima': 'Перу, стандартное время',
  'America/Los_Angeles': 'Тихоокеанское стандартное время',
  'America/Lower_Princes': 'Атлантическое стандартное время',
  'America/Maceio': 'Бразилия, стандартное время',
  'America/Managua': 'Центральная Америка, стандартное время',
  'America/Manaus': 'Амазонка, стандартное время',
  'America/Marigot': 'Атлантическое стандартное время',
  'America/Martinique': 'Атлантическое стандартное время',
  'America/Matamoros': 'Центральная Америка, стандартное время',
  'America/Mazatlan': 'Тихоокеанское мексиканское стандартное время',
  'America/Menominee': 'Центральная Америка, стандартное время',
  'America/Merida': 'Центральная Америка, стандартное время',
  'America/Metlakatla': 'Аляска, стандартное время',
  'America/Mexico_City': 'Центральная Америка, стандартное время',
  'America/Miquelon': 'Сен-Пьер и Микелон, стандартное время',
  'America/Moncton': 'Атлантическое стандартное время',
  'America/Monterrey': 'Центральная Америка, стандартное время',
  'America/Montevideo': 'Уругвай, стандартное время',
  'America/Montserrat': 'Атлантическое стандартное время',
  'America/Nassau': 'Восточная Америка, стандартное время',
  'America/New_York': 'Восточная Америка, стандартное время',
  'America/Nipigon': 'Восточная Америка, стандартное время',
  'America/Nome': 'Аляска, стандартное время',
  'America/Noronha': 'Фернанду-ди-Норонья, стандартное время',
  'America/North_Dakota/Beulah': 'Центральная Америка, стандартное время',
  'America/North_Dakota/Center': 'Центральная Америка, стандартное время',
  'America/North_Dakota/New_Salem': 'Центральная Америка, стандартное время',
  'America/Ojinaga': 'Стандартное горное время (Северная Америка)',
  'America/Panama': 'Восточная Америка, стандартное время',
  'America/Pangnirtung': 'Восточная Америка, стандартное время',
  'America/Paramaribo': 'Суринам',
  'America/Phoenix': 'Стандартное горное время (Северная Америка)',
  'America/Port-au-Prince': 'Восточная Америка, стандартное время',
  'America/Port_of_Spain': 'Атлантическое стандартное время',
  'America/Porto_Velho': 'Амазонка, стандартное время',
  'America/Puerto_Rico': 'Атлантическое стандартное время',
  'America/Punta_Arenas': 'GMT-03:00',
  'America/Rainy_River': 'Центральная Америка, стандартное время',
  'America/Rankin_Inlet': 'Центральная Америка, стандартное время',
  'America/Recife': 'Бразилия, стандартное время',
  'America/Regina': 'Центральная Америка, стандартное время',
  'America/Resolute': 'Центральная Америка, стандартное время',
  'America/Rio_Branco': 'Акри стандартное время',
  'America/Santarem': 'Бразилия, стандартное время',
  'America/Santiago': 'Чили, стандартное время',
  'America/Santo_Domingo': 'Атлантическое стандартное время',
  'America/Sao_Paulo': 'Бразилия, стандартное время',
  'America/Scoresbysund': 'Восточная Гренландия, стандарное время',
  'America/Sitka': 'Аляска, стандартное время',
  'America/St_Barthelemy': 'Атлантическое стандартное время',
  'America/St_Johns': 'Ньюфаундленд, стандартное время',
  'America/St_Kitts': 'Атлантическое стандартное время',
  'America/St_Lucia': 'Атлантическое стандартное время',
  'America/St_Thomas': 'Атлантическое стандартное время',
  'America/St_Vincent': 'Атлантическое стандартное время',
  'America/Swift_Current': 'Центральная Америка, стандартное время',
  'America/Tegucigalpa': 'Центральная Америка, стандартное время',
  'America/Thule': 'Атлантическое стандартное время',
  'America/Thunder_Bay': 'Восточная Америка, стандартное время',
  'America/Tijuana': 'Тихоокеанское стандартное время',
  'America/Toronto': 'Восточная Америка, стандартное время',
  'America/Tortola': 'Атлантическое стандартное время',
  'America/Vancouver': 'Тихоокеанское стандартное время',
  'America/Whitehorse': 'Тихоокеанское стандартное время',
  'America/Winnipeg': 'Центральная Америка, стандартное время',
  'America/Yakutat': 'Аляска, стандартное время',
  'America/Yellowknife': 'Стандартное горное время (Северная Америка)',
  'Antarctica/Casey': 'Кейси',
  'Antarctica/Davis': 'Дейвис',
  'Antarctica/DumontDUrville': 'Дюмон-д’Юрвиль',
  'Antarctica/Macquarie': 'Маккуори',
  'Antarctica/Mawson': 'Моусон',
  'Antarctica/McMurdo': 'Новая Зеландия, стандартное время',
  'Antarctica/Palmer': 'GMT-03:00',
  'Antarctica/Rothera': 'Ротера',
  'Antarctica/Syowa': 'Сёва',
  'Antarctica/Troll': 'Среднее время по Гринвичу',
  'Antarctica/Vostok': 'Восток',
  'Arctic/Longyearbyen': 'Центральная Европа, стандартное время',
  'Asia/Aden': 'Саудовская Аравия, стандартное время',
  'Asia/Almaty': 'Восточный Казахстан',
  'Asia/Amman': 'Восточная Европа, стандартное время',
  'Asia/Anadyr': 'Анадырь стандартное время',
  'Asia/Aqtau': 'Западный Казахстан',
  'Asia/Aqtobe': 'Западный Казахстан',
  'Asia/Ashgabat': 'Туркмения, стандартное время',
  'Asia/Atyrau': 'Западный Казахстан',
  'Asia/Baghdad': 'Саудовская Аравия, стандартное время',
  'Asia/Bahrain': 'Саудовская Аравия, стандартное время',
  'Asia/Baku': 'Азербайджан, стандартное время',
  'Asia/Bangkok': 'Индокитай',
  'Asia/Barnaul': 'GMT+07:00',
  'Asia/Beirut': 'Восточная Европа, стандартное время',
  'Asia/Bishkek': 'Киргизия',
  'Asia/Brunei': 'Бруней-Даруссалам',
  'Asia/Chita': 'Якутск, стандартное время',
  'Asia/Choibalsan': 'Чойбалсан, стандартное время',
  'Asia/Colombo': 'Индия',
  'Asia/Damascus': 'Восточная Европа, стандартное время',
  'Asia/Dhaka': 'Бангладеш, стандартное время',
  'Asia/Dili': 'Восточный Тимор',
  'Asia/Dubai': 'Персидский залив',
  'Asia/Dushanbe': 'Таджикистан',
  'Asia/Famagusta': 'GMT+02:00',
  'Asia/Gaza': 'Восточная Европа, стандартное время',
  'Asia/Hebron': 'Восточная Европа, стандартное время',
  'Asia/Ho_Chi_Minh': 'Индокитай',
  'Asia/Hong_Kong': 'Гонконг, стандартное время',
  'Asia/Hovd': 'Ховд, стандартное время',
  'Asia/Irkutsk': 'Иркутск, стандартное время',
  'Asia/Jakarta': 'Западная Индонезия',
  'Asia/Jayapura': 'Восточная Индонезия',
  'Asia/Jerusalem': 'Израиль, стандартное время',
  'Asia/Kabul': 'Афганистан',
  'Asia/Kamchatka': 'Петропавловск-Камчатский, стандартное время',
  'Asia/Karachi': 'Пакистан, стандартное время',
  'Asia/Kathmandu': 'Непал',
  'Asia/Khandyga': 'Якутск, стандартное время',
  'Asia/Kolkata': 'Индия',
  'Asia/Krasnoyarsk': 'Красноярск, стандартное время',
  'Asia/Kuala_Lumpur': 'Малайзия',
  'Asia/Kuching': 'Малайзия',
  'Asia/Kuwait': 'Саудовская Аравия, стандартное время',
  'Asia/Macau': 'Китай, стандартное время',
  'Asia/Magadan': 'Магадан, стандартное время',
  'Asia/Makassar': 'Центральная Индонезия',
  'Asia/Manila': 'Филиппины, стандартное время',
  'Asia/Muscat': 'Персидский залив',
  'Asia/Nicosia': 'Восточная Европа, стандартное время',
  'Asia/Novokuznetsk': 'Красноярск, стандартное время',
  'Asia/Novosibirsk': 'Новосибирск, стандартное время',
  'Asia/Omsk': 'Омск, стандартное время',
  'Asia/Oral': 'Западный Казахстан',
  'Asia/Phnom_Penh': 'Индокитай',
  'Asia/Pontianak': 'Западная Индонезия',
  'Asia/Pyongyang': 'Пхеньян',
  'Asia/Qatar': 'Саудовская Аравия, стандартное время',
  'Asia/Qyzylorda': 'Восточный Казахстан',
  'Asia/Riyadh': 'Саудовская Аравия, стандартное время',
  'Asia/Sakhalin': 'Сахалин, стандартное время',
  'Asia/Samarkand': 'Узбекистан, стандартное время',
  'Asia/Seoul': 'Корея, стандартное время',
  'Asia/Shanghai': 'Китай, стандартное время',
  'Asia/Singapore': 'Сингапур',
  'Asia/Srednekolymsk': 'GMT+11:00',
  'Asia/Taipei': 'Тайвань, стандартное время',
  'Asia/Tashkent': 'Узбекистан, стандартное время',
  'Asia/Tbilisi': 'Грузия, стандартное время',
  'Asia/Tehran': 'Иран, стандартное время',
  'Asia/Thimphu': 'Бутан',
  'Asia/Tokyo': 'Япония, стандартное время',
  'Asia/Tomsk': 'GMT+07:00',
  'Asia/Ulaanbaatar': 'Улан-Батор, стандартное время',
  'Asia/Urumqi': 'GMT+06:00',
  'Asia/Ust-Nera': 'Владивосток, стандартное время',
  'Asia/Vientiane': 'Индокитай',
  'Asia/Vladivostok': 'Владивосток, стандартное время',
  'Asia/Yakutsk': 'Якутск, стандартное время',
  'Asia/Yangon': 'Мьянма',
  'Asia/Yekaterinburg': 'Екатеринбург, стандартное время',
  'Asia/Yerevan': 'Армения, стандартное время',
  'Atlantic/Azores': 'Азорские о-ва, стандартное время',
  'Atlantic/Bermuda': 'Атлантическое стандартное время',
  'Atlantic/Canary': 'Западная Европа, стандартное время',
  'Atlantic/Cape_Verde': 'Кабо-Верде, стандартное время',
  'Atlantic/Faroe': 'Западная Европа, стандартное время',
  'Atlantic/Madeira': 'Западная Европа, стандартное время',
  'Atlantic/Reykjavik': 'Среднее время по Гринвичу',
  'Atlantic/South_Georgia': 'Южная Георгия',
  'Atlantic/St_Helena': 'Среднее время по Гринвичу',
  'Atlantic/Stanley': 'Фолклендские о-ва, стандартное время',
  'Australia/Adelaide': 'Центральная Австралия, стандартное время',
  'Australia/Brisbane': 'Восточная Австралия, стандартное время',
  'Australia/Broken_Hill': 'Центральная Австралия, стандартное время',
  'Australia/Currie': 'Восточная Австралия, стандартное время',
  'Australia/Darwin': 'Центральная Австралия, стандартное время',
  'Australia/Eucla': 'Центральная Австралия, западное стандартное время',
  'Australia/Hobart': 'Восточная Австралия, стандартное время',
  'Australia/Lindeman': 'Восточная Австралия, стандартное время',
  'Australia/Lord_Howe': 'Лорд-Хау, стандартное время',
  'Australia/Melbourne': 'Восточная Австралия, стандартное время',
  'Australia/Perth': 'Западная Австралия, стандартное время',
  'Australia/Sydney': 'Восточная Австралия, стандартное время',
  'Europe/Amsterdam': 'Центральная Европа, стандартное время',
  'Europe/Andorra': 'Центральная Европа, стандартное время',
  'Europe/Astrakhan': 'GMT+04:00',
  'Europe/Athens': 'Восточная Европа, стандартное время',
  'Europe/Belgrade': 'Центральная Европа, стандартное время',
  'Europe/Berlin': 'Центральная Европа, стандартное время',
  'Europe/Bratislava': 'Центральная Европа, стандартное время',
  'Europe/Brussels': 'Центральная Европа, стандартное время',
  'Europe/Bucharest': 'Восточная Европа, стандартное время',
  'Europe/Budapest': 'Центральная Европа, стандартное время',
  'Europe/Busingen': 'Центральная Европа, стандартное время',
  'Europe/Chisinau': 'Восточная Европа, стандартное время',
  'Europe/Copenhagen': 'Центральная Европа, стандартное время',
  'Europe/Dublin': 'Среднее время по Гринвичу',
  'Europe/Gibraltar': 'Центральная Европа, стандартное время',
  'Europe/Guernsey': 'Среднее время по Гринвичу',
  'Europe/Helsinki': 'Восточная Европа, стандартное время',
  'Europe/Isle_of_Man': 'Среднее время по Гринвичу',
  'Europe/Istanbul': 'GMT+03:00',
  'Europe/Jersey': 'Среднее время по Гринвичу',
  'Europe/Kaliningrad': 'Восточная Европа, стандартное время',
  'Europe/Kiev': 'Восточная Европа, стандартное время',
  'Europe/Kirov': 'GMT+03:00',
  'Europe/Lisbon': 'Западная Европа, стандартное время',
  'Europe/Ljubljana': 'Центральная Европа, стандартное время',
  'Europe/London': 'Среднее время по Гринвичу',
  'Europe/Luxembourg': 'Центральная Европа, стандартное время',
  'Europe/Madrid': 'Центральная Европа, стандартное время',
  'Europe/Malta': 'Центральная Европа, стандартное время',
  'Europe/Mariehamn': 'Восточная Европа, стандартное время',
  'Europe/Minsk': 'Москва, стандартное время',
  'Europe/Monaco': 'Центральная Европа, стандартное время',
  'Europe/Moscow': 'Москва, стандартное время',
  'Europe/Oslo': 'Центральная Европа, стандартное время',
  'Europe/Paris': 'Центральная Европа, стандартное время',
  'Europe/Podgorica': 'Центральная Европа, стандартное время',
  'Europe/Prague': 'Центральная Европа, стандартное время',
  'Europe/Riga': 'Восточная Европа, стандартное время',
  'Europe/Rome': 'Центральная Европа, стандартное время',
  'Europe/Samara': 'Самарское стандартное время',
  'Europe/San_Marino': 'Центральная Европа, стандартное время',
  'Europe/Sarajevo': 'Центральная Европа, стандартное время',
  'Europe/Saratov': 'GMT+04:00',
  'Europe/Simferopol': 'Москва, стандартное время',
  'Europe/Skopje': 'Центральная Европа, стандартное время',
  'Europe/Sofia': 'Восточная Европа, стандартное время',
  'Europe/Stockholm': 'Центральная Европа, стандартное время',
  'Europe/Tallinn': 'Восточная Европа, стандартное время',
  'Europe/Tirane': 'Центральная Европа, стандартное время',
  'Europe/Ulyanovsk': 'GMT+04:00',
  'Europe/Uzhgorod': 'Восточная Европа, стандартное время',
  'Europe/Vaduz': 'Центральная Европа, стандартное время',
  'Europe/Vatican': 'Центральная Европа, стандартное время',
  'Europe/Vienna': 'Центральная Европа, стандартное время',
  'Europe/Vilnius': 'Восточная Европа, стандартное время',
  'Europe/Volgograd': 'Москва, стандартное время',
  'Europe/Warsaw': 'Центральная Европа, стандартное время',
  'Europe/Zagreb': 'Центральная Европа, стандартное время',
  'Europe/Zaporozhye': 'Восточная Европа, стандартное время',
  'Europe/Zurich': 'Центральная Европа, стандартное время',
  'Indian/Antananarivo': 'Восточная Африка',
  'Indian/Chagos': 'Индийский океан',
  'Indian/Christmas': 'о-в Рождества',
  'Indian/Cocos': 'Кокосовые о-ва',
  'Indian/Comoro': 'Восточная Африка',
  'Indian/Kerguelen': 'Французские Южные и Антарктические территории',
  'Indian/Mahe': 'Сейшельские острова',
  'Indian/Maldives': 'Мальдивы',
  'Indian/Mauritius': 'Маврикий, стандартное время',
  'Indian/Mayotte': 'Восточная Африка',
  'Indian/Reunion': 'Реюньон',
  'Pacific/Apia': 'Апиа, стандартное время',
  'Pacific/Auckland': 'Новая Зеландия, стандартное время',
  'Pacific/Bougainville': 'GMT+11:00',
  'Pacific/Chatham': 'Чатем, стандартное время',
  'Pacific/Chuuk': 'Трук',
  'Pacific/Easter': 'О-в Пасхи, стандартное время',
  'Pacific/Efate': 'Вануату, стандартное время',
  'Pacific/Enderbury': 'о-ва Феникс',
  'Pacific/Fakaofo': 'Токелау',
  'Pacific/Fiji': 'Фиджи, стандартное время',
  'Pacific/Funafuti': 'Тувалу',
  'Pacific/Galapagos': 'Галапагосские о-ва',
  'Pacific/Gambier': 'Гамбье',
  'Pacific/Guadalcanal': 'Соломоновы острова',
  'Pacific/Guam': 'Чаморро',
  'Pacific/Honolulu': 'Гавайско-алеутское стандартное время',
  'Pacific/Kiritimati': 'о-ва Лайн',
  'Pacific/Kosrae': 'Косрае',
  'Pacific/Kwajalein': 'Маршалловы Острова',
  'Pacific/Majuro': 'Маршалловы Острова',
  'Pacific/Marquesas': 'Маркизские о-ва',
  'Pacific/Midway': 'Самоа, стандартное время',
  'Pacific/Nauru': 'Науру',
  'Pacific/Niue': 'Ниуэ',
  'Pacific/Norfolk': 'Норфолк',
  'Pacific/Noumea': 'Новая Каледония, стандартное время',
  'Pacific/Pago_Pago': 'Самоа, стандартное время',
  'Pacific/Palau': 'Палау',
  'Pacific/Pitcairn': 'Питкэрн',
  'Pacific/Pohnpei': 'Понпеи',
  'Pacific/Port_Moresby': 'Папуа – Новая Гвинея',
  'Pacific/Rarotonga': 'Острова Кука, стандартное время',
  'Pacific/Saipan': 'Чаморро',
  'Pacific/Tahiti': 'Таити',
  'Pacific/Tarawa': 'о-ва Гилберта',
  'Pacific/Tongatapu': 'Тонга, стандартное время',
  'Pacific/Wake': 'Уэйк',
  'Pacific/Wallis': 'Уоллис и Футуна',
  UTC: 'Всемирное координированное время',
};
