module.exports = {
  'Africa/Abidjan': 'Greenwich Ortalama Saati',
  'Africa/Accra': 'Greenwich Ortalama Saati',
  'Africa/Addis_Ababa': 'Doğu Afrika Saati',
  'Africa/Algiers': 'Orta Avrupa Standart Saati',
  'Africa/Asmara': 'Doğu Afrika Saati',
  'Africa/Bamako': 'Greenwich Ortalama Saati',
  'Africa/Bangui': 'Batı Afrika Standart Saati',
  'Africa/Banjul': 'Greenwich Ortalama Saati',
  'Africa/Bissau': 'Greenwich Ortalama Saati',
  'Africa/Blantyre': 'Orta Afrika Saati',
  'Africa/Brazzaville': 'Batı Afrika Standart Saati',
  'Africa/Bujumbura': 'Orta Afrika Saati',
  'Africa/Cairo': 'Doğu Avrupa Standart Saati',
  'Africa/Casablanca': 'Batı Avrupa Standart Saati',
  'Africa/Ceuta': 'Orta Avrupa Standart Saati',
  'Africa/Conakry': 'Greenwich Ortalama Saati',
  'Africa/Dakar': 'Greenwich Ortalama Saati',
  'Africa/Dar_es_Salaam': 'Doğu Afrika Saati',
  'Africa/Djibouti': 'Doğu Afrika Saati',
  'Africa/Douala': 'Batı Afrika Standart Saati',
  'Africa/El_Aaiun': 'Batı Avrupa Standart Saati',
  'Africa/Freetown': 'Greenwich Ortalama Saati',
  'Africa/Gaborone': 'Orta Afrika Saati',
  'Africa/Harare': 'Orta Afrika Saati',
  'Africa/Johannesburg': 'Güney Afrika Standart Saati',
  'Africa/Juba': 'Doğu Afrika Saati',
  'Africa/Kampala': 'Doğu Afrika Saati',
  'Africa/Khartoum': 'Orta Afrika Saati',
  'Africa/Kigali': 'Orta Afrika Saati',
  'Africa/Kinshasa': 'Batı Afrika Standart Saati',
  'Africa/Lagos': 'Batı Afrika Standart Saati',
  'Africa/Libreville': 'Batı Afrika Standart Saati',
  'Africa/Lome': 'Greenwich Ortalama Saati',
  'Africa/Luanda': 'Batı Afrika Standart Saati',
  'Africa/Lubumbashi': 'Orta Afrika Saati',
  'Africa/Lusaka': 'Orta Afrika Saati',
  'Africa/Malabo': 'Batı Afrika Standart Saati',
  'Africa/Maputo': 'Orta Afrika Saati',
  'Africa/Maseru': 'Güney Afrika Standart Saati',
  'Africa/Mbabane': 'Güney Afrika Standart Saati',
  'Africa/Mogadishu': 'Doğu Afrika Saati',
  'Africa/Monrovia': 'Greenwich Ortalama Saati',
  'Africa/Nairobi': 'Doğu Afrika Saati',
  'Africa/Ndjamena': 'Batı Afrika Standart Saati',
  'Africa/Niamey': 'Batı Afrika Standart Saati',
  'Africa/Nouakchott': 'Greenwich Ortalama Saati',
  'Africa/Ouagadougou': 'Greenwich Ortalama Saati',
  'Africa/Porto-Novo': 'Batı Afrika Standart Saati',
  'Africa/Sao_Tome': 'Greenwich Ortalama Saati',
  'Africa/Tripoli': 'Doğu Avrupa Standart Saati',
  'Africa/Tunis': 'Orta Avrupa Standart Saati',
  'Africa/Windhoek': 'Orta Afrika Saati',
  'America/Adak': 'Hawaii-Aleut Standart Saati',
  'America/Anchorage': 'Alaska Standart Saati',
  'America/Anguilla': 'Atlantik Standart Saati',
  'America/Antigua': 'Atlantik Standart Saati',
  'America/Araguaina': 'Brasilia Standart Saati',
  'America/Argentina/Buenos_Aires': 'Arjantin Standart Saati',
  'America/Argentina/Catamarca': 'Arjantin Standart Saati',
  'America/Argentina/Cordoba': 'Arjantin Standart Saati',
  'America/Argentina/Jujuy': 'Arjantin Standart Saati',
  'America/Argentina/La_Rioja': 'Arjantin Standart Saati',
  'America/Argentina/Mendoza': 'Arjantin Standart Saati',
  'America/Argentina/Rio_Gallegos': 'Arjantin Standart Saati',
  'America/Argentina/Salta': 'Arjantin Standart Saati',
  'America/Argentina/San_Juan': 'Arjantin Standart Saati',
  'America/Argentina/San_Luis': 'Batı Arjantin Standart Saati',
  'America/Argentina/Tucuman': 'Arjantin Standart Saati',
  'America/Argentina/Ushuaia': 'Arjantin Standart Saati',
  'America/Aruba': 'Atlantik Standart Saati',
  'America/Asuncion': 'Paraguay Standart Saati',
  'America/Atikokan': 'Kuzey Amerika Doğu Standart Saati',
  'America/Bahia': 'Brasilia Standart Saati',
  'America/Bahia_Banderas': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Barbados': 'Atlantik Standart Saati',
  'America/Belem': 'Brasilia Standart Saati',
  'America/Belize': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Blanc-Sablon': 'Atlantik Standart Saati',
  'America/Boa_Vista': 'Amazon Standart Saati',
  'America/Bogota': 'Kolombiya Standart Saati',
  'America/Boise': 'Kuzey Amerika Dağ Standart Saati',
  'America/Cambridge_Bay': 'Kuzey Amerika Dağ Standart Saati',
  'America/Campo_Grande': 'Amazon Standart Saati',
  'America/Cancun': 'Kuzey Amerika Doğu Standart Saati',
  'America/Caracas': 'Venezuela Saati',
  'America/Cayenne': 'Fransız Guyanası Saati',
  'America/Cayman': 'Kuzey Amerika Doğu Standart Saati',
  'America/Chicago': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Chihuahua': 'Meksika Pasifik Kıyısı Standart Saati',
  'America/Costa_Rica': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Creston': 'Kuzey Amerika Dağ Standart Saati',
  'America/Cuiaba': 'Amazon Standart Saati',
  'America/Curacao': 'Atlantik Standart Saati',
  'America/Danmarkshavn': 'Greenwich Ortalama Saati',
  'America/Dawson': 'Kuzey Amerika Pasifik Standart Saati',
  'America/Dawson_Creek': 'Kuzey Amerika Dağ Standart Saati',
  'America/Denver': 'Kuzey Amerika Dağ Standart Saati',
  'America/Detroit': 'Kuzey Amerika Doğu Standart Saati',
  'America/Dominica': 'Atlantik Standart Saati',
  'America/Edmonton': 'Kuzey Amerika Dağ Standart Saati',
  'America/Eirunepe': 'Acre Standart Saati',
  'America/El_Salvador': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Fort_Nelson': 'Kuzey Amerika Dağ Standart Saati',
  'America/Fortaleza': 'Brasilia Standart Saati',
  'America/Glace_Bay': 'Atlantik Standart Saati',
  'America/Godthab': 'Batı Grönland Standart Saati',
  'America/Goose_Bay': 'Atlantik Standart Saati',
  'America/Grand_Turk': 'Kuzey Amerika Doğu Standart Saati',
  'America/Grenada': 'Atlantik Standart Saati',
  'America/Guadeloupe': 'Atlantik Standart Saati',
  'America/Guatemala': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Guayaquil': 'Ekvador Saati',
  'America/Guyana': 'Guyana Saati',
  'America/Halifax': 'Atlantik Standart Saati',
  'America/Havana': 'Küba Standart Saati',
  'America/Hermosillo': 'Meksika Pasifik Kıyısı Standart Saati',
  'America/Indiana/Indianapolis': 'Kuzey Amerika Doğu Standart Saati',
  'America/Indiana/Knox': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Indiana/Marengo': 'Kuzey Amerika Doğu Standart Saati',
  'America/Indiana/Petersburg': 'Kuzey Amerika Doğu Standart Saati',
  'America/Indiana/Tell_City': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Indiana/Vevay': 'Kuzey Amerika Doğu Standart Saati',
  'America/Indiana/Vincennes': 'Kuzey Amerika Doğu Standart Saati',
  'America/Indiana/Winamac': 'Kuzey Amerika Doğu Standart Saati',
  'America/Inuvik': 'Kuzey Amerika Dağ Standart Saati',
  'America/Iqaluit': 'Kuzey Amerika Doğu Standart Saati',
  'America/Jamaica': 'Kuzey Amerika Doğu Standart Saati',
  'America/Juneau': 'Alaska Standart Saati',
  'America/Kentucky/Louisville': 'Kuzey Amerika Doğu Standart Saati',
  'America/Kentucky/Monticello': 'Kuzey Amerika Doğu Standart Saati',
  'America/Kralendijk': 'Atlantik Standart Saati',
  'America/La_Paz': 'Bolivya Saati',
  'America/Lima': 'Peru Standart Saati',
  'America/Los_Angeles': 'Kuzey Amerika Pasifik Standart Saati',
  'America/Lower_Princes': 'Atlantik Standart Saati',
  'America/Maceio': 'Brasilia Standart Saati',
  'America/Managua': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Manaus': 'Amazon Standart Saati',
  'America/Marigot': 'Atlantik Standart Saati',
  'America/Martinique': 'Atlantik Standart Saati',
  'America/Matamoros': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Mazatlan': 'Meksika Pasifik Kıyısı Standart Saati',
  'America/Menominee': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Merida': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Metlakatla': 'Alaska Standart Saati',
  'America/Mexico_City': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Miquelon': 'Saint Pierre ve Miquelon Standart Saati',
  'America/Moncton': 'Atlantik Standart Saati',
  'America/Monterrey': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Montevideo': 'Uruguay Standart Saati',
  'America/Montserrat': 'Atlantik Standart Saati',
  'America/Nassau': 'Kuzey Amerika Doğu Standart Saati',
  'America/New_York': 'Kuzey Amerika Doğu Standart Saati',
  'America/Nipigon': 'Kuzey Amerika Doğu Standart Saati',
  'America/Nome': 'Alaska Standart Saati',
  'America/Noronha': 'Fernando de Noronha Standart Saati',
  'America/North_Dakota/Beulah': 'Kuzey Amerika Merkezi Standart Saati',
  'America/North_Dakota/Center': 'Kuzey Amerika Merkezi Standart Saati',
  'America/North_Dakota/New_Salem': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Ojinaga': 'Kuzey Amerika Dağ Standart Saati',
  'America/Panama': 'Kuzey Amerika Doğu Standart Saati',
  'America/Pangnirtung': 'Kuzey Amerika Doğu Standart Saati',
  'America/Paramaribo': 'Surinam Saati',
  'America/Phoenix': 'Kuzey Amerika Dağ Standart Saati',
  'America/Port-au-Prince': 'Kuzey Amerika Doğu Standart Saati',
  'America/Port_of_Spain': 'Atlantik Standart Saati',
  'America/Porto_Velho': 'Amazon Standart Saati',
  'America/Puerto_Rico': 'Atlantik Standart Saati',
  'America/Punta_Arenas': 'GMT-03:00',
  'America/Rainy_River': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Rankin_Inlet': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Recife': 'Brasilia Standart Saati',
  'America/Regina': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Resolute': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Rio_Branco': 'Acre Standart Saati',
  'America/Santarem': 'Brasilia Standart Saati',
  'America/Santiago': 'Şili Standart Saati',
  'America/Santo_Domingo': 'Atlantik Standart Saati',
  'America/Sao_Paulo': 'Brasilia Standart Saati',
  'America/Scoresbysund': 'Doğu Grönland Standart Saati',
  'America/Sitka': 'Alaska Standart Saati',
  'America/St_Barthelemy': 'Atlantik Standart Saati',
  'America/St_Johns': 'Newfoundland Standart Saati',
  'America/St_Kitts': 'Atlantik Standart Saati',
  'America/St_Lucia': 'Atlantik Standart Saati',
  'America/St_Thomas': 'Atlantik Standart Saati',
  'America/St_Vincent': 'Atlantik Standart Saati',
  'America/Swift_Current': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Tegucigalpa': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Thule': 'Atlantik Standart Saati',
  'America/Thunder_Bay': 'Kuzey Amerika Doğu Standart Saati',
  'America/Tijuana': 'Kuzey Amerika Pasifik Standart Saati',
  'America/Toronto': 'Kuzey Amerika Doğu Standart Saati',
  'America/Tortola': 'Atlantik Standart Saati',
  'America/Vancouver': 'Kuzey Amerika Pasifik Standart Saati',
  'America/Whitehorse': 'Kuzey Amerika Pasifik Standart Saati',
  'America/Winnipeg': 'Kuzey Amerika Merkezi Standart Saati',
  'America/Yakutat': 'Alaska Standart Saati',
  'America/Yellowknife': 'Kuzey Amerika Dağ Standart Saati',
  'Antarctica/Casey': 'Casey Saati',
  'Antarctica/Davis': 'Davis Saati',
  'Antarctica/DumontDUrville': 'Dumont-d’Urville Saati',
  'Antarctica/Macquarie': 'Macquarie Adası Saati',
  'Antarctica/Mawson': 'Mawson Saati',
  'Antarctica/McMurdo': 'Yeni Zelanda Standart Saati',
  'Antarctica/Palmer': 'GMT-03:00',
  'Antarctica/Rothera': 'Rothera Saati',
  'Antarctica/Syowa': 'Showa Saati',
  'Antarctica/Troll': 'Greenwich Ortalama Saati',
  'Antarctica/Vostok': 'Vostok Saati',
  'Arctic/Longyearbyen': 'Orta Avrupa Standart Saati',
  'Asia/Aden': 'Arabistan Standart Saati',
  'Asia/Almaty': 'Doğu Kazakistan Saati',
  'Asia/Amman': 'Doğu Avrupa Standart Saati',
  'Asia/Anadyr': 'Anadır Standart Saati',
  'Asia/Aqtau': 'Batı Kazakistan Saati',
  'Asia/Aqtobe': 'Batı Kazakistan Saati',
  'Asia/Ashgabat': 'Türkmenistan Standart Saati',
  'Asia/Atyrau': 'Batı Kazakistan Saati',
  'Asia/Baghdad': 'Arabistan Standart Saati',
  'Asia/Bahrain': 'Arabistan Standart Saati',
  'Asia/Baku': 'Azerbaycan Standart Saati',
  'Asia/Bangkok': 'Hindiçin Saati',
  'Asia/Barnaul': 'GMT+07:00',
  'Asia/Beirut': 'Doğu Avrupa Standart Saati',
  'Asia/Bishkek': 'Kırgızistan Saati',
  'Asia/Brunei': 'Brunei Darü’s-Selam Saati',
  'Asia/Chita': 'Yakutsk Standart Saati',
  'Asia/Choibalsan': 'Çoybalsan Standart Saati',
  'Asia/Colombo': 'Hindistan Standart Saati',
  'Asia/Damascus': 'Doğu Avrupa Standart Saati',
  'Asia/Dhaka': 'Bangladeş Standart Saati',
  'Asia/Dili': 'Doğu Timor Saati',
  'Asia/Dubai': 'Körfez Saati',
  'Asia/Dushanbe': 'Tacikistan Saati',
  'Asia/Famagusta': 'GMT+02:00',
  'Asia/Gaza': 'Doğu Avrupa Standart Saati',
  'Asia/Hebron': 'Doğu Avrupa Standart Saati',
  'Asia/Ho_Chi_Minh': 'Hindiçin Saati',
  'Asia/Hong_Kong': 'Hong Kong Standart Saati',
  'Asia/Hovd': 'Hovd Standart Saati',
  'Asia/Irkutsk': 'İrkutsk Standart Saati',
  'Asia/Jakarta': 'Batı Endonezya Saati',
  'Asia/Jayapura': 'Doğu Endonezya Saati',
  'Asia/Jerusalem': 'İsrail Standart Saati',
  'Asia/Kabul': 'Afganistan Saati',
  'Asia/Kamchatka': 'Petropavlovsk-Kamçatski Standart Saati',
  'Asia/Karachi': 'Pakistan Standart Saati',
  'Asia/Kathmandu': 'Nepal Saati',
  'Asia/Khandyga': 'Yakutsk Standart Saati',
  'Asia/Kolkata': 'Hindistan Standart Saati',
  'Asia/Krasnoyarsk': 'Krasnoyarsk Standart Saati',
  'Asia/Kuala_Lumpur': 'Malezya Saati',
  'Asia/Kuching': 'Malezya Saati',
  'Asia/Kuwait': 'Arabistan Standart Saati',
  'Asia/Macau': 'Çin Standart Saati',
  'Asia/Magadan': 'Magadan Standart Saati',
  'Asia/Makassar': 'Orta Endonezya Saati',
  'Asia/Manila': 'Filipinler Standart Saati',
  'Asia/Muscat': 'Körfez Saati',
  'Asia/Nicosia': 'Doğu Avrupa Standart Saati',
  'Asia/Novokuznetsk': 'Krasnoyarsk Standart Saati',
  'Asia/Novosibirsk': 'Novosibirsk Standart Saati',
  'Asia/Omsk': 'Omsk Standart Saati',
  'Asia/Oral': 'Batı Kazakistan Saati',
  'Asia/Phnom_Penh': 'Hindiçin Saati',
  'Asia/Pontianak': 'Batı Endonezya Saati',
  'Asia/Pyongyang': 'Pyongyang Saati',
  'Asia/Qatar': 'Arabistan Standart Saati',
  'Asia/Qyzylorda': 'Doğu Kazakistan Saati',
  'Asia/Riyadh': 'Arabistan Standart Saati',
  'Asia/Sakhalin': 'Sahalin Standart Saati',
  'Asia/Samarkand': 'Özbekistan Standart Saati',
  'Asia/Seoul': 'Kore Standart Saati',
  'Asia/Shanghai': 'Çin Standart Saati',
  'Asia/Singapore': 'Singapur Standart Saati',
  'Asia/Srednekolymsk': 'GMT+11:00',
  'Asia/Taipei': 'Taipei Standart Saati',
  'Asia/Tashkent': 'Özbekistan Standart Saati',
  'Asia/Tbilisi': 'Gürcistan Standart Saati',
  'Asia/Tehran': 'İran Standart Saati',
  'Asia/Thimphu': 'Butan Saati',
  'Asia/Tokyo': 'Japonya Standart Saati',
  'Asia/Tomsk': 'GMT+07:00',
  'Asia/Ulaanbaatar': 'Ulan Batur Standart Saati',
  'Asia/Urumqi': 'GMT+06:00',
  'Asia/Ust-Nera': 'Vladivostok Standart Saati',
  'Asia/Vientiane': 'Hindiçin Saati',
  'Asia/Vladivostok': 'Vladivostok Standart Saati',
  'Asia/Yakutsk': 'Yakutsk Standart Saati',
  'Asia/Yangon': 'Myanmar Saati',
  'Asia/Yekaterinburg': 'Yekaterinburg Standart Saati',
  'Asia/Yerevan': 'Ermenistan Standart Saati',
  'Atlantic/Azores': 'Azorlar Standart Saati',
  'Atlantic/Bermuda': 'Atlantik Standart Saati',
  'Atlantic/Canary': 'Batı Avrupa Standart Saati',
  'Atlantic/Cape_Verde': 'Cape Verde Standart Saati',
  'Atlantic/Faroe': 'Batı Avrupa Standart Saati',
  'Atlantic/Madeira': 'Batı Avrupa Standart Saati',
  'Atlantic/Reykjavik': 'Greenwich Ortalama Saati',
  'Atlantic/South_Georgia': 'Güney Georgia Saati',
  'Atlantic/St_Helena': 'Greenwich Ortalama Saati',
  'Atlantic/Stanley': 'Falkland Adaları Standart Saati',
  'Australia/Adelaide': 'Orta Avustralya Standart Saati',
  'Australia/Brisbane': 'Doğu Avustralya Standart Saati',
  'Australia/Broken_Hill': 'Orta Avustralya Standart Saati',
  'Australia/Currie': 'Doğu Avustralya Standart Saati',
  'Australia/Darwin': 'Orta Avustralya Standart Saati',
  'Australia/Eucla': 'İç Batı Avustralya Standart Saati',
  'Australia/Hobart': 'Doğu Avustralya Standart Saati',
  'Australia/Lindeman': 'Doğu Avustralya Standart Saati',
  'Australia/Lord_Howe': 'Lord Howe Standart Saati',
  'Australia/Melbourne': 'Doğu Avustralya Standart Saati',
  'Australia/Perth': 'Batı Avustralya Standart Saati',
  'Australia/Sydney': 'Doğu Avustralya Standart Saati',
  'Europe/Amsterdam': 'Orta Avrupa Standart Saati',
  'Europe/Andorra': 'Orta Avrupa Standart Saati',
  'Europe/Astrakhan': 'GMT+04:00',
  'Europe/Athens': 'Doğu Avrupa Standart Saati',
  'Europe/Belgrade': 'Orta Avrupa Standart Saati',
  'Europe/Berlin': 'Orta Avrupa Standart Saati',
  'Europe/Bratislava': 'Orta Avrupa Standart Saati',
  'Europe/Brussels': 'Orta Avrupa Standart Saati',
  'Europe/Bucharest': 'Doğu Avrupa Standart Saati',
  'Europe/Budapest': 'Orta Avrupa Standart Saati',
  'Europe/Busingen': 'Orta Avrupa Standart Saati',
  'Europe/Chisinau': 'Doğu Avrupa Standart Saati',
  'Europe/Copenhagen': 'Orta Avrupa Standart Saati',
  'Europe/Dublin': 'Greenwich Ortalama Saati',
  'Europe/Gibraltar': 'Orta Avrupa Standart Saati',
  'Europe/Guernsey': 'Greenwich Ortalama Saati',
  'Europe/Helsinki': 'Doğu Avrupa Standart Saati',
  'Europe/Isle_of_Man': 'Greenwich Ortalama Saati',
  'Europe/Istanbul': 'GMT+03:00',
  'Europe/Jersey': 'Greenwich Ortalama Saati',
  'Europe/Kaliningrad': 'Doğu Avrupa Standart Saati',
  'Europe/Kiev': 'Doğu Avrupa Standart Saati',
  'Europe/Kirov': 'GMT+03:00',
  'Europe/Lisbon': 'Batı Avrupa Standart Saati',
  'Europe/Ljubljana': 'Orta Avrupa Standart Saati',
  'Europe/London': 'Greenwich Ortalama Saati',
  'Europe/Luxembourg': 'Orta Avrupa Standart Saati',
  'Europe/Madrid': 'Orta Avrupa Standart Saati',
  'Europe/Malta': 'Orta Avrupa Standart Saati',
  'Europe/Mariehamn': 'Doğu Avrupa Standart Saati',
  'Europe/Minsk': 'Moskova Standart Saati',
  'Europe/Monaco': 'Orta Avrupa Standart Saati',
  'Europe/Moscow': 'Moskova Standart Saati',
  'Europe/Oslo': 'Orta Avrupa Standart Saati',
  'Europe/Paris': 'Orta Avrupa Standart Saati',
  'Europe/Podgorica': 'Orta Avrupa Standart Saati',
  'Europe/Prague': 'Orta Avrupa Standart Saati',
  'Europe/Riga': 'Doğu Avrupa Standart Saati',
  'Europe/Rome': 'Orta Avrupa Standart Saati',
  'Europe/Samara': 'Samara Standart Saati',
  'Europe/San_Marino': 'Orta Avrupa Standart Saati',
  'Europe/Sarajevo': 'Orta Avrupa Standart Saati',
  'Europe/Saratov': 'GMT+04:00',
  'Europe/Simferopol': 'Moskova Standart Saati',
  'Europe/Skopje': 'Orta Avrupa Standart Saati',
  'Europe/Sofia': 'Doğu Avrupa Standart Saati',
  'Europe/Stockholm': 'Orta Avrupa Standart Saati',
  'Europe/Tallinn': 'Doğu Avrupa Standart Saati',
  'Europe/Tirane': 'Orta Avrupa Standart Saati',
  'Europe/Ulyanovsk': 'GMT+04:00',
  'Europe/Uzhgorod': 'Doğu Avrupa Standart Saati',
  'Europe/Vaduz': 'Orta Avrupa Standart Saati',
  'Europe/Vatican': 'Orta Avrupa Standart Saati',
  'Europe/Vienna': 'Orta Avrupa Standart Saati',
  'Europe/Vilnius': 'Doğu Avrupa Standart Saati',
  'Europe/Volgograd': 'Moskova Standart Saati',
  'Europe/Warsaw': 'Orta Avrupa Standart Saati',
  'Europe/Zagreb': 'Orta Avrupa Standart Saati',
  'Europe/Zaporozhye': 'Doğu Avrupa Standart Saati',
  'Europe/Zurich': 'Orta Avrupa Standart Saati',
  'Indian/Antananarivo': 'Doğu Afrika Saati',
  'Indian/Chagos': 'Hint Okyanusu Saati',
  'Indian/Christmas': 'Christmas Adası Saati',
  'Indian/Cocos': 'Cocos Adaları Saati',
  'Indian/Comoro': 'Doğu Afrika Saati',
  'Indian/Kerguelen': 'Fransız Güney ve Antarktika Saati',
  'Indian/Mahe': 'Seyşeller Saati',
  'Indian/Maldives': 'Maldivler Saati',
  'Indian/Mauritius': 'Mauritius Standart Saati',
  'Indian/Mayotte': 'Doğu Afrika Saati',
  'Indian/Reunion': 'Reunion Saati',
  'Pacific/Apia': 'Apia Standart Saati',
  'Pacific/Auckland': 'Yeni Zelanda Standart Saati',
  'Pacific/Bougainville': 'GMT+11:00',
  'Pacific/Chatham': 'Chatham Standart Saati',
  'Pacific/Chuuk': 'Chuuk Saati',
  'Pacific/Easter': 'Paskalya Adası Standart Saati',
  'Pacific/Efate': 'Vanuatu Standart Saati',
  'Pacific/Enderbury': 'Phoenix Adaları Saati',
  'Pacific/Fakaofo': 'Tokelau Saati',
  'Pacific/Fiji': 'Fiji Standart Saati',
  'Pacific/Funafuti': 'Tuvalu Saati',
  'Pacific/Galapagos': 'Galapagos Saati',
  'Pacific/Gambier': 'Gambier Saati',
  'Pacific/Guadalcanal': 'Solomon Adaları Saati',
  'Pacific/Guam': 'Chamorro Saati',
  'Pacific/Honolulu': 'Hawaii-Aleut Standart Saati',
  'Pacific/Kiritimati': 'Line Adaları Saati',
  'Pacific/Kosrae': 'Kosrae Saati',
  'Pacific/Kwajalein': 'Marshall Adaları Saati',
  'Pacific/Majuro': 'Marshall Adaları Saati',
  'Pacific/Marquesas': 'Markiz Adaları Saati',
  'Pacific/Midway': 'Samoa Standart Saati',
  'Pacific/Nauru': 'Nauru Saati',
  'Pacific/Niue': 'Niue Saati',
  'Pacific/Norfolk': 'Norfolk Adası Saati',
  'Pacific/Noumea': 'Yeni Kaledonya Standart Saati',
  'Pacific/Pago_Pago': 'Samoa Standart Saati',
  'Pacific/Palau': 'Palau Saati',
  'Pacific/Pitcairn': 'Pitcairn Saati',
  'Pacific/Pohnpei': 'Ponape Saati',
  'Pacific/Port_Moresby': 'Papua Yeni Gine Saati',
  'Pacific/Rarotonga': 'Cook Adaları Standart Saati',
  'Pacific/Saipan': 'Chamorro Saati',
  'Pacific/Tahiti': 'Tahiti Saati',
  'Pacific/Tarawa': 'Gilbert Adaları Saati',
  'Pacific/Tongatapu': 'Tonga Standart Saati',
  'Pacific/Wake': 'Wake Adası Saati',
  'Pacific/Wallis': 'Wallis ve Futuna Saati',
  UTC: 'Eş Güdümlü Evrensel Zaman',
};
