module.exports = {
  'Africa/Abidjan': 'گرین وچ کا اصل وقت',
  'Africa/Accra': 'گرین وچ کا اصل وقت',
  'Africa/Addis_Ababa': 'مشرقی افریقہ ٹائم',
  'Africa/Algiers': 'وسطی یورپ کا معیاری وقت',
  'Africa/Asmara': 'مشرقی افریقہ ٹائم',
  'Africa/Bamako': 'گرین وچ کا اصل وقت',
  'Africa/Bangui': 'مغربی افریقہ سٹینڈرڈ ٹائم',
  'Africa/Banjul': 'گرین وچ کا اصل وقت',
  'Africa/Bissau': 'گرین وچ کا اصل وقت',
  'Africa/Blantyre': 'وسطی افریقہ ٹائم',
  'Africa/Brazzaville': 'مغربی افریقہ سٹینڈرڈ ٹائم',
  'Africa/Bujumbura': 'وسطی افریقہ ٹائم',
  'Africa/Cairo': 'مشرقی یورپ کا معیاری وقت',
  'Africa/Casablanca': 'مغربی یورپ کا معیاری وقت',
  'Africa/Ceuta': 'وسطی یورپ کا معیاری وقت',
  'Africa/Conakry': 'گرین وچ کا اصل وقت',
  'Africa/Dakar': 'گرین وچ کا اصل وقت',
  'Africa/Dar_es_Salaam': 'مشرقی افریقہ ٹائم',
  'Africa/Djibouti': 'مشرقی افریقہ ٹائم',
  'Africa/Douala': 'مغربی افریقہ سٹینڈرڈ ٹائم',
  'Africa/El_Aaiun': 'مغربی یورپ کا معیاری وقت',
  'Africa/Freetown': 'گرین وچ کا اصل وقت',
  'Africa/Gaborone': 'وسطی افریقہ ٹائم',
  'Africa/Harare': 'وسطی افریقہ ٹائم',
  'Africa/Johannesburg': 'جنوبی افریقہ سٹینڈرڈ ٹائم',
  'Africa/Juba': 'مشرقی افریقہ ٹائم',
  'Africa/Kampala': 'مشرقی افریقہ ٹائم',
  'Africa/Khartoum': 'وسطی افریقہ ٹائم',
  'Africa/Kigali': 'وسطی افریقہ ٹائم',
  'Africa/Kinshasa': 'مغربی افریقہ سٹینڈرڈ ٹائم',
  'Africa/Lagos': 'مغربی افریقہ سٹینڈرڈ ٹائم',
  'Africa/Libreville': 'مغربی افریقہ سٹینڈرڈ ٹائم',
  'Africa/Lome': 'گرین وچ کا اصل وقت',
  'Africa/Luanda': 'مغربی افریقہ سٹینڈرڈ ٹائم',
  'Africa/Lubumbashi': 'وسطی افریقہ ٹائم',
  'Africa/Lusaka': 'وسطی افریقہ ٹائم',
  'Africa/Malabo': 'مغربی افریقہ سٹینڈرڈ ٹائم',
  'Africa/Maputo': 'وسطی افریقہ ٹائم',
  'Africa/Maseru': 'جنوبی افریقہ سٹینڈرڈ ٹائم',
  'Africa/Mbabane': 'جنوبی افریقہ سٹینڈرڈ ٹائم',
  'Africa/Mogadishu': 'مشرقی افریقہ ٹائم',
  'Africa/Monrovia': 'گرین وچ کا اصل وقت',
  'Africa/Nairobi': 'مشرقی افریقہ ٹائم',
  'Africa/Ndjamena': 'مغربی افریقہ سٹینڈرڈ ٹائم',
  'Africa/Niamey': 'مغربی افریقہ سٹینڈرڈ ٹائم',
  'Africa/Nouakchott': 'گرین وچ کا اصل وقت',
  'Africa/Ouagadougou': 'گرین وچ کا اصل وقت',
  'Africa/Porto-Novo': 'مغربی افریقہ سٹینڈرڈ ٹائم',
  'Africa/Sao_Tome': 'گرین وچ کا اصل وقت',
  'Africa/Tripoli': 'مشرقی یورپ کا معیاری وقت',
  'Africa/Tunis': 'وسطی یورپ کا معیاری وقت',
  'Africa/Windhoek': 'وسطی افریقہ ٹائم',
  'America/Adak': 'ہوائی الیوٹیئن اسٹینڈرڈ ٹائم',
  'America/Anchorage': 'الاسکا اسٹینڈرڈ ٹائم',
  'America/Anguilla': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Antigua': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Araguaina': 'برازیلیا اسٹینڈرڈ ٹائم',
  'America/Argentina/Buenos_Aires': 'ارجنٹینا سٹینڈرڈ ٹائم',
  'America/Argentina/Catamarca': 'ارجنٹینا سٹینڈرڈ ٹائم',
  'America/Argentina/Cordoba': 'ارجنٹینا سٹینڈرڈ ٹائم',
  'America/Argentina/Jujuy': 'ارجنٹینا سٹینڈرڈ ٹائم',
  'America/Argentina/La_Rioja': 'ارجنٹینا سٹینڈرڈ ٹائم',
  'America/Argentina/Mendoza': 'ارجنٹینا سٹینڈرڈ ٹائم',
  'America/Argentina/Rio_Gallegos': 'ارجنٹینا سٹینڈرڈ ٹائم',
  'America/Argentina/Salta': 'ارجنٹینا سٹینڈرڈ ٹائم',
  'America/Argentina/San_Juan': 'ارجنٹینا سٹینڈرڈ ٹائم',
  'America/Argentina/San_Luis': 'مغربی ارجنٹینا کا معیاری وقت',
  'America/Argentina/Tucuman': 'ارجنٹینا سٹینڈرڈ ٹائم',
  'America/Argentina/Ushuaia': 'ارجنٹینا سٹینڈرڈ ٹائم',
  'America/Aruba': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Asuncion': 'پیراگوئے کا معیاری وقت',
  'America/Atikokan': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Bahia': 'برازیلیا اسٹینڈرڈ ٹائم',
  'America/Bahia_Banderas': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Barbados': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Belem': 'برازیلیا اسٹینڈرڈ ٹائم',
  'America/Belize': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Blanc-Sablon': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Boa_Vista': 'ایمیزون سٹینڈرڈ ٹائم',
  'America/Bogota': 'کولمبیا کا معیاری وقت',
  'America/Boise': 'ماؤنٹین اسٹینڈرڈ ٹائم',
  'America/Cambridge_Bay': 'ماؤنٹین اسٹینڈرڈ ٹائم',
  'America/Campo_Grande': 'ایمیزون سٹینڈرڈ ٹائم',
  'America/Cancun': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Caracas': 'وینزوئیلا کا وقت',
  'America/Cayenne': 'فرینچ گیانا کا وقت',
  'America/Cayman': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Chicago': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Chihuahua': 'میکسیکن پیسفک اسٹینڈرڈ ٹائم',
  'America/Costa_Rica': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Creston': 'ماؤنٹین اسٹینڈرڈ ٹائم',
  'America/Cuiaba': 'ایمیزون سٹینڈرڈ ٹائم',
  'America/Curacao': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Danmarkshavn': 'گرین وچ کا اصل وقت',
  'America/Dawson': 'پیسفک اسٹینڈرڈ ٹائم',
  'America/Dawson_Creek': 'ماؤنٹین اسٹینڈرڈ ٹائم',
  'America/Denver': 'ماؤنٹین اسٹینڈرڈ ٹائم',
  'America/Detroit': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Dominica': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Edmonton': 'ماؤنٹین اسٹینڈرڈ ٹائم',
  'America/Eirunepe': 'GMT -05:00',
  'America/El_Salvador': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Fort_Nelson': 'ماؤنٹین اسٹینڈرڈ ٹائم',
  'America/Fortaleza': 'برازیلیا اسٹینڈرڈ ٹائم',
  'America/Glace_Bay': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Godthab': 'مغربی گرین لینڈ اسٹینڈرڈ ٹائم',
  'America/Goose_Bay': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Grand_Turk': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Grenada': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Guadeloupe': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Guatemala': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Guayaquil': 'ایکواڈور کا وقت',
  'America/Guyana': 'گیانا کا وقت',
  'America/Halifax': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Havana': 'کیوبا اسٹینڈرڈ ٹائم',
  'America/Hermosillo': 'میکسیکن پیسفک اسٹینڈرڈ ٹائم',
  'America/Indiana/Indianapolis': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Indiana/Knox': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Indiana/Marengo': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Indiana/Petersburg': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Indiana/Tell_City': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Indiana/Vevay': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Indiana/Vincennes': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Indiana/Winamac': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Inuvik': 'ماؤنٹین اسٹینڈرڈ ٹائم',
  'America/Iqaluit': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Jamaica': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Juneau': 'الاسکا اسٹینڈرڈ ٹائم',
  'America/Kentucky/Louisville': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Kentucky/Monticello': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Kralendijk': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/La_Paz': 'بولیویا کا وقت',
  'America/Lima': 'پیرو کا معیاری وقت',
  'America/Los_Angeles': 'پیسفک اسٹینڈرڈ ٹائم',
  'America/Lower_Princes': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Maceio': 'برازیلیا اسٹینڈرڈ ٹائم',
  'America/Managua': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Manaus': 'ایمیزون سٹینڈرڈ ٹائم',
  'America/Marigot': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Martinique': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Matamoros': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Mazatlan': 'میکسیکن پیسفک اسٹینڈرڈ ٹائم',
  'America/Menominee': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Merida': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Metlakatla': 'الاسکا اسٹینڈرڈ ٹائم',
  'America/Mexico_City': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Miquelon': 'سینٹ پیئر اور مکلیئون اسٹینڈرڈ ٹائم',
  'America/Moncton': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Monterrey': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Montevideo': 'یوروگوئے کا معیاری وقت',
  'America/Montserrat': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Nassau': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/New_York': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Nipigon': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Nome': 'الاسکا اسٹینڈرڈ ٹائم',
  'America/Noronha': 'فرنانڈو ڈی نورنہا کا معیاری وقت',
  'America/North_Dakota/Beulah': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/North_Dakota/Center': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/North_Dakota/New_Salem': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Ojinaga': 'ماؤنٹین اسٹینڈرڈ ٹائم',
  'America/Panama': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Pangnirtung': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Paramaribo': 'سورینام کا وقت',
  'America/Phoenix': 'ماؤنٹین اسٹینڈرڈ ٹائم',
  'America/Port-au-Prince': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Port_of_Spain': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Porto_Velho': 'ایمیزون سٹینڈرڈ ٹائم',
  'America/Puerto_Rico': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Punta_Arenas': 'GMT -03:00',
  'America/Rainy_River': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Rankin_Inlet': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Recife': 'برازیلیا اسٹینڈرڈ ٹائم',
  'America/Regina': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Resolute': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Rio_Branco': 'GMT -05:00',
  'America/Santarem': 'برازیلیا اسٹینڈرڈ ٹائم',
  'America/Santiago': 'چلی کا معیاری وقت',
  'America/Santo_Domingo': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Sao_Paulo': 'برازیلیا اسٹینڈرڈ ٹائم',
  'America/Scoresbysund': 'مشرقی گرین لینڈ اسٹینڈرڈ ٹائم',
  'America/Sitka': 'الاسکا اسٹینڈرڈ ٹائم',
  'America/St_Barthelemy': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/St_Johns': 'نیو فاؤنڈ لینڈ اسٹینڈرڈ ٹائم',
  'America/St_Kitts': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/St_Lucia': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/St_Thomas': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/St_Vincent': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Swift_Current': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Tegucigalpa': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Thule': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Thunder_Bay': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Tijuana': 'پیسفک اسٹینڈرڈ ٹائم',
  'America/Toronto': 'ایسٹرن اسٹینڈرڈ ٹائم',
  'America/Tortola': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'America/Vancouver': 'پیسفک اسٹینڈرڈ ٹائم',
  'America/Whitehorse': 'پیسفک اسٹینڈرڈ ٹائم',
  'America/Winnipeg': 'سنٹرل اسٹینڈرڈ ٹائم',
  'America/Yakutat': 'الاسکا اسٹینڈرڈ ٹائم',
  'America/Yellowknife': 'ماؤنٹین اسٹینڈرڈ ٹائم',
  'Antarctica/Casey': 'GMT +11:00',
  'Antarctica/Davis': 'ڈیوس ٹائم',
  'Antarctica/DumontDUrville': 'ڈومونٹ-ڈی’ارویلے ٹائم',
  'Antarctica/Macquarie': 'مکوآری آئلینڈ کا وقت',
  'Antarctica/Mawson': 'ماؤسن ٹائم',
  'Antarctica/McMurdo': 'نیوزی لینڈ کا معیاری وقت',
  'Antarctica/Palmer': 'GMT -03:00',
  'Antarctica/Rothera': 'روتھیرا کا وقت',
  'Antarctica/Syowa': 'سیووا ٹائم',
  'Antarctica/Troll': 'گرین وچ کا اصل وقت',
  'Antarctica/Vostok': 'ووسٹاک کا وقت',
  'Arctic/Longyearbyen': 'وسطی یورپ کا معیاری وقت',
  'Asia/Aden': 'عرب کا معیاری وقت',
  'Asia/Almaty': 'مشرقی قزاخستان کا وقت',
  'Asia/Amman': 'مشرقی یورپ کا معیاری وقت',
  'Asia/Anadyr': 'انیدر اسٹینڈرڈ ٹائم',
  'Asia/Aqtau': 'مغربی قزاخستان کا وقت',
  'Asia/Aqtobe': 'مغربی قزاخستان کا وقت',
  'Asia/Ashgabat': 'ترکمانستان کا معیاری وقت',
  'Asia/Atyrau': 'مغربی قزاخستان کا وقت',
  'Asia/Baghdad': 'عرب کا معیاری وقت',
  'Asia/Bahrain': 'عرب کا معیاری وقت',
  'Asia/Baku': 'آذربائیجان کا معیاری وقت',
  'Asia/Bangkok': 'ہند چین ٹائم',
  'Asia/Barnaul': 'GMT +07:00',
  'Asia/Beirut': 'مشرقی یورپ کا معیاری وقت',
  'Asia/Bishkek': 'کرغستان کا وقت',
  'Asia/Brunei': 'برونئی دارالسلام ٹائم',
  'Asia/Chita': 'یکوتسک اسٹینڈرڈ ٹائم',
  'Asia/Choibalsan': 'کوئبلسان سٹینڈرڈ ٹائم',
  'Asia/Colombo': 'ہندوستان کا معیاری وقت',
  'Asia/Damascus': 'مشرقی یورپ کا معیاری وقت',
  'Asia/Dhaka': 'بنگلہ دیش کا معیاری وقت',
  'Asia/Dili': 'مشرقی تیمور ٹائم',
  'Asia/Dubai': 'خلیج کا معیاری وقت',
  'Asia/Dushanbe': 'تاجکستان کا وقت',
  'Asia/Famagusta': 'GMT +02:00',
  'Asia/Gaza': 'مشرقی یورپ کا معیاری وقت',
  'Asia/Hebron': 'مشرقی یورپ کا معیاری وقت',
  'Asia/Ho_Chi_Minh': 'ہند چین ٹائم',
  'Asia/Hong_Kong': 'ہانگ کانگ سٹینڈرڈ ٹائم',
  'Asia/Hovd': 'ہووڈ سٹینڈرڈ ٹائم',
  'Asia/Irkutsk': 'ارکتسک سٹینڈرڈ ٹائم',
  'Asia/Jakarta': 'مغربی انڈونیشیا ٹائم',
  'Asia/Jayapura': 'مشرقی انڈونیشیا ٹائم',
  'Asia/Jerusalem': 'اسرائیل کا معیاری وقت',
  'Asia/Kabul': 'افغانستان کا وقت',
  'Asia/Kamchatka': 'پیٹروپاؤلووسک-کیمچسکی اسٹینڈرڈ ٹائم',
  'Asia/Karachi': 'پاکستان کا معیاری وقت',
  'Asia/Kathmandu': 'نیپال کا وقت',
  'Asia/Khandyga': 'یکوتسک اسٹینڈرڈ ٹائم',
  'Asia/Kolkata': 'ہندوستان کا معیاری وقت',
  'Asia/Krasnoyarsk': 'کرسنویارسک سٹینڈرڈ ٹائم',
  'Asia/Kuala_Lumpur': 'ملیشیا ٹائم',
  'Asia/Kuching': 'ملیشیا ٹائم',
  'Asia/Kuwait': 'عرب کا معیاری وقت',
  'Asia/Macau': 'چین سٹینڈرڈ ٹائم',
  'Asia/Magadan': 'مگادان اسٹینڈرڈ ٹائم',
  'Asia/Makassar': 'وسطی انڈونیشیا ٹائم',
  'Asia/Manila': 'فلپائن سٹینڈرڈ ٹائم',
  'Asia/Muscat': 'خلیج کا معیاری وقت',
  'Asia/Nicosia': 'مشرقی یورپ کا معیاری وقت',
  'Asia/Novokuznetsk': 'کرسنویارسک سٹینڈرڈ ٹائم',
  'Asia/Novosibirsk': 'نوووسیبرسک سٹینڈرڈ ٹائم',
  'Asia/Omsk': 'اومسک سٹینڈرڈ ٹائم',
  'Asia/Oral': 'مغربی قزاخستان کا وقت',
  'Asia/Phnom_Penh': 'ہند چین ٹائم',
  'Asia/Pontianak': 'مغربی انڈونیشیا ٹائم',
  'Asia/Pyongyang': 'پیانگ یانگ وقت',
  'Asia/Qatar': 'عرب کا معیاری وقت',
  'Asia/Qyzylorda': 'مشرقی قزاخستان کا وقت',
  'Asia/Riyadh': 'عرب کا معیاری وقت',
  'Asia/Sakhalin': 'سخالین سٹینڈرڈ ٹائم',
  'Asia/Samarkand': 'ازبکستان کا معیاری وقت',
  'Asia/Seoul': 'کوریا سٹینڈرڈ ٹائم',
  'Asia/Shanghai': 'چین سٹینڈرڈ ٹائم',
  'Asia/Singapore': 'سنگاپور سٹینڈرڈ ٹائم',
  'Asia/Srednekolymsk': 'GMT +11:00',
  'Asia/Taipei': 'تائی پیئی اسٹینڈرڈ ٹائم',
  'Asia/Tashkent': 'ازبکستان کا معیاری وقت',
  'Asia/Tbilisi': 'جارجیا کا معیاری وقت',
  'Asia/Tehran': 'ایران کا معیاری وقت',
  'Asia/Thimphu': 'بھوٹان کا وقت',
  'Asia/Tokyo': 'جاپان سٹینڈرڈ ٹائم',
  'Asia/Tomsk': 'GMT +07:00',
  'Asia/Ulaanbaatar': 'یولان بیتور سٹینڈرڈ ٹائم',
  'Asia/Urumqi': 'GMT +06:00',
  'Asia/Ust-Nera': 'ولادی ووستک سٹینڈرڈ ٹائم',
  'Asia/Vientiane': 'ہند چین ٹائم',
  'Asia/Vladivostok': 'ولادی ووستک سٹینڈرڈ ٹائم',
  'Asia/Yakutsk': 'یکوتسک اسٹینڈرڈ ٹائم',
  'Asia/Yangon': 'میانمار ٹائم',
  'Asia/Yekaterinburg': 'یکاٹیرِنبرگ اسٹینڈرڈ ٹائم',
  'Asia/Yerevan': 'آرمینیا کا معیاری وقت',
  'Atlantic/Azores': 'ازوریس کا معیاری وقت',
  'Atlantic/Bermuda': 'اٹلانٹک اسٹینڈرڈ ٹائم',
  'Atlantic/Canary': 'مغربی یورپ کا معیاری وقت',
  'Atlantic/Cape_Verde': 'کیپ ورڈی سٹینڈرڈ ٹائم',
  'Atlantic/Faroe': 'مغربی یورپ کا معیاری وقت',
  'Atlantic/Madeira': 'مغربی یورپ کا معیاری وقت',
  'Atlantic/Reykjavik': 'گرین وچ کا اصل وقت',
  'Atlantic/South_Georgia': 'جنوبی جارجیا ٹائم',
  'Atlantic/St_Helena': 'گرین وچ کا اصل وقت',
  'Atlantic/Stanley': 'فاک لینڈ آئلینڈز کا معیاری وقت',
  'Australia/Adelaide': 'آسٹریلین سنٹرل اسٹینڈرڈ ٹائم',
  'Australia/Brisbane': 'آسٹریلین ایسٹرن اسٹینڈرڈ ٹائم',
  'Australia/Broken_Hill': 'آسٹریلین سنٹرل اسٹینڈرڈ ٹائم',
  'Australia/Currie': 'آسٹریلین ایسٹرن اسٹینڈرڈ ٹائم',
  'Australia/Darwin': 'آسٹریلین سنٹرل اسٹینڈرڈ ٹائم',
  'Australia/Eucla': 'آسٹریلین سنٹرل ویسٹرن اسٹینڈرڈ ٹائم',
  'Australia/Hobart': 'آسٹریلین ایسٹرن اسٹینڈرڈ ٹائم',
  'Australia/Lindeman': 'آسٹریلین ایسٹرن اسٹینڈرڈ ٹائم',
  'Australia/Lord_Howe': 'لارڈ ہووے اسٹینڈرڈ ٹائم',
  'Australia/Melbourne': 'آسٹریلین ایسٹرن اسٹینڈرڈ ٹائم',
  'Australia/Perth': 'آسٹریلیا ویسٹرن اسٹینڈرڈ ٹائم',
  'Australia/Sydney': 'آسٹریلین ایسٹرن اسٹینڈرڈ ٹائم',
  'Europe/Amsterdam': 'وسطی یورپ کا معیاری وقت',
  'Europe/Andorra': 'وسطی یورپ کا معیاری وقت',
  'Europe/Astrakhan': 'GMT +04:00',
  'Europe/Athens': 'مشرقی یورپ کا معیاری وقت',
  'Europe/Belgrade': 'وسطی یورپ کا معیاری وقت',
  'Europe/Berlin': 'وسطی یورپ کا معیاری وقت',
  'Europe/Bratislava': 'وسطی یورپ کا معیاری وقت',
  'Europe/Brussels': 'وسطی یورپ کا معیاری وقت',
  'Europe/Bucharest': 'مشرقی یورپ کا معیاری وقت',
  'Europe/Budapest': 'وسطی یورپ کا معیاری وقت',
  'Europe/Busingen': 'وسطی یورپ کا معیاری وقت',
  'Europe/Chisinau': 'مشرقی یورپ کا معیاری وقت',
  'Europe/Copenhagen': 'وسطی یورپ کا معیاری وقت',
  'Europe/Dublin': 'گرین وچ کا اصل وقت',
  'Europe/Gibraltar': 'وسطی یورپ کا معیاری وقت',
  'Europe/Guernsey': 'گرین وچ کا اصل وقت',
  'Europe/Helsinki': 'مشرقی یورپ کا معیاری وقت',
  'Europe/Isle_of_Man': 'گرین وچ کا اصل وقت',
  'Europe/Istanbul': 'GMT +03:00',
  'Europe/Jersey': 'گرین وچ کا اصل وقت',
  'Europe/Kaliningrad': 'مشرقی یورپ کا معیاری وقت',
  'Europe/Kiev': 'مشرقی یورپ کا معیاری وقت',
  'Europe/Kirov': 'GMT +03:00',
  'Europe/Lisbon': 'مغربی یورپ کا معیاری وقت',
  'Europe/Ljubljana': 'وسطی یورپ کا معیاری وقت',
  'Europe/London': 'گرین وچ کا اصل وقت',
  'Europe/Luxembourg': 'وسطی یورپ کا معیاری وقت',
  'Europe/Madrid': 'وسطی یورپ کا معیاری وقت',
  'Europe/Malta': 'وسطی یورپ کا معیاری وقت',
  'Europe/Mariehamn': 'مشرقی یورپ کا معیاری وقت',
  'Europe/Minsk': 'ماسکو اسٹینڈرڈ ٹائم',
  'Europe/Monaco': 'وسطی یورپ کا معیاری وقت',
  'Europe/Moscow': 'ماسکو اسٹینڈرڈ ٹائم',
  'Europe/Oslo': 'وسطی یورپ کا معیاری وقت',
  'Europe/Paris': 'وسطی یورپ کا معیاری وقت',
  'Europe/Podgorica': 'وسطی یورپ کا معیاری وقت',
  'Europe/Prague': 'وسطی یورپ کا معیاری وقت',
  'Europe/Riga': 'مشرقی یورپ کا معیاری وقت',
  'Europe/Rome': 'وسطی یورپ کا معیاری وقت',
  'Europe/Samara': 'سمارا اسٹینڈرڈ ٹائم',
  'Europe/San_Marino': 'وسطی یورپ کا معیاری وقت',
  'Europe/Sarajevo': 'وسطی یورپ کا معیاری وقت',
  'Europe/Saratov': 'GMT +04:00',
  'Europe/Simferopol': 'ماسکو اسٹینڈرڈ ٹائم',
  'Europe/Skopje': 'وسطی یورپ کا معیاری وقت',
  'Europe/Sofia': 'مشرقی یورپ کا معیاری وقت',
  'Europe/Stockholm': 'وسطی یورپ کا معیاری وقت',
  'Europe/Tallinn': 'مشرقی یورپ کا معیاری وقت',
  'Europe/Tirane': 'وسطی یورپ کا معیاری وقت',
  'Europe/Ulyanovsk': 'GMT +04:00',
  'Europe/Uzhgorod': 'مشرقی یورپ کا معیاری وقت',
  'Europe/Vaduz': 'وسطی یورپ کا معیاری وقت',
  'Europe/Vatican': 'وسطی یورپ کا معیاری وقت',
  'Europe/Vienna': 'وسطی یورپ کا معیاری وقت',
  'Europe/Vilnius': 'مشرقی یورپ کا معیاری وقت',
  'Europe/Volgograd': 'ماسکو اسٹینڈرڈ ٹائم',
  'Europe/Warsaw': 'وسطی یورپ کا معیاری وقت',
  'Europe/Zagreb': 'وسطی یورپ کا معیاری وقت',
  'Europe/Zaporozhye': 'مشرقی یورپ کا معیاری وقت',
  'Europe/Zurich': 'وسطی یورپ کا معیاری وقت',
  'Indian/Antananarivo': 'مشرقی افریقہ ٹائم',
  'Indian/Chagos': 'بحر ہند ٹائم',
  'Indian/Christmas': 'کرسمس آئلینڈ ٹائم',
  'Indian/Cocos': 'کوکوس آئلینڈز ٹائم',
  'Indian/Comoro': 'مشرقی افریقہ ٹائم',
  'Indian/Kerguelen': 'فرینچ جنوبی اور انٹارکٹک ٹائم',
  'Indian/Mahe': 'سیشلیز ٹائم',
  'Indian/Maldives': 'مالدیپ کا وقت',
  'Indian/Mauritius': 'ماریشس سٹینڈرڈ ٹائم',
  'Indian/Mayotte': 'مشرقی افریقہ ٹائم',
  'Indian/Reunion': 'ری یونین ٹائم',
  'Pacific/Apia': 'ایپیا سٹینڈرڈ ٹائم',
  'Pacific/Auckland': 'نیوزی لینڈ کا معیاری وقت',
  'Pacific/Bougainville': 'GMT +11:00',
  'Pacific/Chatham': 'چیتھم اسٹینڈرڈ ٹائم',
  'Pacific/Chuuk': 'چوک ٹائم',
  'Pacific/Easter': 'ایسٹر آئلینڈ کا معیاری وقت',
  'Pacific/Efate': 'وانوآٹو سٹینڈرڈ ٹائم',
  'Pacific/Enderbury': 'فینکس آئلینڈز ٹائم',
  'Pacific/Fakaofo': 'ٹوکیلاؤ ٹائم',
  'Pacific/Fiji': 'فجی سٹینڈرڈ ٹائم',
  'Pacific/Funafuti': 'ٹوالو ٹائم',
  'Pacific/Galapagos': 'گالاپاگوز کا وقت',
  'Pacific/Gambier': 'گیمبیئر ٹائم',
  'Pacific/Guadalcanal': 'سولمن آئلینڈز ٹائم',
  'Pacific/Guam': 'چامورو سٹینڈرڈ ٹائم',
  'Pacific/Honolulu': 'ہوائی الیوٹیئن اسٹینڈرڈ ٹائم',
  'Pacific/Kiritimati': 'لائن آئلینڈز ٹائم',
  'Pacific/Kosrae': 'کوسرے ٹائم',
  'Pacific/Kwajalein': 'مارشل آئلینڈز ٹائم',
  'Pacific/Majuro': 'مارشل آئلینڈز ٹائم',
  'Pacific/Marquesas': 'مارکیسس ٹائم',
  'Pacific/Midway': 'ساموآ سٹینڈرڈ ٹائم',
  'Pacific/Nauru': 'ناؤرو ٹائم',
  'Pacific/Niue': 'نیئو ٹائم',
  'Pacific/Norfolk': 'نارفوک آئلینڈ کا وقت',
  'Pacific/Noumea': 'نیو کیلیڈونیا سٹینڈرڈ ٹائم',
  'Pacific/Pago_Pago': 'ساموآ سٹینڈرڈ ٹائم',
  'Pacific/Palau': 'پلاؤ ٹائم',
  'Pacific/Pitcairn': 'پٹکائرن ٹائم',
  'Pacific/Pohnpei': 'پوناپے ٹائم',
  'Pacific/Port_Moresby': 'پاپوآ نیو گنی ٹائم',
  'Pacific/Rarotonga': 'کک آئلینڈز سٹینڈرڈ ٹائم',
  'Pacific/Saipan': 'چامورو سٹینڈرڈ ٹائم',
  'Pacific/Tahiti': 'تاہیتی ٹائم',
  'Pacific/Tarawa': 'جلبرٹ آئلینڈز ٹائم',
  'Pacific/Tongatapu': 'ٹونگا سٹینڈرڈ ٹائم',
  'Pacific/Wake': 'ویک آئلینڈ ٹائم',
  'Pacific/Wallis': 'والیز اور فٹونا ٹائم',
  UTC: 'کوآرڈینیٹڈ یونیورسل ٹائم',
};
