module.exports = {
  islamicYear: 'AH',
  persianYear: 'AP',
  gregorianYear: 'yeni era',
  gregorian: [
    'yanvar',
    'Fevral',
    'mart',
    'Aprel',
    'May',
    'İyun',
    'İyul',
    'Avqust',
    'Sentyabr',
    'Oktyabr',
    'Noyabr',
    'dekabr',
  ],
  persian: [
    'Farvardin',
    'Ordibehesht',
    'Khordad',
    'Tir',
    'Mordad',
    'Shahrivar',
    'Mehr',
    'Aban',
    'Azar',
    'Dey',
    'Bahman',
    'Esfand',
  ],
  islamic: [
    'Məhərrəm',
    'Səfər',
    'Rəbiüləvvəl',
    'Rəbiülaxır',
    'Cəmadiyələvvəl',
    'Cəmadiyəlaxır',
    'Rəcəb',
    'Şaban',
    'Ramazan',
    'Şəvval',
    'Zilqədə',
    'Zilhiccə',
  ],
  week: [
    'bazar',
    'bazar ertəsi',
    'çərşənbə axşamı',
    'çərşənbə',
    'cümə axşamı',
    'cümə',
    'şənbə',
  ],
  weekNarrow: ['7', '1', '2', '3', '4', '5', '6'],
};
