module.exports = {
  islamicYear: 'AH',
  persianYear: 'AP',
  gregorianYear: 'después de Cristo',
  gregorian: [
    'enero',
    'febrero',
    'marzo',
    'abril',
    'mayo',
    'junio',
    'julio',
    'agosto',
    'septiembre',
    'octubre',
    'noviembre',
    'diciembre',
  ],
  persian: [
    'farvardin',
    'ordibehesht',
    'khordad',
    'tir',
    'mordad',
    'shahrivar',
    'mehr',
    'aban',
    'azar',
    'dey',
    'bahman',
    'esfand',
  ],
  islamic: [
    'muharram',
    'safar',
    'rabiʻ I',
    'rabiʻ II',
    'jumada I',
    'jumada II',
    'rajab',
    'shaʻban',
    'ramadán',
    'shawwal',
    'dhuʻl-qiʻdah',
    'dhuʻl-hijjah',
  ],
  week: [
    'domingo',
    'lunes',
    'martes',
    'miércoles',
    'jueves',
    'viernes',
    'sábado',
  ],
  weekNarrow: ['D', 'L', 'M', 'X', 'J', 'V', 'S'],
};
