module.exports = {
  islamicYear: 'ère de l’Hégire',
  persianYear: 'Anno Persico',
  gregorianYear: 'après Jésus-Christ',
  gregorian: [
    'janvier',
    'février',
    'mars',
    'avril',
    'mai',
    'juin',
    'juillet',
    'août',
    'septembre',
    'octobre',
    'novembre',
    'décembre',
  ],
  persian: [
    'farvardin',
    'ordibehešt',
    'khordâd',
    'tir',
    'mordâd',
    'šahrivar',
    'mehr',
    'âbân',
    'âzar',
    'dey',
    'bahman',
    'esfand',
  ],
  islamic: [
    'mouharram',
    'safar',
    'rabia al awal',
    'rabia ath-thani',
    'joumada al oula',
    'joumada ath-thania',
    'rajab',
    'chaabane',
    'ramadan',
    'chawwal',
    'dhou al qi`da',
    'dhou al-hijja',
  ],
  week: [
    'dimanche',
    'lundi',
    'mardi',
    'mercredi',
    'jeudi',
    'vendredi',
    'samedi',
  ],
  weekNarrow: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
};
