module.exports = {
  islamicYear: 'Saʻna Hizjria',
  persianYear: 'AP',
  gregorianYear: 'na Christus',
  gregorian: [
    'januari',
    'februari',
    'maart',
    'april',
    'mei',
    'juni',
    'juli',
    'augustus',
    'september',
    'oktober',
    'november',
    'december',
  ],
  persian: [
    'Farvardin',
    'Ordibehesht',
    'Khordad',
    'Tir',
    'Mordad',
    'Shahrivar',
    'Mehr',
    'Aban',
    'Azar',
    'Dey',
    'Bahman',
    'Esfand',
  ],
  islamic: [
    'Moeharram',
    'Safar',
    'Rabiʻa al awal',
    'Rabiʻa al thani',
    'Joemadʻal awal',
    'Joemadʻal thani',
    'Rajab',
    'Sjaʻaban',
    'Ramadan',
    'Sjawal',
    'Doe al kaʻaba',
    'Doe al hizja',
  ],
  week: [
    'zondag',
    'maandag',
    'dinsdag',
    'woensdag',
    'donderdag',
    'vrijdag',
    'zaterdag',
  ],
  weekNarrow: ['Z', 'M', 'D', 'W', 'D', 'V', 'Z'],
};
