module.exports = {
  islamicYear: 'AH',
  persianYear: 'AP',
  gregorianYear: 'naszej ery',
  gregorian: [
    'styczeń',
    'luty',
    'marzec',
    'kwiecień',
    'maj',
    'czerwiec',
    'lipiec',
    'sierpień',
    'wrzesień',
    'październik',
    'listopad',
    'grudzień',
  ],
  persian: [
    'Farwardin',
    'Ordibeheszt',
    'Chordād',
    'Tir',
    'Mordād',
    'Szahriwar',
    'Mehr',
    'Ābān',
    'Āsar',
    'Déi',
    'Bahman',
    'Esfand',
  ],
  islamic: [
    'Muharram',
    'Safar',
    'Rabiʻ I',
    'Rabiʻ II',
    'Dżumada I',
    'Dżumada II',
    'Radżab',
    'Szaban',
    'Ramadan',
    'Szawwal',
    'Zu al-kada',
    'Zu al-hidżdża',
  ],
  week: [
    'niedziela',
    'poniedziałek',
    'wtorek',
    'środa',
    'czwartek',
    'piątek',
    'sobota',
  ],
  weekNarrow: ['n', 'p', 'w', 'ś', 'c', 'p', 's'],
};
