module.exports = {
  islamicYear: 'Hicri',
  persianYear: 'AP',
  gregorianYear: 'Milattan Sonra',
  gregorian: [
    'Ocak',
    'Şubat',
    'Mart',
    'Nisan',
    'Mayıs',
    'Haziran',
    'Temmuz',
    'Ağustos',
    'Eylül',
    'Ekim',
    'Kasım',
    'Aralık',
  ],
  persian: [
    'Ferverdin',
    'Ordibeheşt',
    'Hordad',
    'Tir',
    'Mordad',
    'Şehriver',
    'Mehr',
    'Aban',
    'Azer',
    'Dey',
    'Behmen',
    'Esfend',
  ],
  islamic: [
    'Muharrem',
    'Safer',
    'Rebiülevvel',
    'Rebiülahir',
    'Cemaziyelevvel',
    'Cemaziyelahir',
    'Recep',
    'Şaban',
    'Ramazan',
    'Şevval',
    'Zilkade',
    'Zilhicce',
  ],
  week: [
    'Pazar',
    'Pazartesi',
    'Salı',
    'Çarşamba',
    'Perşembe',
    'Cuma',
    'Cumartesi',
  ],
  weekNarrow: ['P', 'P', 'S', 'Ç', 'P', 'C', 'C'],
};
